### ISSUE TITLE
Is there such "plugin-places for Objective-C?

### ISSUE THREAD

**Issue by pjl1234567** [mapbox/mapbox-plugins-android#1004]
Is there such "plugin-places for Objective-C?

**Comment by LukasPaczos** [comment]
Unfortunately, I don't think so @pjl1234567. Unless there's some alternative @julianrex @chloekraw?

**Comment by julianrex** [comment]
There's https://github.com/mapbox/mapbox-plugins-ios, but these are experimental; most features are in the core SDK.
