### ISSUE TITLE
How can I put a marker inside a circle and each marker and distance 1 km

### ISSUE THREAD

**Issue by eslam2010011** [mapbox/mapbox-plugins-android#1016]
How can I put a marker inside a circle and each marker and distance 1 km

**Comment by langsmith** [comment]
You can use a `SymbolLayer` and `CircleLayer`:

- https://docs.mapbox.com/android/maps/examples/marker-symbol-layer/
- https://docs.mapbox.com/android/maps/examples/style-circles-categorically/

>and each marker and distance 1 km

In terms of specifically 1km, you could look into using the Java SDK's Turf circle methods. The methods can be found in https://github.com/mapbox/mapbox-java/blob/master/services-turf/src/main/java/com/mapbox/turf/TurfTransformation.java and are ports of http://turfjs.org/docs/#circle.

Used in https://docs.mapbox.com/android/java/examples/turf-ring and https://github.com/mapbox/mapbox-android-demo/pull/1047/files#diff-12e72a02bf211ccbf4e6e961a86d522eR285
