### ISSUE TITLE
Adding multiple markers with symbolLayer does not work

### ISSUE THREAD

**Issue by gracedotdotdot** [mapbox/mapbox-plugins-android#1017]
I want to add multiple markers on my map and I typed in my onStyleLoaded

>                 List<Feature> symbolLayerIconFeatureList = new ArrayList<>();
>                 symbolLayerIconFeatureList.add(Feature.fromGeometry(
>                         Point.fromLngLat(31.995560, 34.767070)));
>                 symbolLayerIconFeatureList.add(Feature.fromGeometry(
>                         Point.fromLngLat(31.995979, 34.744110)));
>                 symbolLayerIconFeatureList.add(Feature.fromGeometry(
>                         Point.fromLngLat(31.995010, 34.767380)));
           

  

>                 style.addImage("charge-icon-id", BitmapFactory.decodeResource(
>                         MapboxNavigationActivity.this.getResources(), R.drawable.map_marker_dark));
>                 style.addSource(new GeoJsonSource("charge-source-id",
>                                 FeatureCollection.fromFeatures(symbolLayerIconFeatureList)));

>                 SymbolLayer destinationSymbolLayer = new SymbolLayer("charge-layer-id", "charge-source-id");
>                 destinationSymbolLayer.withProperties(
>                         iconImage("charge-icon-id"),
>                         iconAllowOverlap(true),
>                         iconIgnorePlacement(true)
>                 );
>                 style.addLayer(destinationSymbolLayer);

But it can't be shown, may I ask what is the problem?

**Comment by LukasPaczos** [comment]
This code does not reference any of the plugins. For help setting up the `SymbolLayer` check out our examples https://docs.mapbox.com/android/maps/examples/marker-symbol-layer/.

**Comment by gracedotdotdot** [comment]
But that one is for static symbolLayer and I want to add it dynamically. 
And I thought it is for annotation plugin?

**Comment by LukasPaczos** [comment]
Above example does add the layer in runtime. Here's another example including the user interaction - https://docs.mapbox.com/android/maps/examples/icon-size-change-on-click/. For further assistance please reach out to support or StackOverflow community with tags `mapbox` and `android` (which is monitored by our support team as well).

**Comment by gracedotdotdot** [comment]
So I have done the same thing as the link suggested, why can't I add it?Q
below is my gradle

> apply plugin: 'com.android.application'
> android {
>     compileSdkVersion 28
>     defaultConfig {
>         applicationId "com.graphhopper.navigation.example"
>         minSdkVersion 23
>         targetSdkVersion 28
>         versionCode 9
>         versionName "1.0.0-pre5"
>         testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
>         vectorDrawables.useSupportLibrary = true
>     }
>     buildTypes {
>         release {
>             minifyEnabled true
>             proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
>         }
>     }
>     compileOptions {
>         targetCompatibility 1.8
>         sourceCompatibility 1.8
>     }
> }
> 
> dependencies {
>     implementation fileTree(include: ['*.jar'], dir: 'libs')
>     implementation 'androidx.appcompat:appcompat:1.0.0'
>     implementation 'com.android.support:appcompat-v7:28.1.1'
>     testImplementation 'junit:junit:4.12'
>     implementation 'com.android.volley:volley:1.1.1'
>     implementation 'com.google.android.material:material:1.0.0'
>     implementation 'com.android.support:design:28.1.1'
>     implementation 'androidx.constraintlayout:constraintlayout:1.1.3'
>     implementation 'androidx.coordinatorlayout:coordinatorlayout:1.0.0-alpha1'
>     implementation 'com.google.android.gms:play-services:12.0.1'
>     implementation 'com.google.android.gms:play-services-maps:12.0.1'
>     implementation 'androidx.multidex:multidex:2.0.1'
> 
> 
>     //implementation 'com.graphhopper:directions-api-client:0.10.1-4'
>     implementation 'com.jakewharton:butterknife:10.1.0'
>     annotationProcessor 'com.jakewharton:butterknife-compiler:10.1.0'
>     testImplementation 'junit:junit:4.12'
>     androidTestImplementation 'androidx.test:runner:1.1.0'
>     androidTestImplementation 'androidx.test.espresso:espresso-core:3.1.0'
> 
>     implementation 'com.mapbox.mapboxsdk:mapbox-android-sdk:8.1.0'
>     implementation 'com.mapbox.mapboxsdk:mapbox-android-sdk:8.1.0'
>     implementation 'com.mapbox.mapboxsdk:mapbox-android-navigation:0.41.0'
>     implementation ('com.mapbox.mapboxsdk:mapbox-android-navigation-ui:0.41.0'){
>         exclude group: 'com.mapbox.mapboxsdk',module : 'mapbox-android-plugin-annotation-v7'
>     }
>     implementation 'com.mapbox.mapboxsdk:mapbox-android-plugin-markerview-v8:0.3.0'
>     implementation 'com.mapbox.mapboxsdk:mapbox-android-plugin-places-v8:0.9.0'
>     implementation 'com.mapbox.mapboxsdk:mapbox-android-plugin-annotation-v8:0.7.0'

>     implementation 'com.graphhopper:directions-api-client-hc:0.13.0-pre12'
> }

my mapbox_access_token
    <string name="mapbox_access_token">pk.eyJ1IjoiaGVyc2hpbmUiLCJhIjoiY2p4dWRtdWsxMDJnaDNvdWdocGQxN3c4bCJ9.PBhV8xvcFsEDAAL2bpnfBg</string>
