### ISSUE TITLE
Annotations disappear on phone screen rotate

### ISSUE THREAD

**Issue by SalimHFX** [mapbox/mapbox-plugins-android#1018]
Here's a code snippet : 

      public void onMapReady(@NonNull final MapboxMap mapboxMap) {

              this.mapboxMap = mapboxMap;

              mapboxMap.setStyle(new Style.Builder().fromUri(localStyle), new Style.OnStyleLoaded() {
                @Override
                public void onStyleLoaded(@NonNull Style style) {
                    if(firstMapLoading) {
                        fillManager = new FillManager(mapView, mapboxMap, style);
                        fillManager.addClickListener(fill -> Toast.makeText(getContext(),String.format("Fill clicked"),Toast.LENGTH_SHORT).show());
                        firstMapLoading = false;
                    }
                }
            });
    }

The localStyle variable is a string that references my local json style asset downloaded from mapbox studio

I then have a displayFilled() function that adds a bunch of filled geometry to the map on button click events. This is done by creating a FillOptions object and calling fillManager.create() with the FillOptions object as a parameter. At the end of this function, I copy the style inside my localStyle using : 
`localStyle  = mapboxMap.getStyle.getUri();`

Everything works perfectly except that on phone screen rotate all annotations disappear. Obviously the screen rotation triggers the OnMapReady() function, but why isn't it loaded with the annotations ? Am I copying the style in a wrong way or isn't this the way to go to handle the situation ?

**Comment by LukasPaczos** [comment]
Hey @SalimHFX, is `firstMapLoading` a static variable? This would explain that the code block wrapped in the `if(firstMapLoading)` is not going to be called after the screen rotation.

**Comment by SalimHFX** [comment]
It is static yes, but that was the intent, i.e to only call the wrapped in code once, because I figured that in order to keep the annotations displayed after screen rotation I'd need to only have one Manager, hence the one time initializer.
It seems like I was wrong though cause the annotations still disappear, so I'm wondering what it is I'm doing wrong here

**Comment by SalimHFX** [comment]
It's not static no, why would I do that ? I only have one instance of the Map class (or maybe I got you wrong here on what you mean by the word static ?) 

The variable is a class attribute initiated with a true value, and after the first OnMapReady() call it becomes false, and stays so forever. But that was the intent, i.e to only call the code block wrapped in the if(firstMapLoading) once, because I figured that in order to keep the annotations displayed after screen rotation I'd need to only have one Manager, hence the one time initializer.
It seems like I was wrong though cause the annotations still disappear, so I'm wondering what it is I'm doing wrong here

**Comment by LukasPaczos** [comment]
> It's not static no, why would I do that ?

That'd be an obvious mistake, hence the question :slightly_smiling_face: 

The map is going to be destroyed and recreated during screen rotation, therefore you have to save your state and recreate the annotations if the saved instance is not `null`, it's not going to be done automatically.

**Comment by SalimHFX** [comment]
At what point exactly should I save the state ?
I would assume it has to be done after the annotations are created, but it seems like the only place where I can access the savedInstanceState variable is within the onCreateView and OnViewCreated methods (I'm using a Fragment, on an Activity that would be the onCreate method), but at that point I haven't created my annotations yet (since they're created on button events).

Also, provided I have successfully saved my precedent state, can I access the precedent annotations objects from it in order to recreate them ? As I said, I don't know the complete details of these in compile-time as they're based on user choice

**Comment by LukasPaczos** [comment]
I assume you have some kind of a wrapper object for user input choices which is then a base to create annotations - you need to save those objects to any persistent memory (disk, `ViewModel`, implementation details can vary here) state whenever the map is destroyed (`Fragment#onDestroyView`) and re-add them whenever the map is recreated (`Fragment#onViewCreated` -> `onMapReady` -> `onStyleLoaded`).

As this repo is for bug reports only, please feel free to [contact our support](https://www.mapbox.com/contact/) or reach out on StackOverflow if you're having implementation details troubles. Thanks for using Mapbox!

**Comment by SalimHFX** [comment]
Thank you for your help !
