### ISSUE TITLE
LocationLayerPlugin Navigation Mode Arrow issues

### ISSUE THREAD

**Issue by chean5143** [mapbox/mapbox-plugins-android#102]
I set my LocationLayerPlugin to Navigation mode. However, when I start my navigation, my default blue user icon does not change to arrow, Instead, the new arrow icon is appear together with my default blue user icon.

![21733280_10212666733897500_1054043786_n](https://user-images.githubusercontent.com/22052900/30387610-97d2df86-98df-11e7-959f-ba8cd5cf07c2.png)

**Comment by davols** [comment]
It kind of looks like the `MyLocationView` which is inside the mapbox sdk itself. And from what I've read will be removed in favor of the plugins.

Have you disabled/(or perhaps enabled) the locationview? 
Try
`MapboxMap.setMyLocationEnabled(false);` or remove the enabling (if you have that)

**Comment by chean5143** [comment]
If the locationview is disabled, how could I get my current location?

**Comment by davols** [comment]
> If the locationview is disabled, how could I get my current location?

You could add a `LocationEngineListener` that will return the location. `MyLocationView` is the dot you see, I guess you could set it to another icon which is transparent if you want to keep the logic for locations and just remove the UI. 

(Quite sure `MyLocationView` is the reason you see the dot, but not 100%)

**Comment by chean5143** [comment]
After I disable the locationview, it solve my problem. Thank for the help.
