### ISSUE TITLE
Update `lodash` dependency

### ISSUE THREAD

**Issue by zugaldia** [mapbox/mapbox-plugins-android#1020]
GH is notifying us that one of the dependencies we use to provide code generation for the annotation plugin has a security issue:

![image](https://user-images.githubusercontent.com/6964/61893466-1f23f880-aedc-11e9-9349-f35b566bb107.png)

We should update the dependency to a more recent (secure) version. I've also updated the "automated security fixes" feature to experiment with it.

**Comment by zugaldia** [comment]
See: https://github.com/mapbox/mapbox-plugins-android/pull/1019.

**Comment by langsmith** [comment]
@zugaldia , https://github.com/mapbox/mapbox-plugins-android/pull/1019 resolved this, correct? I'm not seeing any alerts in https://github.com/mapbox/mapbox-plugins-android/settings/alerts.

**Comment by zugaldia** [comment]
@langsmith thanks for checking. I agree, we should be good now. This automated pull requests are :100:.
