### ISSUE TITLE
加载arcgis切图问题

### ISSUE THREAD

**Issue by 739826946** [mapbox/mapbox-plugins-android#1054]
我可以这样加载图层吗？现在地图全是黑的，我抓包获取的个别图片路径是有的。
代码如下，我是仿着js的代码写的。
mapView.getMapAsync(new OnMapReadyCallback() {
            @Override
            public void onMapReady(@NonNull MapboxMap mbm) {
                String url = "http://192.168.31.8:7071/geowebcache/service/wms?LAYERS=wlmq03&FORMAT=image%2Fpng&SERVICE=WMS&REQUEST=GetMap&EXCEPTIONS=application%2Fvnd.ogc.se_inimage&SRS=EPSG%3A3857&BBOX={bbox-epsg-3857}&WIDTH=256&HEIGHT=256";
                TileSet tileSet = new TileSet("{\"tileSize\":\"256\"}", url);
                VectorSource source = new VectorSource("vector-source", tileSet);
                RasterLayer rasterLayer = new RasterLayer("layer-id", "vector-source");
                mapboxMap.setStyle(new Style.Builder()
                                .withSource(source)
                                .withLayer(rasterLayer),
                        new Style.OnStyleLoaded() {
                        }
             }
         });

请问android是否支持这种加载方式，因为我看到

![image](https://user-images.githubusercontent.com/25890534/64951417-70cf7a80-d8b0-11e9-83d1-cc70981a46fe.png)

如果不支持，请问该咋整？
=============分割线============
打破0中文提问，翻译软件这么多，作者需要我翻译成英文提问吗

**Comment by langsmith** [comment]
cc @Chaoba @chriswu42

**Comment by Chaoba** [comment]
@739826946 Please refer to this [demo](https://github.com/mapbox/mapbox-android-demo/blob/master/MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/examples/styles/AddWmsSourceActivity.java).

**Comment by 739826946** [comment]
thanks for replay
