### ISSUE TITLE
Align design between iOS and Android

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-plugins-android#1058]
This issue tracks aligning the design between iOS and Android for the scalebar component:

 - iOS bar is thinner as Android
 - align font color
 - align abbreviation measurement unit

![image](https://user-images.githubusercontent.com/2151639/65853976-7d95a900-e35b-11e9-97e3-01136d00c1e3.png)
![image](https://user-images.githubusercontent.com/2151639/65853982-80909980-e35b-11e9-9a09-6104a8205913.png)

cc @mapbox/maps-android

**Comment by zugaldia** [comment]
cc: @julianrex as our official iOS ambassador.

**Comment by julianrex** [comment]
FYI Some iOS scale bar fixes are happening here: https://github.com/mapbox/mapbox-gl-native/pull/15703 (though mostly layout). 

We could take this opportunity to tweak the defaults & sizes between platforms.
