### ISSUE TITLE
Icon in symbol layer is dismissed when changing the map style

### ISSUE THREAD

**Issue by fightyz** [mapbox/mapbox-plugins-android#1061]
[1570702322603078.mp4.zip](https://github.com/mapbox/mapbox-plugins-android/files/3715133/1570702322603078.mp4.zip)
Pay attention that the airport icon is disappeared after changing the map style

**Comment by Chaoba** [comment]
cc: @chriswu42

**Comment by Chaoba** [comment]
@mapbox/android Any idea what's the root cause?

**Comment by LukasPaczos** [comment]
The airplane image is not shipped with the style itself, it's added manually. Therefore, whenever the style changes, the image needs to be re-added. The discussion of automating this process is at https://github.com/mapbox/mapbox-plugins-android/issues/742.

Fix for this test app issue in https://github.com/mapbox/mapbox-plugins-android/pull/1062.

**Comment by fightyz** [comment]
Thanks for your reply. It works.
