### ISSUE TITLE
Using the annotations plugin with a local mapbox aar

### ISSUE THREAD

**Issue by RNMBuser** [mapbox/mapbox-plugins-android#1064]
Is there any way the annotations plugin can be used with a local MapboxGLAndroidSDK.aar file I compiled myself? I get a 'com.android.builder.dexing.DexArchiveMergerException: Error while merging dex archives'  and a 'Program type already present: com.mapbox.mapboxsdk.BuildConfig' message.

Also, how do I compile the plugin and add features to it? The instructions show only how to use it from a maven repository.

**Comment by LukasPaczos** [comment]
Hey @RNMBuser, thanks for using Mapbox!

It's hard to say what might be causing the clash, are the manifests correct? That said, we do not generally offer support for building from source.

This repository is nothing else than a classic Android project that you can fork.
