### ISSUE TITLE
Marker View position not stable on map zoom

### ISSUE THREAD

**Issue by imagineDev** [mapbox/mapbox-plugins-android#1068]
I am trying to implement a custom marker on the map via Marker View.
I have provided to target latitude and longitude, everything works well but as soon as I zoom the Map the marker view's position changes to a different lat/lng.

Please find my code below and do note:
1. I know Symbol Layer, but I chose Marker View as I want to achieve animations and use 3D images.

2. Same problem with Marker View as well, but in below code I have done custom implementation for the sake of clarity.

3. I have used Lottie Animation View as Marker Image. Surprisingly I works better than ImageView in my case.

```
class Marker3DFragment : BaseFragment() {

    private val markerPosition = LatLng(28.550661, 77.268939)
    private val markerView by lazy {
        LayoutInflater.from(context).inflate(R.layout.layout_marker, null)
    }


    override fun layoutId(): Int = R.layout.fragment_marker_three_d

    override fun initViews(view: View, savedInstanceState: Bundle?) {
        //Ignore - Inherited from BaseFragment
    }

    override fun initToolbar(toolbar: Toolbar) {
        //Ignore - Inherited from BaseFragment
    }

    
    //Inherited from BaseFragment
    override fun initComplete(view: View, savedInstanceState: Bundle?) {

        //Adding my Marker Layout to mapView
        mapView.addView(markerView)


    }

    //Inherited from BaseFragment
    override fun initMapSettings(map: MapboxMap, style: Style) {
        
        map.animateCamera(CameraUpdateFactory.newLatLngZoom(markerPosition, 15.0), 1000)

        updateMarkerView(map)

        mapView.addOnCameraDidChangeListener {
            updateMarkerView(map)
        }

    }


    private fun updateMarkerView(map: MapboxMap) {
        val point = map.projection.toScreenLocation(markerPosition)
        markerView.x = point.x
        markerView.y = point.y
    }

}
```

Please have a look at attached Clip.
Marker stays in correct position when I pan the map, but as soon as I zoom the map, Its position changes to an incorrect location.

![ezgif com-optimize-4](https://user-images.githubusercontent.com/15804567/67678287-417e5400-f9ac-11e9-82a0-3de54818602d.gif)

**Comment by langsmith** [comment]
Please try using https://docs.mapbox.com/android/plugins/overview/markerview . If you continue to have issues, please comment back on this ticket. Thanks !
