### ISSUE TITLE
The scalebar plugin shows incorrect scale after upgraded Mapbox from 8.4.0 to 8.5.1

### ISSUE THREAD

**Issue by ystsoi** [mapbox/mapbox-plugins-android#1075]
After upgraded Mapbox from 8.4.0 to 8.5.1, the scalebar plugin will show different scales for different phones with different screen resolution/density.

scalebar version: com.mapbox.mapboxsdk:mapbox-android-plugin-scalebar-v8:0.3.0

**Comment by LukasPaczos** [comment]
I suspect that any perceived difference comes from https://github.com/mapbox/mapbox-gl-native/pull/15742.

@Chaoba could you verify if the behavior remains correct?

**Comment by Canivek** [comment]
After https://github.com/mapbox/mapbox-gl-native/pull/15742 the distance displayed by the scale bar is incorrect on devices where screen density is different than 1.

Verified by drawing a line of 200 meters and measuring it with the scale bar using following code:

```
    private void setupScaleBarPlugin(MapView mapView, MapboxMap mapboxMap) {
        ScaleBarPlugin scaleBarPlugin = new ScaleBarPlugin(mapView, mapboxMap);
        ScaleBarOptions scaleBarOptions = new ScaleBarOptions(this)
                .setMetricUnit(true);
        scaleBarPlugin.create(scaleBarOptions);
    }

    private void setupLine(Style style, MapboxMap mapboxMap) {
        GeoJsonSource source = new GeoJsonSource("source-id");
        LineLayer lineLayer = new LineLayer("layer-id", source.getId());

        Point startPoint = Point.fromLngLat(0, 0);
        Point endPoint = TurfMeasurement.destination(startPoint, 200, 90, TurfConstants.UNIT_METERS);

        List<Point> pointList = Arrays.asList(startPoint, endPoint);
        source.setGeoJson(LineString.fromLngLats(pointList));

        style.addSource(source);
        style.addLayer(lineLayer);

        mapboxMap.animateCamera(CameraUpdateFactory.newLatLng(new LatLng(startPoint.latitude(), startPoint.longitude())));
    }
```

And using following dependencies:
```
    implementation 'com.mapbox.mapboxsdk:mapbox-android-sdk:8.4.0' // or 8.5.0 for incorrect behavior
    implementation 'com.mapbox.mapboxsdk:mapbox-android-plugin-scalebar-v8:0.3.0'
    implementation 'com.mapbox.mapboxsdk:mapbox-sdk-turf:5.0.0'
```

Following screenshots are on a device with a 2.25 screen density and the black line is 200m:

With mapbox-android-sdk:8.4.0 result is correct:
![scale_bar_ok_8_4_0](https://user-images.githubusercontent.com/10046130/72089576-96273f00-330c-11ea-96b6-8ceedeec4217.jpg)

With mapbox-android-sdk:8.5.0 (or 8.6.0 which is the last stable version when writing these lines)  result is incorrect:
![scale_bar_nok_8_5_0](https://user-images.githubusercontent.com/10046130/72090133-b4416f00-330d-11ea-95cd-b6423eff2f4f.jpg)

I suspect that `Projection#getMetersPerPixelAtLatitude()` method is actually returning meters per dp.

**Comment by Chaoba** [comment]
@Canivek Thanks for your support. I got the same conclusion after my test. @LukasPaczos I believe  the returning value of `Projection#getMetersPerPixelAtLatitude()` is not right.

**Comment by LukasPaczos** [comment]
@Chaoba feel free to take a stab at it, but also keep in mind the accuracy radius value that we use with the `LocationComponent` which provoked https://github.com/mapbox/mapbox-gl-native/pull/15742.

**Comment by Chaoba** [comment]
@Canivek I have add your test method in #1088, it's really a good idea 👍  .

**Comment by Canivek** [comment]
@Chaoba I have looked at your fix, and it will indeed fix the fact that the scale bar doesn't display the correct distance.  
But I do believe that the problem is rather on `Projection#getMetersPerPixelAtLatitude()` or this method is just poorly named? To me, a method with this name returns meters per **screen** pixel. And here it seems to return meters per density independent pixel (dp).

**Comment by Chaoba** [comment]
@Canivek Thanks for your quick response. I agree with you, @LukasPaczos shell we rename `Projection#getMetersPerPixelAtLatitude()` to `Projection#getMetersPerDpAtLatitude()` or something else that won't make misunderstanding？

**Comment by ystsoi** [comment]
MapView allows us to set the pixel ratio, as in:
https://github.com/mapbox/mapbox-gl-native-android/blob/master/MapboxGLAndroidSDKTestApp/src/main/res/layout/activity_camera_test.xml

If I set the pixel ratio to a value different from the screen density, the fix will not work.

For the method name, I think that at least you need to have a better documentation, if not a better name.

**Comment by Chaoba** [comment]
@ystsoi Good catch. If user set this pixel ratio, scale bar will show wrong value. But `Mapview.getPixelRatio()` is private, we can't get it from outside. @tobrun Any idea about it?

**Comment by tobrun** [comment]
Fixing this in https://github.com/mapbox/mapbox-gl-native-android/pull/146

**Comment by Chaoba** [comment]
I will merge the pr of this issue and created a new [issue](https://github.com/mapbox/mapbox-plugins-android/issues/1093) to track the pixel ratio problem.
