### ISSUE TITLE
Map click event and symbol click event are triggered together when click on a symbol.

### ISSUE THREAD

**Issue by boybeak** [mapbox/mapbox-plugins-android#1076]
```
if (clicked on a symbol) {
    just trigger symbol click event.
} else {
    trigger map click
}
```
This is what i want. Now the map click event is triggered before symbol click, so i can't know if map click should return true or false, because I don't know if it clicked on a symbol.

**Comment by LukasPaczos** [comment]
Hey @boybeak thanks for reaching out!

Closing as a duplicate of https://github.com/mapbox/mapbox-plugins-android/issues/966.
