### ISSUE TITLE
how to use bitmap icon 

### ISSUE THREAD

**Issue by frankgogoland** [mapbox/mapbox-plugins-android#1080]
the code like:
new SymbolOptions()
                .withLatLng(new LatLng(60.169091, 24.939876))
                .withIconImage("dog")
                .withIconSize(2.0f)
                .withDraggable(true));

how to fill options with bitmap icon replace dog? I cannot find any code sample regarding this.

**Comment by frankgogoland** [comment]
No anybody support?

**Comment by langsmith** [comment]
Hi @frankgogoland , thanks for using Mapbox. For Mapbox implementation questions, please contact the Mapbox support team via https://support.mapbox.com/hc/en-us/requests/new?ticket_form_id=360000291231. Tickets in this repo are for problems with the Mapbox Plugins for Android.
