### ISSUE TITLE
Do you have the same plugins of ios?

### ISSUE THREAD

**Issue by lily0101** [mapbox/mapbox-plugins-android#1094]
hi,
    I found the document of [Mapbox China plugin for iOS](https://docs.mapbox.com/ios/plugins/overview/?size=n_10_n) , but I don't see the same project in git, do you have open the project in git like the android plugins? I just found a experimental project, but it seems like not the China plugin.

**Comment by langsmith** [comment]
Hi @lily0101 , thanks for your interest in Mapbox.

Documentation about The Mapbox China Plugin for Android can be found at https://docs.mapbox.com/android/plugins/overview/china/

We also have https://www.mapbox.cn/tutorials/android/

You will need a special China Mapbox access token if you want to use any of our China map styles. [Contact our sales team](https://www.mapbox.com/contact/sales/) to start the process of receiving this special China access token.

The Mapbox Android demo app also has a `china` flavor, which you can use with a China access token once you have the token: https://github.com/mapbox/mapbox-android-demo#product-flavors

cc @chriswu42 @Chaoba
