### ISSUE TITLE
Annotation blinking issue with Mapbox version >8.6.3

### ISSUE THREAD

**Issue by AndrKzntsv** [mapbox/mapbox-plugins-android#1130]
We've encountered an issue with symbols blinking when changing positions frequently. The setup is exactly like one described in #1043. 

`SymbolManager` instance is configured with `iconAllowOverlap` set to `true`:
```kotlin
private val symbolManager =
    SymbolManager(mapboxView, mapboxMap, mapboxStyle).apply {
        iconAllowOverlap = true
    }
```

The symbol is updated like this:
```kotlin
roverSymbol.latLng = position
symbolManager.update(roverSymbol)
```

Everything worked fine with the Mapbox version 8.6.3. We check all newer versions – the symbol blinks. 

<p align="center">
  <img alt="Blinking symbol" width="45%" src="https://user-images.githubusercontent.com/25344115/83419769-49b0dd00-a42e-11ea-925a-2e591df0628f.gif" />
</p>

**Comment by langsmith** [comment]
Thanks for the ticket @AndrKzntsv . This flickering is likely the same as discussed at:
- https://github.com/mapbox/mapbox-gl-native-android/issues/392
- https://github.com/mapbox/mapbox-gl-native/issues/16473
- https://github.com/mapbox/mapbox-gl-native-android/issues/360

The fix has already landed in the Maps SDK for Android and will be delivered in the next stable release of the Maps SDK for Android.

**Comment by AndrKzntsv** [comment]
Thank you for the quick reply! Will be waiting for the update.

**Comment by langsmith** [comment]
Great, thanks for your patience.

**Comment by langsmith** [comment]
By the way, @AndrKzntsv , along with `iconAllowOverlap()`, `iconIgnorePlacement()` is another often-used `PropertyFactory` method used to control the visual collision of symbols.

See https://docs.mapbox.com/android/maps/examples/symbol-collision-detection and https://docs.mapbox.com/android/maps/examples/marker-symbol-layer

**Comment by AndrKzntsv** [comment]
Thanks for the advice. Somehow, I've never experimented with this option.

**Comment by mrfaa** [comment]
hi @langsmith is there already a release date for next stable release of the Maps SDK for Android? :)

**Comment by mrfaa** [comment]
Hi @langsmith i updated the Android SDK (9.3.0) but unfortunately i'm experiencing the same issue like described in #16473 and obove.

Any thoughts about this behavior?

**Comment by tomerlevi444** [comment]
+1

**Comment by tobrun** [comment]
Validated with v9.4.0 that this is not an issue anymore:

![ezgif com-video-to-gif (18)](https://user-images.githubusercontent.com/2151639/91407923-4c5f7a80-e843-11ea-8f0b-024a4d9cf419.gif)

For this I updated [Change Symbol example](https://github.com/mapbox/mapbox-plugins-android/blob/master/app/src/main/java/com/mapbox/mapboxsdk/plugins/testapp/activity/annotation/DynamicSymbolChangeActivity.java#L27) to not update the icon image [here](https://github.com/mapbox/mapbox-plugins-android/blob/master/app/src/main/java/com/mapbox/mapboxsdk/plugins/testapp/activity/annotation/DynamicSymbolChangeActivity.java#L86). 
Note that it uses the aforementioned APIs as 

```
          symbolManager.setIconAllowOverlap(true);
          symbolManager.setTextAllowOverlap(true);
```

Configured [here](https://github.com/mapbox/mapbox-plugins-android/blob/master/app/src/main/java/com/mapbox/mapboxsdk/plugins/testapp/activity/annotation/DynamicSymbolChangeActivity.java#L68-L69;).
