### ISSUE TITLE
How i can change polygon fillColor when polygon clicked?

### ISSUE THREAD

**Issue by zohouri** [mapbox/mapbox-plugins-android#1132]
I tried this code to change polygon fillColor in onAnnotationClick, but its not working right!
`fillManager.addClickListener(new OnFillClickListener() {
            @Override
            public void onAnnotationClick(Fill fill) {
                fill.setFillColor("BE2109");
                fillManager.update(fill);
            }
        });`
before click:
![image](https://user-images.githubusercontent.com/35111452/83942652-d5e64a00-a80a-11ea-9d3b-b24eca7c58c1.png)
after click (It should be red not gray):
![image](https://user-images.githubusercontent.com/35111452/83942656-e39bcf80-a80a-11ea-90b4-10931fdb13f0.png)

**Comment by langsmith** [comment]
`"BE2109"` isn't enough. You need `#` in front of the HEX code. 

Try `fill.setFillColor(Color.parseColor("#BE2109"));`

```java
fillManager.addClickListener(new OnFillClickListener() {
                @Override
                public boolean onAnnotationClick(Fill fill) {
                    fill.setFillColor(Color.parseColor("#BE2109"));
                    fillManager.update(fill);
                    return false;
                }
            });
```

![ezgif com-resize](https://user-images.githubusercontent.com/4394910/90272442-49f82c00-de12-11ea-978a-518492c743e7.gif)
