### ISSUE TITLE
Overlapping annotations OnClickListener

### ISSUE THREAD

**Issue by zohouri** [mapbox/mapbox-plugins-android#1134]
I'm drawing a polygon and few lines on it :
![image](https://user-images.githubusercontent.com/35111452/84104476-0278ac80-aa2b-11ea-9702-727eee81a770.png)

When I click on the lines، both OnPolygonClicked & OnLineClicked are called ! i only want top annotation (lines) clickListener to be called. Is there a way to solve this problem?

**Comment by Ph0tonic** [comment]
A fix as been merged and will hopefully be in the next release, see #966 for the issue.

**Comment by langsmith** [comment]
Closing as `0.9.0` has gone out and should resolve this ticket. https://github.com/mapbox/mapbox-plugins-android/issues/1149. Please re-open and comment if this issue is still being seen.
