### ISSUE TITLE
Map click listener (no symbol selected)

### ISSUE THREAD

**Issue by kevinvanmierlo** [mapbox/mapbox-plugins-android#1136]
Right now it's only possible to listen to clicks on symbols. But I want to deselect the symbols when clicked on the map and not on a symbol. Right now there isn't an easy way to know if the user clicked on the map.
Also it would be awesome to make it a little more extensible. Maybe allow the overriding of the MapClickResolver, so we can handle our own click handling.

**Comment by Ph0tonic** [comment]
It seems to me that you can already add a clickListener on the map using `mapboxMap.addOnMapClickListener(...);`.

**Comment by kevinvanmierlo** [comment]
@Ph0tonic Unfortunately not. `addOnMapClickListener` is also used by the plugin and is the default way to see if a symbol is clicked. So if I add another `addOnMapClickListener` it just calls both methods. But there is no way to check if just the map was pressed or a symbol.

**Comment by Ph0tonic** [comment]
You are right, this has been fixed but has not been released yet, see #966 and PR #1124.

**Comment by kevinvanmierlo** [comment]
@Ph0tonic Awesome! I will close this issue then

**Comment by langsmith** [comment]
`0.9.0` has gone out and should resolve this ticket. https://github.com/mapbox/mapbox-plugins-android/issues/1149. Please re-open and comment if this issue is still being seen.
