### ISSUE TITLE
How to use Marker from mapbox-plugins-android instead of the deprecated Marker from previous libraries?

### ISSUE THREAD

**Issue by roboirc** [mapbox/mapbox-plugins-android#1138]
Can you please show me an example.
What do we use instead of Marker object in our current projects?
Thanks

**Comment by langsmith** [comment]
Hi @roboirc, thanks for using Mapbox. Please see:

- https://docs.mapbox.com/android/plugins/examples/symbol-listener/ 
- https://github.com/mapbox/mapbox-plugins-android/blob/master/app/src/main/java/com/mapbox/mapboxsdk/plugins/testapp/activity/annotation/SymbolActivity.java
- https://github.com/mapbox/mapbox-plugins-android/blob/master/app/src/main/java/com/mapbox/mapboxsdk/plugins/testapp/activity/annotation/PressForSymbolActivity.java
- https://github.com/mapbox/mapbox-plugins-android/blob/master/app/src/main/java/com/mapbox/mapboxsdk/plugins/testapp/activity/annotation/BulkSymbolActivity.java
