### ISSUE TITLE
LineLayer is  bizarrely displaying

### ISSUE THREAD

**Issue by BoumBam** [mapbox/mapbox-plugins-android#1151]
Hello, 
I looked for hours about how to use polyline between two points but i cannot find, so I tried to use **LineLayer** and tried to  give custom icon to the two point of the line like below:
`mapView.getMapAsync(new OnMapReadyCallback() {
            @Override
            public void onMapReady(@NonNull final MapboxMap mapboxMap) {

                mapboxMap.setStyle(Style.OUTDOORS, new Style.OnStyleLoaded() {
                    @Override
                    public void onStyleLoaded(@NonNull Style style) {

                        // drawing the dashed line
                        routeCoordinates = new ArrayList<>();

                        routeCoordinates.add(Point.fromLngLat(-29.0023, 25.0803));
                        routeCoordinates.add(Point.fromLngLat(33.4808800004811, -86.7872850166282));

                        style.addSource(new GeoJsonSource("line-source",
                                FeatureCollection.fromFeatures(new Feature[] {
                                        Feature.fromGeometry(
                                                LineString.fromLngLats(routeCoordinates)
                                        )})));

                        style.addLayer(new LineLayer("linelayer", "line-source").withProperties(
                                PropertyFactory.lineDasharray(new Float[] {0.01f, 2f}),
                                PropertyFactory.lineCap(Property.LINE_CAP_ROUND),
                                PropertyFactory.lineJoin(Property.LINE_JOIN_ROUND),
                                PropertyFactory.lineWidth(5f),
                                PropertyFactory.lineColor(Color.parseColor("#e55e5e"))
                        ));

                        // putting the icon to the two points
                        style.addImage("RED_MARKER_ICON_ID", Objects.requireNonNull(BitmapUtils.getBitmapFromDrawable(getResources().getDrawable(R.drawable.from))));
                        SymbolManager symbolManager = new SymbolManager(mapView, mapboxMap, style);
                        symbolManager.create(new SymbolOptions()
                                .withLatLng(new LatLng(-29.0023, 25.0803))
                                .withIconImage("RED_MARKER_ICON_ID"));

                        style.addImage("COMPASS_ICON_ID", Objects.requireNonNull(BitmapUtils.getBitmapFromDrawable(getResources().getDrawable(R.drawable.from))));
                        SymbolManager symbolManager_ = new SymbolManager(mapView, mapboxMap, style);
                        symbolManager_.create(new SymbolOptions()
                                .withLatLng(new LatLng(33.4808800004811, -86.7872850166282))
                                .withIconImage("COMPASS_ICON_ID"));

                    }
                });
            }
        });`

The customs icons are set correctly but position of the **LineLayer** is not correct.
Why **LineLayer** is not on the two customs icons ?
I'm new user ot Mapbox, how **LineLayer** should be used ?

Here bizarre displaying of the **LineLayer**:
![117753393_2717162715219964_6072954209649658951_o](https://user-images.githubusercontent.com/26336351/90154600-d6a2db80-dd79-11ea-8613-907102062658.jpg)

Thanks.

**Comment by langsmith** [comment]
@BoumBam , your coordinates should be in different orders because of `Point.fromLngLat` vs. `new LatLng`. However, they're the same in your code:

`routeCoordinates.add(Point.fromLngLat(-29.0023, 25.0803));` 
and
`.withLatLng(new LatLng(-29.0023, 25.0803))`

**Comment by BoumBam** [comment]
@langsmith what do you mean here: **your coordinates should be in different orders because of Point.fromLngLat vs. new LatLng** ?
I can not understand you.

**Comment by langsmith** [comment]
> zoom the given LineLayer like CameraPosition does

Not sure what you mean. Can you provide more info?

**Comment by BoumBam** [comment]
I want the map to be centred on the two points of the line and visible without scrolling.

The actual map is given like below:
![117723549_2717309575205278_4056291935881997915_o](https://user-images.githubusercontent.com/26336351/90176463-7f603380-dd98-11ea-85c3-e2fa0730f9af.jpg)

I want it to be given, like below:
![117753393_2717162715219964_6072954209649658951_o](https://user-images.githubusercontent.com/26336351/90176493-8b4bf580-dd98-11ea-8ec2-7868a60d4d4e.jpg)

**Comment by langsmith** [comment]
Ah, got it. Ok, thanks. See https://docs.mapbox.com/android/maps/examples/fit-camera-in-bounding-box/. You'll want to use `LatLngBounds` and `newLatLngBounds()`.

Try something like:

```java
LatLngBounds latLngBounds = new LatLngBounds.Builder()
.include(lineStartLatLng)
.include(lineEndLatLng)
.build();
 
mapboxMap.easeCamera(CameraUpdateFactory.newLatLngBounds(latLngBounds, 50), 5000);
```

Play around with methods to get the camera behavior that you want.

<img width="555" alt="Screen Shot 2020-08-13 at 12 22 03 PM" src="https://user-images.githubusercontent.com/4394910/90177614-a6e6da00-dd5f-11ea-92d0-403419f2cd09.png">
<img width="781" alt="Screen Shot 2020-08-13 at 12 22 14 PM" src="https://user-images.githubusercontent.com/4394910/90177634-af3f1500-dd5f-11ea-8711-6c19a50e909a.png">

**Comment by langsmith** [comment]
Going to close this ticket as it seems that everything's been resolved. Thanks for using Mapbox!
