### ISSUE TITLE
Location layer crash after commit with support library update (26.1.0)

### ISSUE THREAD

**Issue by giperwlad** [mapbox/mapbox-plugins-android#116]
Hey guys.

After commit Sep 27 (#111) crash occurs on screen rotates:

    Fatal signal 11 (SIGSEGV), code 1, fault addr 0x0 in tid 1263 
    signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0
     r0 00000000  r1 8b07030f  r2 00000002  r3 3fe37715
     r4 9fb99340  r5 9fb99340  r6 bee6b640  r7 bee6b630
     r8 bee6b698  r9 bee6b638  sl bee6b700  fp b4f07800
     ip 9cdf5cc4  sp bee6b628  lr b6fb1387  pc 9cb1f9f4  cpsr 600b0030
    backtrace:
     #00 pc 000fd9f4  /data/app/com.reverllc.rever-1/lib/arm/libmapbox-gl.so
     #01 pc 000bd715  /data/app/com.reverllc.rever-1/lib/arm/libmapbox-gl.so
     #02 pc 000bf68b  /data/app/com.reverllc.rever-1/lib/arm/libmapbox-gl.so
     #03 pc 000a2541  /system/lib/libart.so (art_quick_generic_jni_trampoline+32)
      #04 pc 0033b8c4  /dev/ashmem/dalvik-alloc space (deleted)

I clone location layer plugin as module and noticed that crash occurs after adding support (26.1.0) dependency and after removing lifecycle (1.0.0-alpha5) dependencies. Because new support version depend on new lifecycle versions. Problem with new lifecycle versions. 

Please solve the problem.

**Comment by tobrun** [comment]
@cammace do you know if this is still an issue? if so, would be great to be included with #148.

**Comment by tobrun** [comment]
Deps have been updated
