### ISSUE TITLE
Navigation plugin

### ISSUE THREAD

**Issue by zugaldia** [mapbox/mapbox-plugins-android#12]
Currently we bundle the Navigation SDK for Android (https://github.com/mapbox/mapbox-navigation-android) with no explicit dependencies on the Map SDK. This makes the Navigation SDK light-weight, well-contained, and suitable of a wide range of applications.

However, there're some specific features that a navigation app would build on top of the Maps SDK (like route layers updated as the user navigate, or traffic https://github.com/mapbox/mapbox-plugins-android/issues/4). Let's bring this functionality as a navigation-focused plugin.

cc: @mapbox/navigation

**Comment by cammace** [comment]
Picking this ticket up, the plugin should be called something like `navigation-viewport` and begin by handling two different occurrences that depend on the `MapboxMap` object. The route line can be drawn in runtime styling with a casing. The other feature being camera adjustments for speed, maneuver zones, etc.

**Comment by zugaldia** [comment]
>  the plugin should be called something like navigation-viewport

Why not simply `NavigationPlugin`? Unless we envision more than one navigation plugin, that name seems the clearer option.

**Comment by Guardiola31337** [comment]
A great feature to have would be to give users the possibility of having the puck centered so the camera animates automatically when receiving indications.

**Comment by cammace** [comment]
@Guardiola31337 the navigation pucks independent from the navigation plugin, the puck can be found in the location layer plugin. For the camera animating as the user traverses along the route, this navigation plugin has the intention to handle this, though it's still in its early days.

**Comment by cammace** [comment]
The Navigation UI Plugin makes this ticket obsolete since it will depend on the map sdk. https://github.com/mapbox/mapbox-navigation-android/tree/master/navigation/libandroid-navigation-ui

closing.

**Comment by zugaldia** [comment]
@cammace is there a ticket on https://github.com/mapbox/mapbox-navigation-android where we could track the release of the new `libandroid-navigation-ui` module?

**Comment by cammace** [comment]
Not really, i'm a bit confused on how we will be tracking projects now with the new issue tracking through ZenHub. I'll work with @ericrwolfe on getting something setup.
