### ISSUE TITLE
Document plugins

### ISSUE THREAD

**Issue by zugaldia** [mapbox/mapbox-plugins-android#13]
Once we're able to publish the plugins to Maven https://github.com/mapbox/mapbox-plugins-android/issues/3 and once we have the first plugin ready https://github.com/mapbox/mapbox-plugins-android/issues/4 (both are happening shortly) we'll want to make this repository available for anyone to use. For this to happen we have to document:

- [ ] the list of available plugins with descriptions
- [ ] information on how to install them via Maven/Gradle
- [ ] examples on how to use them (reference implementation is in the test app)
- [ ] information on how to contribute a plugin

Initially, we can use the README file in this repo but, ideally, we'll integrate this documentation with the rest of the Android docs (new `Plugins` tab in https://www.mapbox.com/android-docs?).

@langsmith Could you add to OP anything I might have missed and run point on this?

@ericrwolfe Do we have a similar ticket for iOS? Do we have any comms plans in the pipeline?

cc:  @cammace @tobrun

**Comment by tobrun** [comment]
this has been merged :tada:, closing
