### ISSUE TITLE
OfflinePluginDownload validation

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-plugins-android#132]
Capturing from https://github.com/mapbox/mapbox-plugins-android/pull/72#discussion-diff-142771213R28 that we still need to add validation of the OfflineDownload builder (eg. the user didn't  add either a camera position or a bounds).

**Comment by cammace** [comment]
AutoValue automatically validates this information with the android annotations. Feel free to reopen if I misunderstood the issue.
