### ISSUE TITLE
Stop showing user location arrow in navigation mode when it is unknown

### ISSUE THREAD

**Issue by cammace** [mapbox/mapbox-plugins-android#139]
Currently, if the location bearing is 0 or null we still point in that direction. Rather than doing this we should make this more clear by removing the arrow and simply showing a dot to remove the implication that the users navigating in an unknown direction.

**Comment by cammace** [comment]
There is a bit of overhead to accomplish this, moving off the 0.4.0 milestone but will tackle it in the near future depending on the nav team needs.

**Comment by zugaldia** [comment]
I'm gonna close this ticket as per https://github.com/mapbox/mapbox-plugins-android/issues/684#issuecomment-433947880 the functionality provided by the Location Layer Plugin is now part of the core Maps SDK (there's no need to add additional plugins) and the plugin is now deprecated. If this ticket is still relevant for the new `LocationComponent`, please cut a new ticket on https://github.com/mapbox/mapbox-gl-native/issues/new?template=android.md. Thanks!
