### ISSUE TITLE
How add cluster plugin to project

### ISSUE THREAD

**Issue by abdullo211** [mapbox/mapbox-plugins-android#141]

**Comment by mdakram** [comment]
[Follow code here](https://github.com/mapbox/mapbox-plugins-android/blob/master/plugins/app/src/main/java/com/mapbox/mapboxsdk/plugins/testapp/activity/MarkerClusterActivity.java)

**Comment by abdullo211** [comment]
I asked how add to gradle file
 dependencies {
    compile 'com.mapbox.mapboxsdk:mapbox-android-plugin-cluster:0.1.0'
} this not working

**Comment by langsmith** [comment]
Hi @abdullo211 , thanks for the message and for using Mapbox. 

The cluster plugin has landed in `master` of this repo, but you should use a SNAPSHOT of it for now. We should be finishing the stable release via Maven in the next couple of days, which means that you can remove the `SNAPSHOT` word from the dependency declaration line in your gradle file.

This should work for you:
```java
dependencies {
compile 'com.mapbox.mapboxsdk:mapbox-android-plugin-cluster:0.1.0-SNAPSHOT'
}
```

**Comment by abdullo211** [comment]
Thanks

**Comment by langsmith** [comment]
You got it @abdullo211 👍

**Comment by abdullo211** [comment]
No, it's not working, I'm waiting now stable version.
