### ISSUE TITLE
In the navigation，LocationLayerPlugin is easy to crash on xiaomi phone when zoom in and zoom out the map

### ISSUE THREAD

**Issue by ivan-shen** [mapbox/mapbox-plugins-android#146]
crash trace:

10-31 10:40:06.747   713   713 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
10-31 10:40:06.747   713   713 F DEBUG   : Build fingerprint: 'xiaomi/mido/mido:6.0.1/MMB29M/V8.5.7.0.MCFCNED:user/release-keys'
10-31 10:40:06.747   713   713 F DEBUG   : Revision: '0'
10-31 10:40:06.747   713   713 F DEBUG   : ABI: 'arm64'
10-31 10:40:06.748   713   713 F DEBUG   : pid: 31561, tid: 31561, name: arrobot.oversea  >>> com.ileja.carrobot.oversea <<<
10-31 10:40:06.749   713   713 F DEBUG   : signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0
10-31 10:40:06.853   713   713 F DEBUG   :     x0   0000000000000000  x1   0000007fd53c7f98  x2   0000007fd53c7ff0  x3   000000558d19cee0
10-31 10:40:06.853   713   713 F DEBUG   :     x4   0000000000000000  x5   0000000000000001  x6   0000000000000000  x7   0000000000000000
10-31 10:40:06.853   713   713 F DEBUG   :     x8   06c08bf1d681607a  x9   000000558b65f730  x10  0000000000000003  x11  0000000000000010
10-31 10:40:06.853   713   713 F DEBUG   :     x12  0000007f8c310af8  x13  000000558b96c490  x14  000000558a308000  x15  0000007f8c310bb8
10-31 10:40:06.853   713   713 F DEBUG   :     x16  0000007f8c309a58  x17  0000000000000000  x18  0000000000000020  x19  0000007fd53c7ff0
10-31 10:40:06.853   713   713 F DEBUG   :     x20  0000007fd53c7f98  x21  000000558aa18c98  x22  000000558ea5acb0  x23  06c08bf1d681607a
10-31 10:40:06.853   713   713 F DEBUG   :     x24  00000000702dd8b0  x25  0000281e00007b49  x26  0000281e00007b49  x27  0000000012d8bbb0
10-31 10:40:06.853   713   713 F DEBUG   :     x28  000000007137d711  x29  0000007fd53c7f50  x30  0000007f6eeb6e68
10-31 10:40:06.853   713   713 F DEBUG   :     sp   0000007fd53c7e40  pc   0000007f6ef063d8  pstate 0000000020000000
10-31 10:40:06.949   713   713 F DEBUG   : 
10-31 10:40:06.949   713   713 F DEBUG   : backtrace:
10-31 10:40:06.949   713   713 F DEBUG   :     #00 pc 00000000002563d8  /data/app/com.ileja.carrobot.oversea-1/lib/arm64/libmapbox-gl.so
10-31 10:40:06.949   713   713 F DEBUG   :     #01 pc 0000000000206e64  /data/app/com.ileja.carrobot.oversea-1/lib/arm64/libmapbox-gl.so
10-31 10:40:06.949   713   713 F DEBUG   :     #02 pc 0000000000121808  /data/app/com.ileja.carrobot.oversea-1/lib/arm64/libmapbox-gl.so
10-31 10:40:06.950   713   713 F DEBUG   :     #03 pc 00000000001248dc  /data/app/com.ileja.carrobot.oversea-1/lib/arm64/libmapbox-gl.so
10-31 10:40:06.950   713   713 F DEBUG   :     #04 pc 0000000001ab8c78  /data/app/com.ileja.carrobot.oversea-1/oat/arm64/base.odex (offset 0xf3d000) (com.mapbox.services.commons.geojson.Feature[] com.mapbox.mapboxsdk.style.sources.GeoJsonSource.querySourceFeatures(java.lang.Object[])+156)
10-31 10:40:06.950   713   713 F DEBUG   :     #05 pc 0000000001ab9268  /data/app/com.ileja.carrobot.oversea-1/oat/arm64/base.odex (offset 0xf3d000) (java.util.List com.mapbox.mapboxsdk.style.sources.GeoJsonSource.querySourceFeatures(com.mapbox.mapboxsdk.style.layers.Filter$Statement)+124)
10-31 10:40:06.950   713   713 F DEBUG   :     #06 pc 0000000001b96804  /data/app/com.ileja.carrobot.oversea-1/oat/arm64/base.odex (offset 0xf3d000) (com.mapbox.services.commons.geojson.Point com.mapbox.mapboxsdk.plugins.locationlayer.LocationLayerPlugin.getCurrentSourcePoint(com.mapbox.mapboxsdk.style.sources.GeoJsonSource)+72)
10-31 10:40:06.951   713   713 F DEBUG   :     #07 pc 0000000001b97914  /data/app/com.ileja.carrobot.oversea-1/oat/arm64/base.odex (offset 0xf3d000) (void com.mapbox.mapboxsdk.plugins.locationlayer.LocationLayerPlugin.setLocation(android.location.Location)+344)
10-31 10:40:06.951   713   713 F DEBUG   :     #08 pc 0000000001b9897c  
/data/app/com.ileja.carrobot.oversea-1/oat/arm64/base.odex (offset 0xf3d000) (void com.mapbox.mapboxsdk.plugins.locationlayer.LocationLayerPlugin.updateLocation(android.location.Location)+304)
10-31 10:40:06.951   713   713 F DEBUG   :     #09 pc 0000000001b98b50  /data/app/com.ileja.carrobot.oversea-1/oat/arm64/base.odex (offset 0xf3d000) (void com.mapbox.mapboxsdk.plugins.locationlayer.LocationLayerPlugin.forceLocationUpdate(android.location.Location)+68)
10-31 10:40:06.951   713   713 F DEBUG   :     #10 pc 00000000017752d4  /data/app/com.ileja.carrobot.oversea-1/oat/arm64/base.odex (offset 0xf3d000) (void com.ileja.carrobot.oversea.navi.view.NavigationView.onProgressChange(android.location.Location, com.mapbox.services.android.navigation.v5.routeprogress.RouteProgress)+120)
10-31 10:40:06.951   713   713 F DEBUG   :     #11 pc 00000000019d7458  /data/app/com.ileja.carrobot.oversea-1/oat/arm64/base.odex (offset 0xf3d000) (void com.mapbox.services.android.navigation.v5.navigation.NavigationEventDispatcher.onProgressChange(android.location.Location, com.mapbox.services.android.navigation.v5.routeprogress.RouteProgress)+460)
10-31 10:40:06.952   713   713 F DEBUG   :     #12 pc 00000000019e0960  /data/app/com.ileja.carrobot.oversea-1/oat/arm64/base.odex (offset 0xf3d000) (void com.mapbox.services.android.navigation.v5.navigation.NavigationService.onNewRouteProgress(android.location.Location, com.mapbox.services.android.navigation.v5.routeprogress.RouteProgress)+548)
10-31 10:40:06.952   713   713 F DEBUG   :     #13 pc 00000000019d460c  /data/app/com.ileja.carrobot.oversea-1/oat/arm64/base.odex (offset 0xf3d000) (void com.mapbox.services.android.navigation.v5.navigation.NavigationEngine$1.run()+176)
10-31 10:40:06.952   713   713 F DEBUG   :     #14 pc 00000000734798f0  /data/dalvik-cache/arm64/system@framework@boot.oat (offset 0x24c8000)

**Comment by cammace** [comment]
```
com.mapbox.mapboxsdk.style.sources.GeoJsonSource.querySourceFeatures
```

I believe we change this behavior and have merged the fix in master already. Can you try using the 0.2.0-SNAPSHOT and see if that resolves the issue you are having?

**Comment by tobrun** [comment]
closing in favor of #148
