### ISSUE TITLE
Add SymbolGenerator plugin

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-plugins-android#147]
In the testapp of the upstream Map SDK we support generating images from Views to be used as Symbols for a SymbolLayer. Since the code isn't part of the SDK itself it would be usefull creating a small plugin around this functionality.

Atm SymbolGenerator only generates symbols from Views but we could look into allowing to inflate from a Layout file. Having an easy way of hanlding click events specific to views would be a great example to incorporate (eg. generate a container view with two buttons, allow to have a click event for each button seperatly).

**Comment by fdermishin-radargeo** [comment]
Where can I find the testapp? I've searched for SymbolGenerator to find example of generating of Symbols, but found nothing.

**Comment by tobrun** [comment]
@fdermishin-radargeo you can find the code in https://github.com/mapbox/mapbox-gl-native/blob/master/platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/style/SymbolGeneratorActivity.java.
