### ISSUE TITLE
Kotlin plugin

### ISSUE THREAD

**Issue by zugaldia** [mapbox/mapbox-plugins-android#15]
This ticket tracks an idea about the _language_ to write the plugin with rather than the actual purpose of the plugin. Considering plugins are well-contained, a plugin would be an ideal place to showcase how to interact with the Maps SDK using only Kotlin.

What do you think @mapbox/android ?

**Comment by tobrun** [comment]
One idea I have been having is using Kotlin extension functions to add functionality to already existing classes. Eg. you can add dynamically add functions to MapboxMap based on the plugins you are pulling in.

**Comment by zugaldia** [comment]
The more I think about this the more I'm convinced that one good path here would be to build a DSL around the map. What if we could do something like this?

```
map {
	annotations {
		for (marker in markers)
			marker { +marker.location }
	}

	sources {
		...
	}

	layers {
		...
	}
}
```

Similar to what Anko does for Android layouts (https://github.com/Kotlin/anko#anko-layouts-wiki).

**Comment by cammace** [comment]
Stale conversation and Kotlin discussion have been being made in gl-internal. Closing
