### ISSUE TITLE
ANR with support library 26.1.0

### ISSUE THREAD

**Issue by bilthon** [mapbox/mapbox-plugins-android#150]
This might have something to do with #116, or it may not. I get this just after adding the `0.2.0-SNAPSHOT` dependency to the gradle.build file, without even having to create an instance of the `LocationLayerPlugin`.

**A few notes**
Since I moved to 26.1.0 I'm just extending a `android.support.v4.app.Fragment` instead of the `LifecycleFragment`. But I'm still using the following architecture components libraries:

```gradle
// Architecture components
compile "android.arch.lifecycle:extensions:1.0.0-rc1"
compile "android.arch.persistence.room:runtime:1.0.0-rc1"
annotationProcessor "android.arch.persistence.room:compiler:1.0.0-rc1"
```

The problem happens when I get out of the app by pressing the back button and then come back to the app. The screen is white, nothing loads and eventually I get an "Application Not Responding" dialog.

This problem is not happening if I go back to support library 25.3.1.

If it helps, [here](https://pastebin.com/t5idsueM)'s the ANR dump file.

**Comment by tobrun** [comment]
We updated to the latest lifecylce components in 0.2.0 of the LocationLayerPlugin:

```
 lifecycleCompiler  : '1.0.0',
 lifecycleRuntime   : '1.0.3'
```
 This version also contains 26.1.0 as a support lib version. Closing.
