### ISSUE TITLE
Compilation error with LocationLayer since Gradle 3.0.0

### ISSUE THREAD

**Issue by Tweener** [mapbox/mapbox-plugins-android#151]
Hi,
I've recently migrated to Android Studio 3.0 after the official release, which came along with Gradle 3.0.0.
Since then, I can't compile my project anymore and I get the following error: 

> * What went wrong:
Execution failed for task ':app:transformDexArchiveWithDexMergerForProdDebug'.
> com.android.build.api.transform.TransformException: com.android.tools.r8.errors.CompilationError: Program type already present: android.arch.core.internal.SafeIterableMap$ListIterator

After some investigation, I found out the cause of this error comes from the MapBox LocationPlugin, with this line: `implementation 'com.mapbox.mapboxsdk:mapbox-android-plugin-locationlayer:0.1.0'`
If I comment this line, compilation is successful.

Could it be that the plugin needs to be updated to be compatible with Gradle 3.0.0? 

Thanks.

**Comment by tobrun** [comment]
@Tweener thank you for the report, the 0.2.0 version in #148 will be build and thus compatible with Gradle 4.1 (gradle android tools 3.0.0). Sorry for the delay, will get the version released asap.

**Comment by Tweener** [comment]
Thanks @tobrun ! I'll be watching this issue.

**Comment by tobrun** [comment]
location layer 0.2.0 has shipped

**Comment by Tweener** [comment]
Thanks a lot!
