### ISSUE TITLE
Add the plugins to jcenter or maven central

### ISSUE THREAD

**Issue by LouisCAD** [mapbox/mapbox-plugins-android#162]
Hi,

I wanted to use markers cluster in my Android app using the MapBox SDK but I did not find the dependency anywhere. Copy pasting the sources is not a solution since it's not properly versioned in addition to being highly inconvenient.

Could you please put the cluster plugin (and other plugins BTW) on jcenter or maven central please?

Thanks!

**Comment by langsmith** [comment]
hey @LouisCAD , thanks for your interest in the plugin and for using Mapbox!

Adding `compile 'com.mapbox.mapboxsdk:mapbox-android-plugin-cluster-utils:0.1.0'` should get you squared away with the plugin. We're very close to adding documentation to this repo, documentation to the plugins page in [our Android docs](https://www.mapbox.com/android-docs/plugins/overview/), and [adding a marker cluster example to our Android demo app](https://github.com/mapbox/mapbox-android-demo/compare/ls-marker-clusters-plugin-example?expand=1).

[All plugin dependencies can be found here](https://www.mapbox.com/android-docs/plugins/overview/#selectively-compiling-plugins)

**Comment by LouisCAD** [comment]
@langsmith Thanks for the link!

How to add the dependencies should be present in the README.md though IMHO to avoid confusion, and the plugins link should be present on the Getting started page of MapBox Android SDK instead of annoying us with basic Android stuff such as how to create an Android Studio project or how to setup an emulator (these things belong to [d.android.com](d.android.com), not Mapbox website!)

**Comment by LouisCAD** [comment]
@langsmith Also, I noticed the links you provided don't include cluster dependency, which is highly misleading. I hope MabBox team will fix that.

**Comment by langsmith** [comment]
Thanks for the feedback @LouisCAD . Yes, we're still obviously figuring out our documentation/communications ecosystem as we've got a growing list of products/tools. I manage a lot of this, so I will take your comments into consideration for the future. 

> I noticed the links you provided don't include cluster dependency, which is highly misleading.

The writing to update these links has largely been finished, but I haven't gotten around to making the actual pull requests yet.

**Comment by langsmith** [comment]
> the plugins link should be present on the Getting started page of MapBox Android 

@LouisCAD , there's a drop-down menu to get to Plugin information from anywhere in the documentation site, but it can sometimes be easy to miss.

![screen shot 2017-11-09 at 10 40 26 am](https://user-images.githubusercontent.com/4394910/32623270-6f4aeb1c-c53a-11e7-94b5-2a3f2cdc068e.png)

**Comment by LouisCAD** [comment]
@langsmith That's what I would say yeah, too easy to miss, especially since once I'm on this page where Google search brought me, I think: "Okay, I'm inside the MapBox Android SDK part of the website, there's the outline on the left, let's get started!"

The fact that MapBox SDK Plugins are classified as a different product from "Map SDK" is highly misleading, since they are not products, but just optional extensions of the MapBox SDK for when you want advanced features that not everyone may need and that not everyone may want to eat the precious methods count inside its app. IMHO, The organisation of the Android stuff needs to be redone because I don't see anyone thinking "I want cluster map markers, this probably is not part of the Map SDK product, right?"
