### ISSUE TITLE
Links Doesn't Work

### ISSUE THREAD

**Issue by nikiizvorski** [mapbox/mapbox-plugins-android#182]
Hi almost all links that are needed so you can find even the slight information about your SDKs and Plugins is broken. Here it is an example:

https://github.com/mapbox/mapbox-plugins-android/tree/master/plugins/app/src/main/java/com/mapbox/mapboxsdk/plugins/testapp

**Comment by langsmith** [comment]
Thanks @nikiizvorski . We recently made a change to the structure of this app, so we're still hunting and squashing random broken links. Do you recall where you originally found the broken link(s) that motivated you to create this ticket?

**Comment by nikiizvorski** [comment]
No i am bumping into a broken links 99% of the time i try to find a solution for something and i really want to show you guys its not good...and when a massive change like that happen need to be documented and added on time.

Thanks

**Comment by langsmith** [comment]
Thanks for your feedback @nikiizvorski .
