### ISSUE TITLE
Offline Plugin

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-plugins-android#19]
This plugin would be a high level wrapper around  offline API.
More information and context in https://github.com/mapbox/mapbox-gl-native/issues/7289.

 - download a region
   - show notification while downloading
     - cancel button
     - customisation configuration
   - handle multiple requests
     - hook into onStartCommand
   - allow binding/unbinding to forward any errors?
   - handle connection state change events
 - bounds selection dialog
 - list offline regions
 - remove offline regions
 - change name offline region
 - update offline region content?
 - navigation?
 - searching for map data?
 - only download on wifi configuration
 - save maps only to SD card configuration?

**Comment by zugaldia** [comment]
A common scenario we hear from developers is being able to automatically launch the download of a few offline regions in the background to provide pre-cached data to users early on. One possible way to facilitate this would be to create sample code that uses a new `OfflineService` which would be in charge of downloading regions in the background without having to show the map or other user interaction.

**Comment by zugaldia** [comment]
cc: @Guardiola31337

**Comment by tobrun** [comment]
I have been kicking tires on an initial implementation. Focus for this version is:

> Providing an easy way to download offline tiles through a foreground service. 

While we could add all features mentioned in OP. I'm focussing on a minimal viable plugin and iterate on the concept with future versions. I'm trying to get a SNAPSHOT released asap with content shared in this comment.

## API proposal

### Foreground service

> A foreground service performs some operation that is noticeable to the user. For example, an audio app would use a foreground service to play an audio track. Foreground services must display a status bar icon. Foreground services continue running even when the user isn't interacting with the app.

Using this type of service matches requirements set out in https://github.com/mapbox/mapbox-gl-native/issues/7289. This requires users to add a AndroidManifest.xml entry and will show a notification to the users while downloading. 

### Explicit broadcasting results/errors

One way of providing communication to developer from a Service is sending out a explicit broadcast containing information if a download has succeeded or failed. This gives the user the ability to start a download in one Android SDK lifecycle aware component and receive results in another. 

### Bound service status updates

While intent broadcasting is a robust way of sending out final results and errors. It does introduce some additional computational overhead which makes them less fit for notifying download status updates. For this I'm thinking about making the service boundable. This allows the user to both show download progress in a notification while showing progress in an Activity (this matches the UX that is available in Google play when you downloading an app).
