### ISSUE TITLE
Improve default notification content

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-plugins-android#201]
<img width="385" alt="screen shot 2017-12-02 at 23 22 09" src="https://user-images.githubusercontent.com/2151639/33520262-b53af088-d7b7-11e7-8e66-cf8ba3ebb217.png">

In screenshot is current show behaviour when downloading a region. "OfflineDownload & Downloading" content be improved by showing something region name / download speed.

**Comment by cammace** [comment]
We should take a similar approach the Navigation SDK uses which allows for passing in a remote view and allowing users to update the information as they wish.
