### ISSUE TITLE
LocationLayer should accept @null attributes for drawables

### ISSUE THREAD

**Issue by fdermishin-radargeo** [mapbox/mapbox-plugins-android#209]
I want to customize appearance of my location using XML. Particularly I want to show only foregroundDrawable and hide backgroundDrawable. For this I add the following style:
```
    <style name="MyLocationLayer" parent="LocationLayer">
        <item name="foregroundDrawable">@drawable/location</item>
        <item name="backgroundDrawable">@null</item>
    </style>
```
and initialize location layer using this style:
`LocationLayerPlugin(mapView, mapboxMap!!, locationEngine, R.style.MyLocationLayer)`

However, location doesn't appear on the map. This happens even if I pass the following (invisible) drawable to `backgroundDrawable`:

```
<?xml version="1.0" encoding="utf-8"?>
<selector xmlns:android="http://schemas.android.com/apk/res/android">
    <item>
        <shape android:shape="oval">
            <solid android:color="@color/transparent"/>
            <size android:width="0px" android:height="0px"/>
        </shape>
    </item>
</selector>
```

**Platform: Android**
**Mapbox SDK version: 5.2.0**

### Steps to trigger behavior

 1. Create style for location layer without backgroundDrawable
 2. Add this style to LocationLayerPlugin
 3. Show the map

### Expected behavior
foregroundDrawable is displayed, but backgroundDrawable is not

### Actual behavior
LocationLayer crashes. The exception is caught in MapView, but location is not visible at all.

**Comment by cammace** [comment]
in 0.4.0 I've exposed a LocationLayerOptions class along with a bunch of additional style options such as setting the icon colors. For example, if you want to make the foreground image transparent you can pass in a transparent color either in Java using the options class:
```java
LocationLayerOptions options = LocationLayerOptions.builder(this)
      .foregroundTintColor(Color.TRANSPARENT).build();
    locationLayerPlugin = new LocationLayerPlugin(mapView, mapboxMap, locationEngine, options);
```

or through your style.xml file:
```xml
<item name="foregroundTintColor">#00ffffff</item>
```

> However, location doesn't appear on the map. This happens even if I pass the following (invisible) drawable to backgroundDrawable:

I assume this is happening because the drawable has an invalid size of 0. If you give the drawable a valid size like this:

```xml
<vector
    xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="14dp"
    android:height="14dp"
    android:viewportHeight="14.0"
    android:viewportWidth="14.0">
    <path
        android:fillColor="#00FFFFFF"
        android:pathData="M7,7m-7,0a7,7 0,1 1,14 0a7,7 0,1 1,-14 0"/>
</vector>
```

it should draw as expected.

**Comment by fdermishin-radargeo** [comment]
Thank you, it became a bit more convenient to set custom icons
