### ISSUE TITLE
LocationLayerPlugin: Handling Location Service status changes

### ISSUE THREAD

**Issue by Magurosenbei** [mapbox/mapbox-plugins-android#211]
How can we intercept or callback when the user disabled / enabled location service on runtime with `LocationEngine `or the `LocationLayerPlugin`?

With `android.location.LocationManager` and `android.location.LocationRequest` we can just simply override `onProviderStatus`  `onProviderEnabled` `onProviderDisabled` but that would require us to put up excessive `LocationRequest `to the `LocationManager `which may drain a lot of battery?

**Comment by cammace** [comment]
Hey @Magurosenbei, it sounds like you might be interested in when the user enables/disables the location permission? You can use the PermissionManager for detecting this. Could you clarify your use with the LocationManager and why you cannot directly use the class in Android? 

In either of these cases, none of this sounds relevant to the Location Layer Plugin, therefore, I'm closing.

**Comment by Magurosenbei** [comment]
@cammace The permission manager handles permission changes by the users which is fine. However, what I am looking at is the situation where the user turns off location services from the system task bar. This does not trigger onPause() or onResume() of a fragment / activity. The only way I could think of is to use the android framework's `LocationManager `with `LocationRequest` 's  `onProviderStatus ` `onProviderEnabled` `onProviderDisabled` methods to pause or resume explicitly.

Also I am looking for the proper sequence for pausing and resuming the Location Plugin. Whether I could just simply use `activate()`  `deactivate()`. Do I need to re-add all the listeners or even re-create the plugin?
