### ISSUE TITLE
[LocationLayerPlugin] Navigation puck chop / disappears while navigating 

### ISSUE THREAD

**Issue by danesfeder** [mapbox/mapbox-plugins-android#215]
**Original ticket:** https://github.com/mapbox/mapbox-navigation-android/issues/581

Greetings, I have noticed a bug related to the location layer plugin while in navigation. For now at least we have determined that this bug is on all Vodafone Smart Prime 6 devices (over one thousand devices). 

At all times: the location layer does not animate fluidly on the map.

While in navigation: the location layer sometimes dissapears (it's still there if you zoom in or out) or gets left behind going off-screen even if the navigation camera animates and moves accordingly to the device's location.

I am posting a video recording of the bug, maybe it will be of more help visually in determining the problem. 

Video found [here](https://youtu.be/KHL7kfOwNac)

![whatsapp image 2017-12-10 at 22 52 15](https://user-images.githubusercontent.com/13194727/33809775-c07aec8e-de04-11e7-8c8c-292cc73afa78.jpeg)

cc @tobrun @cammace

**Comment by kingfisherphuoc** [comment]
I got the same issue in `locationLayerPlugin = '0.2.0'` (snapshot version as well) and the issue only occurs when the camera `tilt > 0`. Do you have any suggestion?

**Comment by lucianboboc** [comment]
+1 we're getting quite a few reports signaling this issue as well, any updates on this?

**Comment by ibBogdan** [comment]
+1 i`m also having issues with this. any updates?

**Comment by cammace** [comment]
Thanks for reporting everyone. @tobrun is exploring new ways to handle the navigation puck, especially when tilted, in https://github.com/mapbox/mapbox-plugins-android/pull/220. I'm moving this to the 0.4.0 milestone since the PR hasn't been completed yet.

**Comment by vladgheorghe** [comment]
Hi guys, I'm sorry to insist but for my client's business this bug is currently critical due to the majority of the userbase having devices on which it reproduces.

Is there any possible workaround or quick fix to prevent this from happening until 0.4.0 is released ?

**Comment by vicolmoldoveanu** [comment]
Interested about a quickfix also, we're having this issue on around ~4000 devices with a major impact on user experience.

**Comment by vladgheorghe** [comment]
We noticed that the bugs reproduce at the same time on different devices. Recently, with the dynamic camera update, whenever a zoom transition occurs they snap back into position immediately. 

I uploaded 2 videos where you can see how the bug happens always in sync across devices.

Any updates on this issue ?

https://youtu.be/OAwmpHWj0gE
https://youtu.be/XOg8zyb0hH0

**Comment by danesfeder** [comment]
Hey everyone 👋 thank you for your patience here!  With the latest release of the `LocationLayerPlugin` Maps SDK `6.x` is included with updates to help reduce the chop seen in this ticket or dropping frames on lower powered devices.  Please try it out and see if you're able to recreate on the devices that previously were causing these issues.  I'm going to close this ticket, let's open a new one if we find the issue persists.  Thanks!
