### ISSUE TITLE
[LocationLayer] Mapbox freeze when smartphone come back standby

### ISSUE THREAD

**Issue by radaresdeportugal** [mapbox/mapbox-plugins-android#222]
I have a app with this plugin. The 0.2.0-SNAPSHOT works fine, but if i try version 0.3.0-SNAPSHOT the mapbox freeze when come back from standby. in other words, if i press power button and back again the map is freezed (blocked).

Please help.

Thank you.

**Comment by cammace** [comment]
Hey @radaresdeportugal, thanks for reporting, I tried reproducing on master but didn't see any issues following the steps you provided. Can you provide the device information you are using to test this on?

**Comment by radaresdeportugal** [comment]
Please see: https://youtu.be/0LR67XP-9do

Thank you!

**Comment by radaresdeportugal** [comment]
sorted out. I had an error in mapView.onStop (); thank you!
