### ISSUE TITLE
Release location layer 0.3 and places 0.1

### ISSUE THREAD

**Issue by cammace** [mapbox/mapbox-plugins-android#224]
The ticket tracks the release of the location layer plugin 0.3.0 which brings many bug fixes and improvements to the library (see [Changelog](https://github.com/mapbox/mapbox-plugins-android/blob/master/plugin-locationlayer/CHANGELOG.md) for list). The release of the places plugin 0.1.0 with autocomplete widget will also be released.

### Release checklist

- [x] Change version name to proper release versions in `gradle.properties`
- [x] Publish artifacts to Maven Central
- [x] Change version name back to `-SNAPSHOT`
- [x] Update `CHANGELOG.md`'s
- [x] ~Tag releases in GitHub~
- [x] ~Update dependencies in the Maps SDK~
- [x] Close the respective plugin milestones

### Post-release

- [x] Update readme files @langsmith
- [x] Update Javadoc @langsmith
- [x] Update the `constants.js` file in `android-docs` repo @langsmith
- [x] Update the demo app @langsmith
- [x] Update version # in Studio Preview @langsmith
- [ ] Update version # in pthfndr @langsmith

/cc: @mapbox/android

**Comment by lilykaiser** [comment]
Hi @cammace @langsmith is this still in progress or can it be closed?

**Comment by langsmith** [comment]
I've created the two prs above to track final steps. We can close this
