### ISSUE TITLE
How to set the location layer mode to TRACKING_FOLLOW 

### ISSUE THREAD

**Issue by AlexLiuSheng** [mapbox/mapbox-plugins-android#226]
I have changed the my location view to LocationLayerPlugin.But I have a problem about setting TRACKING_FOLLOW mode to plugin just like the deprecated tracking setting of my location view.I need to let map camera rotates with compass and translates with user location.I have noticed the [issue](https://github.com/mapbox/mapbox-plugins-android/issues/67).And do it with the code example you give ,but I found the camera rotation is insensitive.Is there a better way to achieve this function?
```
  locationPlugin = new LocationLayerPlugin(mapView, mapboxMap, locationEngine);
      locationPlugin.setLocationLayerEnabled(LocationLayerMode.COMPASS);
      locationPlugin.addCompassListener(new CompassListener() {
        @Override
        public void onCompassChanged(float userHeading) {
          CameraPosition cameraPosition=new CameraPosition.Builder().bearing(userHeading).build();
          mapboxMap.easeCamera(CameraUpdateFactory.newCameraPosition(cameraPosition),200,false);
        }

        @Override
        public void onCompassAccuracyChange(int compassStatus) {

        }
      });
```

**Comment by pushian** [comment]
@tobrun I am facing the same issue

**Comment by tobrun** [comment]
Thank you for reaching out, this is on our radar to implement.

**Comment by lilykaiser** [comment]
Thank you both for the detailed report! I think this is now being tracked here https://github.com/mapbox/mapbox-plugins-android/issues/259 let's keep the conversation in one place and close this ticket.
