### ISSUE TITLE
ClusterPlugin custom icons.

### ISSUE THREAD

**Issue by radaresdeportugal** [mapbox/mapbox-plugins-android#229]
How to install plugin with multiple icons? For example speed cameras? The icon refers to the speed limit.

Thank you!

**Comment by mf-mindcrewtech** [comment]
Same question, I don't want to use the RED default icon for every marker.

If you found any solution, please let me know.

**Comment by askarsyzdykov** [comment]
I have extended the ClusterItem Interface:

`public interface IconClusterItem extends ClusterItem {
    Icon getIcon();
}`

and have created new ClusterRenderer<T extends IconClusterItem> Class, which extending ClusterRenderer<T> like [this](https://github.com/mapbox/mapbox-plugins-android/blob/master/plugin-cluster/src/main/java/com/mapbox/mapboxsdk/plugins/cluster/clustering/view/DefaultClusterRenderer.java)

after that i have added this code
` else if (!(item.getIcon() == null)) {
                            markerOptions.icon(item.getIcon());
                        }`

in method CreateMarkerTask::perform

**Comment by yeyeya1008** [comment]
@askarsyzdykov Hi, I changed my code as you do. but it doesn't work. It seems like method perform is not being called when I load the map. I'm sorry but can you let me know how it works details ? or please share your full code for your project.

**Comment by askarsyzdykov** [comment]
@yeyeya1008 hi, 
you can see in [this](https://github.com/askarsyzdykov/mapbox-plugins-android) project. In my [commit](https://github.com/askarsyzdykov/mapbox-plugins-android/commit/56a83c7a71db3dd262dec092d13e972f2e70fb2c) you can see my changes that related with drawing marker's icon within clusterization.

On this picture you can see results of my commit

![2018-05-21 16 12 10](https://user-images.githubusercontent.com/3222305/40302886-7999ddc4-5d12-11e8-9382-57b55ebeb5e6.jpg)

**Comment by mf-mindcrewtech** [comment]
Hi , whoever is looking for clustering with custom icons. refer this code.

https://github.com/MaroofAhmedSiddique/MapBoxCustomClustering

thank me later ;)

**Comment by yeyeya1008** [comment]
@askarsyzdykov @mf-mindcrewtech Thank you all!! 👍
