### ISSUE TITLE
Question :: Is there any way to change the cluster color

### ISSUE THREAD

**Issue by mf-mindcrewtech** [mapbox/mapbox-plugins-android#230]
Hello, I just want to use blue color for all clusters.

No matter what count is in between. I already import the cluster-plugin library in my project, but not able to change the color in DefaultClusterRenderer class in getColor() method. Anny help really appreciate.

**Comment by langsmith** [comment]
Closing in favor of https://github.com/mapbox/mapbox-plugins-android/issues/229
