### ISSUE TITLE
Cluster plugin

### ISSUE THREAD

**Issue by debjitk** [mapbox/mapbox-plugins-android#234]
Is the cluster plugin capable of handling a few thousands of points ?

**Comment by langsmith** [comment]
Hi @debjitk , it should be able to, although I've never personally tested it with that many points. Give it a shot and report back!

**Comment by debjitk** [comment]
Yes I am evaluating the same now. Would not it be better if we cluster the data prior and then add markers. I was trying to port supercluster alogorithm in JAVA. Working on it.

**Comment by cammace** [comment]
There are two options for clustering. One way is to add a geoJson source and then using runtime styling to cluster or to use the clustering plugin found in the repo. Since this tickets stale, going ahead and closing

**Comment by debjitk** [comment]
@cammace Not much idea about GeoJSON. Are you suggesting geojson would give faster results ?

**Comment by cammace** [comment]
Yes, using runtime styling to handle clustering is significantly more performant. Have a look at [this example](https://github.com/mapbox/mapbox-android-demo/blob/master/MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/examples/styles/GeoJsonClusteringActivity.java)
