### ISSUE TITLE
Incorrect location view

### ISSUE THREAD

**Issue by psinetron** [mapbox/mapbox-plugins-android#241]
When resume to map the marker of current location breaks up
[<a href="https://ibb.co/dEvTK6"><img src="https://thumb.ibb.co/dEvTK6/2018_01_12_18_27_06.png" alt="2018_01_12_18_27_06" border="0"></a>](url)

**Comment by mdakram** [comment]
it seems its not related to **mapbox-plugins-android**  please see [https://github.com/mapbox/mapbox-gl-native/issues/10761](this issue) which has been fixed. please try latest release.

**Comment by cammace** [comment]
This was an issue with the previous (now deprecated) My Location View which as @mdakram points out, is different than the new Location Layer. The fix would be Integrating the new plugin.
