### ISSUE TITLE
Use latest stable Maps SDK on master

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-plugins-android#252]
I would like to suggest always using the latest stable release of the Maps SDK on master. This allows us to point to the SNAPSHOT build if we haven't updated the stable plugin. Starting from next stable maps release, doing this will be added as a todo in the release checklist. To close this issue let's update the SDK version to 5.3.2 on master. 

cc @cammace @LukasPaczos

**Comment by langsmith** [comment]
pr bump here: https://github.com/mapbox/mapbox-plugins-android/pull/253

👀 I've added a line to the maps sdk release checklist 👇 

<img width="574" alt="screen shot 2018-01-25 at 7 39 07 am" src="https://user-images.githubusercontent.com/4394910/35396902-d73eb222-01a2-11e8-9c7a-cd991aece5e3.png">
