### ISSUE TITLE
Question: LocationLayerPlugin

### ISSUE THREAD

**Issue by psinetron** [mapbox/mapbox-plugins-android#254]
How to folow camera to my location with plugin?
And how to set bearing with plugin?
What is the alternative to this deprecated code:

`map.getTrackingSettings().setMyBearingTrackingMode(MyBearingTracking.GPS);`

**Comment by lilykaiser** [comment]
Hi @psinetron , thanks for asking! This feature request is tracked in https://github.com/mapbox/mapbox-plugins-android/issues/259. I will close your ticket so we can keep the conversation in one place
