### ISSUE TITLE
Bring back camera tracking in location layer

### ISSUE THREAD

**Issue by cammace** [mapbox/mapbox-plugins-android#259]
Theres been a few request on how to have the camera track the year location. This was previously done by setting some APIs state to a specific mode i.e. `TRACKING_FOLLOW`.

**Comment by tobrun** [comment]
We are planning to land this feature with the Maps SDK release v6.0.0 which is currently in beta. To allow this feature to be tested by end developers, we aim to release a beta/snapshot version of this plugin that depends on a maps sdk beta version.

cc @cammace  @LukasPaczos @danesfeder

**Comment by cammace** [comment]
0.5.0-beta.1 is now available on Maven with camera tracking.
