### ISSUE TITLE
Fatal signal 11 (SIGSEGV), code 1 

### ISSUE THREAD

**Issue by kingfisherphuoc** [mapbox/mapbox-plugins-android#265]
I got this issue when using `LocationLayerPlugin` version 0.3.0. I got this bug so often when I close app (deactive location engine) and reopen it (active location engine). Do you have any suggestion? 
```
A/libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0x0 in tid 23208 
```
I am using LostLocationEngine:
```
locationEngine = new LostLocationEngine(context);
 locationEngine.setPriority(HIGH_ACCURACY);
locationEngine.setInterval(0);
 locationEngine.setFastestInterval(1000);
```

**Comment by cammace** [comment]
Closing in favor of https://github.com/mapbox/mapbox-plugins-android/issues/266

**Comment by MArman88** [comment]
I am using 'com.mapbox.mapboxsdk:mapbox-android-sdk:6.5.0-beta.1'.
So I am trying to view two or more maps in the same nested scroll view. My code is simple. I am showing different location on each of these map view.
Now when I am trying to load that page for 2 or more times,( Just starting a activity -> backpress-> restarting the activity). My application crashes.
My Log says: 
09-10 19:00:08.061 18156-18165/[package-name] A/udapper.androi: java_vm_ext.cc:542] JNI DETECTED ERROR IN APPLICATION: thread Thread[5,tid=18165,Native,Thread*=0x75f72d4800,peer=0x138c0198,"FinalizerDaemon"] using JNIEnv* from thread Thread[65,tid=18330,Runnable,Thread*=0x75dcd9fc00,peer=0x0,"{��u
    java_vm_ext.cc:542]     in call to DeleteGlobalRef
    java_vm_ext.cc:542]     from void com.mapbox.mapboxsdk.maps.renderer.MapRenderer.finalize()
    java_vm_ext.cc:542] "FinalizerDaemon" daemon prio=5 tid=5 Runnable
    java_vm_ext.cc:542]   | group="system" sCount=0 dsCount=0 flags=0 obj=0x138c0198 self=0x75f72d4800
    java_vm_ext.cc:542]   | sysTid=18165 nice=4 cgrp=default sched=0/0 handle=0x75e25bc4f0
    java_vm_ext.cc:542]   | state=R schedstat=( 24512343 8666667 39 ) utm=2 stm=0 core=2 HZ=100
    java_vm_ext.cc:542]   | stack=0x75e24b9000-0x75e24bb000 stackSize=1041KB
    java_vm_ext.cc:542]   | held mutexes= "mutator lock"(shared held)
    java_vm_ext.cc:542]   native: #00 pc 00000000003c8d04  /system/lib64/libart.so (art::DumpNativeStack(std::__1::basic_ostream<char, std::__1::char_traits<char>>&, int, BacktraceMap*, char const*, art::ArtMethod*, void*, bool)+220)
    java_vm_ext.cc:542]   native: #01 pc 0000000000498b90  /system/lib64/libart.so (art::Thread::DumpStack(std::__1::basic_ostream<char, std::__1::char_traits<char>>&, bool, BacktraceMap*, bool) const+352)
    java_vm_ext.cc:542]   native: #02 pc 00000000002e9bb8  /system/lib64/libart.so (art::JavaVMExt::JniAbort(char const*, char const*)+972)
    java_vm_ext.cc:542]   native: #03 pc 00000000002e9fe4  /system/lib64/libart.so (art::JavaVMExt::JniAbortV(char const*, char const*, std::__va_list)+116)
    java_vm_ext.cc:542]   native: #04 pc 00000000000fd880  /system/lib64/libart.so (art::(anonymous namespace)::ScopedCheck::AbortF(char const*, ...)+160)
    java_vm_ext.cc:542]   native: #05 pc 00000000000fbf5c  /system/lib64/libart.so (art::(anonymous namespace)::ScopedCheck::CheckPossibleHeapValue(art::ScopedObjectAccess&, char, art::(anonymous namespace)::JniValueType)+416)
    java_vm_ext.cc:542]   native: #06 pc 00000000000fb5a4  /system/lib64/libart.so (art::(anonymous namespace)::ScopedCheck::Check(art::ScopedObjectAccess&, bool, char const*, art::(anonymous namespace)::JniValueType*)+628)
    java_vm_ext.cc:542]   native: #07 pc 00000000000fed94  /system/lib64/libart.so (art::(anonymous namespace)::CheckJNI::DeleteRef(char const*, _JNIEnv*, _jobject*, art::IndirectRefKind)+692)
    java_vm_ext.cc:542]   native: #08 pc 000000000004d470  /data/app/[package-name]-5cpqKJb0iQvMPBot0yCN6g==/lib/arm64/libmapbox-gl.so (???)
    java_vm_ext.cc:542]   native: #09 pc 000000000004d4bc  /data/app/[package-name]-5cpqKJb0iQvMPBot0yCN6g==/lib/arm64/libmapbox-gl.so (???)
    java_vm_ext.cc:542]   native: #10 pc 0000000000131e28  /data/app/[package-name]-5cpqKJb0iQvMPBot0yCN6g==/lib/arm64/libmapbox-gl.so (???)
    java_vm_ext.cc:542]   native: #11 pc 00000000000aa0c8  /data/app/[package-name]-5cpqKJb0iQvMPBot0yCN6g==/lib/arm64/libmapbox-gl.so (???)
    java_vm_ext.cc:542]   native: #12 pc 00000000000aa110  /data/app/[package-name]-5cpqKJb0iQvMPBot0yCN6g==/lib/arm64/libmapbox-gl.so (???)
    java_vm_ext.cc:542]   native: #13 pc 00000000000a6e04  /data/app/[package-name]-5cpqKJb0iQvMPBot0yCN6g==/lib/arm64/libmapbox-gl.so (???)
    java_vm_ext.cc:542]   native: #14 pc 000000000008a20c  /data/app/[package-name]-5cpqKJb0iQvMPBot0yCN6g==/lib/arm64/libmapbox-gl.so (???)
    java_vm_ext.cc:542]   native: #15 pc 000000000008a2d8  /data/app/[package-name]-5cpqKJb0iQvMPBot0yCN6g==/lib/arm64/libmapbox-gl.so (???)
    java_vm_ext.cc:542]   native: #16 pc 000000000008c4e4  /data/app/[package-name]-5cpqKJb0iQvMPBot0yCN6g==/lib/arm64/libmapbox-gl.so (???)
    java_vm_ext.cc:542]   native: #17 pc 00000000005693e0  /system/lib64/libart.so (art_quick_generic_jni_trampoline+144)
    java_vm_ext.cc:542]   native: #18 pc 0000000000560388  /system/lib64/libart.so (art_quick_invoke_stub+584)
    java_vm_ext.cc:542]   native: #19 pc 00000000000cf6b8  /system/lib64/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+200)
    java_vm_ext.cc:542]   native: #20 pc 0000000000282afc  /system/lib64/libart.so (art::interpreter::ArtInterpreterToCompiledCodeBridge(art::Thread*, art::ArtMethod*, art::ShadowFrame*, unsigned short, art::JValue*)+344)
09-10 19:00:08.062 18156-18165/[package-name] A/udapper.androi: java_vm_ext.cc:542]   native: #21 pc 000000000027cbac  /system/lib64/libart.so (bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+960)
    java_vm_ext.cc:542]   native: #22 pc 000000000052fabc  /system/lib64/libart.so (MterpInvokeVirtual+576)
    java_vm_ext.cc:542]   native: #23 pc 0000000000552994  /system/lib64/libart.so (ExecuteMterpImpl+14228)
    java_vm_ext.cc:542]   native: #24 pc 00000000000aec18  /system/framework/boot-core-libart.vdex (java.lang.Daemons$FinalizerDaemon.doFinalize+22)
    java_vm_ext.cc:542]   native: #25 pc 0000000000256d0c  /system/lib64/libart.so (_ZN3art11interpreterL7ExecuteEPNS_6ThreadERKNS_20CodeItemDataAccessorERNS_11ShadowFrameENS_6JValueEb.llvm.3442999494+488)
    java_vm_ext.cc:542]   native: #26 pc 000000000025c8bc  /system/lib64/libart.so (art::interpreter::ArtInterpreterToInterpreterBridge(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame*, art::JValue*)+216)
    java_vm_ext.cc:542]   native: #27 pc 000000000027cb90  /system/lib64/libart.so (bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+932)
    java_vm_ext.cc:542]   native: #28 pc 0000000000530dc4  /system/lib64/libart.so (MterpInvokeDirect+284)
    java_vm_ext.cc:542]   native: #29 pc 0000000000552a94  /system/lib64/libart.so (ExecuteMterpImpl+14484)
    java_vm_ext.cc:542]   native: #30 pc 00000000000aed00  /system/framework/boot-core-libart.vdex (java.lang.Daemons$FinalizerDaemon.runInternal+164)
    java_vm_ext.cc:542]   native: #31 pc 0000000000256d0c  /system/lib64/libart.so (_ZN3art11interpreterL7ExecuteEPNS_6ThreadERKNS_20CodeItemDataAccessorERNS_11ShadowFrameENS_6JValueEb.llvm.3442999494+488)
    java_vm_ext.cc:542]   native: #32 pc 000000000025c8bc  /system/lib64/libart.so (art::interpreter::ArtInterpreterToInterpreterBridge(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame*, art::JValue*)+216)
    java_vm_ext.cc:542]   native: #33 pc 000000000027cb90  /system/lib64/libart.so (bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+932)
    java_vm_ext.cc:542]   native: #34 pc 000000000052fabc  /system/lib64/libart.so (MterpInvokeVirtual+576)
    java_vm_ext.cc:542]   native: #35 pc 0000000000552994  /system/lib64/libart.so (ExecuteMterpImpl+14228)
    java_vm_ext.cc:542]   native: #36 pc 00000000000aeaf8  /system/framework/boot-core-libart.vdex (java.lang.Daemons$Daemon.run+20)
    java_vm_ext.cc:542]   native: #37 pc 0000000000256d0c  /system/lib64/libart.so (_ZN3art11interpreterL7ExecuteEPNS_6ThreadERKNS_20CodeItemDataAccessorERNS_11ShadowFrameENS_6JValueEb.llvm.3442999494+488)
    java_vm_ext.cc:542]   native: #38 pc 000000000025c8bc  /system/lib64/libart.so (art::interpreter::ArtInterpreterToInterpreterBridge(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame*, art::JValue*)+216)
    java_vm_ext.cc:542]   native: #39 pc 000000000027cb90  /system/lib64/libart.so (bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+932)
    java_vm_ext.cc:542]   native: #40 pc 0000000000530a10  /system/lib64/libart.so (MterpInvokeInterface+1376)
    java_vm_ext.cc:542]   native: #41 pc 0000000000552b94  /system/lib64/libart.so (ExecuteMterpImpl+14740)
    java_vm_ext.cc:542]   native: #42 pc 00000000000ca806  /system/framework/boot.vdex (java.lang.Thread.run+12)
    java_vm_ext.cc:542]   native: #43 pc 0000000000256d0c  /system/lib64/libart.so (_ZN3art11interpreterL7ExecuteEPNS_6ThreadERKNS_20CodeItemDataAccessorERNS_11ShadowFrameENS_6JValueEb.llvm.3442999494+488)
    java_vm_ext.cc:542]   native: #44 pc 0000000000520284  /system/lib64/libart.so (artQuickToInterpreterBridge+944)
    java_vm_ext.cc:542]   native: #45 pc 00000000005694fc  /system/lib64/libart.so (art_quick_to_interpreter_bridge+92)
    java_vm_ext.cc:542]   native: #46 pc 0000000000560388  /system/lib64/libart.so (art_quick_invoke_stub+584)
    java_vm_ext.cc:542]   native: #47 pc 00000000000cf6b8  /system/lib64/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+200)
    java_vm_ext.cc:542]   native: #48 pc 00000000004661e4  /system/lib64/libart.so (art::(anonymous namespace)::InvokeWithArgArray(art::ScopedObjectAccessAlreadyRunnable const&, art::ArtMethod*, art::(anonymous namespace)::ArgArray*, art::JValue*, char const*)+104)
    java_vm_ext.cc:542]   native: #49 pc 00000000004672e8  /system/lib64/libart.so (art::InvokeVirtualOrInterfaceWithJValues(art::ScopedObjectAccessAlreadyRunnable const&, _jobject*, _jmethodID*, jvalue*)+424)
    java_vm_ext.cc:542]   native: #50 pc 0000000000492660  /system/lib64/libart.so (art::Thread::CreateCallback(void*)+1116)
    java_vm_ext.cc:542]   native: #51 pc 00000000000847bc  /system/lib64/libc.so (__pthread_start(void*)+36)
    java_vm_ext.cc:542]   native: #52 pc 0000000000023574  /system/lib64/libc.so (__start_thread+68)
    java_vm_ext.cc:542]   at com.mapbox.mapboxsdk.maps.renderer.MapRenderer.finalize(Native method)
    java_vm_ext.cc:542]   at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:250)
    java_vm_ext.cc:542]   at java.lang.Daemons$FinalizerDaemon.runInternal(Daemons.java:237)
    java_vm_ext.cc:542]   at java.lang.Daemons$Daemon.run(Daemons.java:103)
    java_vm_ext.cc:542]   at java.lang.Thread.run(Thread.java:764)
    java_vm_ext.cc:542] 

I understand you guys are busy with other stuff, but can you look into this?
