### ISSUE TITLE
LocationLayerPlugin can not communicate with MapFragment

### ISSUE THREAD

**Issue by TaniaSolo** [mapbox/mapbox-plugins-android#271]
I am using MapFragment for map setup, lifecycle methods are all there, it is convenient. But then If I want to use location services, I can only get a MapboxMap from onMapReady, but not MapView. LocationLayerPlugin need both, however I can not get them from MapFragment.

**Comment by cammace** [comment]
since the map is the view, you have a few options for getting the mapView:
```java

MapFragment map = new MapFragment();
map.getMapAsync(new OnMapReadyCallback(){
  onMapReady(MapboxMap mapboxMap){
    new LocationLayerPlugin((MapView) map.getView(), mapboxMap, null);
  }
}
```

or 

```java
map.getMapAsync(new OnMapReadyCallback(){
  onMapReady(MapboxMap mapboxmap){
       new LocationLayerPlugin((MapView) findViewById(R.id.mapView), mapboxMap, null);
  }
}
```

**Comment by TaniaSolo** [comment]
Oh I see, thanks.
