### ISSUE TITLE
don't display accuracy ring at lower zoom levels

### ISSUE THREAD

**Issue by cammace** [mapbox/mapbox-plugins-android#272]
In some cases, the accuracy circle will be outrageously large causing a huge portion of the map to become blue. To limit this, if the user is at a zoom range about ~14 we should stop showing the accuracy on the map.

**Comment by zugaldia** [comment]
I'm gonna close this ticket as per https://github.com/mapbox/mapbox-plugins-android/issues/684#issuecomment-433947880 the functionality provided by the Location Layer Plugin is now part of the core Maps SDK (there's no need to add additional plugins) and the plugin is now deprecated. If this ticket is still relevant for the new `LocationComponent`, please cut a new ticket on https://github.com/mapbox/mapbox-gl-native/issues/new?template=android.md. Thanks!
