### ISSUE TITLE
Localization should also change function textfields.

### ISSUE THREAD

**Issue by cammace** [mapbox/mapbox-plugins-android#301]
_Originally from @1ec5_

As tail work, consider making this plugin also affect layers whose text-field property is set to a function. In the Mapbox Streets style, for example, U.S. state labels are a function with stops for either {name_en} or {abbr} based on the zoom level.

Without accounting for functions, there will be some inconsistency in state and country labels at low zoom levels. However, expressions will be available in the next release, so it might not be worth spending much effort accommodating functions in the meantime.

**Comment by 1ec5** [comment]
This is equivalent to mapbox/mapbox-gl-native#9902 for iOS and macOS.

**Comment by 1ec5** [comment]
> However, expressions will be available in the next release, so it might not be worth spending much effort accommodating functions in the meantime.

Closing in favor of #301, which is about supporting expressions instead of style functions.
