### ISSUE TITLE
Release Location Layer plugin 0.4.0

### ISSUE THREAD

**Issue by cammace** [mapbox/mapbox-plugins-android#311]
The ticket tracks the release of the location layer plugin 0.4.0 which brings many bug fixes and improvements to the library (see [Changelog](https://github.com/mapbox/mapbox-plugins-android/blob/master/plugin-locationlayer/CHANGELOG.md) for list).

### Release checklist

- [x] Change version name to proper release versions in `gradle.properties`
- [x] Publish artifacts to Maven Central
- [x] Change version name back to `-SNAPSHOT`
- [x] Update `CHANGELOG.md`'s
- [x] Tag releases in GitHub
- [x] Close the respective plugin milestones

### Post-release

- [x] Update readme files @langsmith
- [x] Update Javadoc @langsmith
- [x] Update the `constants.js` file in `android-docs` repo @langsmith
- [x] Update the demo app @langsmith
- [x] Update version # in Studio Preview @langsmith
- [x] Update version # in pthfndr @langsmith

/cc: @mapbox/android

**Comment by cammace** [comment]
Note that this release is pending until https://github.com/mapbox/mapbox-plugins-android/pull/310 gets reviewed and merged

**Comment by vladgheorghe** [comment]
Build fails on release 0.4.0

Error:(2689, 55) No resource found that matches the given name (at 'navigationViewLocationLayerStyle' with value '@style/LocationLayer').

**Comment by danesfeder** [comment]
@vladgheorghe are you using `0.4.0` with the Navigation SDK?  If so, we need to update the nav SDK to accomodate the new default style provided by the plugin that was changed in https://github.com/mapbox/mapbox-plugins-android/pull/263/files#diff-a14596bc53259a2ef3bd185c1f76de34R118.  Otherwise, you will need to continue to use `0.3.0` for now

**Comment by vladgheorghe** [comment]
@danesfeder Yeah, I'm using navigation 0.9.0, any release date for 0.9.1 ?

**Comment by danesfeder** [comment]
@vladgheorghe working on a new release `0.10.0` for today, but we won't be able to get it in for this.  We should have a pretty quick `0.10.1` that will include these updates, but I can't provide a solid timeline on that at this time.

**Comment by cammace** [comment]
> Error:(2689, 55) No resource found that matches the given name

In 0.4 we prefixed all our resources with `mapbox_` to prevent resource conflicts. If you are customizing the user location icon inside your styles.xml, change the parent to `mapbox_LocationLayer`.

https://github.com/mapbox/mapbox-plugins-android/blob/c21b73ab8792a7e2bf902ded64d2f483a126e0e3/app/src/main/res/values/styles.xml#L13

**Comment by vladgheorghe** [comment]
I don’t have any customizations on the location layer, just the navi dependency 😔

**Comment by cammace** [comment]
@vladgheorghe as @danesfeder mentioned then, it will need to be fixed upstream in nav repo, sorry about this.

@langsmith, i've opened tickets in many of the app repos to address updating the plugins to the latest version. Going ahead and checking off these items here so I can close this.
