### ISSUE TITLE
Release Localization 0.1.0

### ISSUE THREAD

**Issue by cammace** [mapbox/mapbox-plugins-android#323]
The ticket tracks the initial release of the Localization Plugin.

### Release checklist

- [x] Change version name to proper release versions in `gradle.properties`
- [x] Publish artifacts to Maven Central
- [x] Change version name back to `-SNAPSHOT`
- [x] Update `CHANGELOG.md`'s
- [x] Tag releases in GitHub
- [x] Close the respective plugin milestones

### Post-release

- [x] Update readme files @langsmith
- [ ] Update Javadoc @langsmith
- [x] Update the `constants.js` file in `android-docs` repo @langsmith
- [x] Update the demo app @langsmith

/cc: @mapbox/android

**Comment by langsmith** [comment]
Readme files update pr is here @cammace https://github.com/mapbox/mapbox-plugins-android/pull/303

**Comment by langsmith** [comment]
Work in progress demo app localization example pr is here:  https://github.com/mapbox/mapbox-android-demo/pull/593

Because this is the initial release, there's not really a version # to update in the demo app. I'm going to check off the demo app checkbox in OP

**Comment by cammace** [comment]
Opened https://github.com/mapbox/android-docs/issues/341 to track adding the Javadoc to the website. Release is finished 🎉
