### ISSUE TITLE
How to change tracking mode icon

### ISSUE THREAD

**Issue by AlexeyIke** [mapbox/mapbox-plugins-android#331]
Hello, i've use map based on 5.4.1 version and location pluging 0.3.0
When i've try to change location mode with locationPlugin.setLocationLayerEnabled(LocationLayerMode.NAVIGATION); // or NONE , TRACKING 
after some changes i've see both icon - circle with blue arrow and  blue dot above it.  How i can change mode (or remove previous mode icon)?
![image](https://user-images.githubusercontent.com/18044177/36830927-6cab95fc-1d71-11e8-80c2-bdc01c193c9a.png)

**Comment by psinetron** [comment]
Can you show your code?

**Comment by cammace** [comment]
The layers seem to be having a visibility issue. Can you upgrade to 0.4 and see if that resolves the issue?

**Comment by AlexeyIke** [comment]
Looks like all work's well. Some my code call old start tracking code.
