### ISSUE TITLE
How to use LocationLayerPlugin with SupportMapFragment?

### ISSUE THREAD

**Issue by LouisCAD** [mapbox/mapbox-plugins-android#333]
Its constructor takes a mandatory `MapView` object which I don't have when using `SupportMapFragment`

**Comment by cammace** [comment]
You can use `findViewById` to grab the mapView and then pass it into the constructor.

**Comment by LouisCAD** [comment]
Shouldn't `SupportMapFragment` expose its `MapView` property directly?

**Comment by cammace** [comment]
Since the class inherits support fragment, you could also call `fragment.getView();` and the map view should be returned.
