### ISSUE TITLE
Limit geocoding to a polygon shape

### ISSUE THREAD

**Issue by langsmith** [mapbox/mapbox-plugins-android#343]
I think it could be cool to have a plugin that delivers various types of search functionalities. Would love to eventually try to take this on. Ways to search:

- Tap on the map to determine a polygon search area
- Draw a line on the map to designate the search area (see gif below)
- other ways?

cc @cammace  @zugaldia @tobrun @LukasPaczos 

![37056808-4cb9bcca-213a-11e8-8e5b-049a546fb080](https://user-images.githubusercontent.com/4394910/38754706-bc76265c-3f17-11e8-91b0-e8c610a91822.gif)

**Comment by langsmith** [comment]
http://www.loopnet.com/for-lease/?sk=22c0282cec08410836cff14a47260f28&bb=5wogvh50vH5t9zvW


![ezgif com-video-to-gif](https://user-images.githubusercontent.com/4394910/43999583-091abcb0-9dc4-11e8-92ae-0787460bcb7a.gif)

**Comment by zugaldia** [comment]
This is really cool. I don't think we need a dedicated plugin for it - either the places plugin, or any related work we do to extend its functionality, could be a good host for this feature.
