### ISSUE TITLE
Localization Plugin Example Code 404

### ISSUE THREAD

**Issue by nitaliano** [mapbox/mapbox-plugins-android#350]
I was adding this plugin to the RN repo today and noticed this section https://github.com/mapbox/mapbox-plugins-android/tree/master/plugin-localization#help-and-usage where it says `Check out it's code` is 404ing

This is the link it is using https://github.com/mapbox/mapbox-plugins-android/tree/master/plugins/app/src/main/java/com/mapbox/mapboxsdk/plugins/testapp

**Comment by langsmith** [comment]
Thanks for the heads up @nitaliano . That link is 404'ing on all of the plugin READMEs because we changed the repo folder structure a while back. I will fix this for all of the plugin README files.
