### ISSUE TITLE
Can't remove shadow from user location icon

### ISSUE THREAD

**Issue by fdermishin-radargeo** [mapbox/mapbox-plugins-android#355]
I tried to use mapbox-android-plugin-locationlayer:0.4.0. I was able to increase size of shadow using elevation:

```
val locationLayerOptions = LocationLayerOptions.builder(this)
                    .backgroundTintColor(Color.TRANSPARENT)  // hide the default icon background
                    .elevation(100f)  // a large shadow
                    .build()
```

However, when I set elevation to 0, the shadow is still there:

```
val locationLayerOptions = LocationLayerOptions.builder(this)
                    .backgroundTintColor(Color.TRANSPARENT)  // hide the default icon background
                    .elevation(0f)  // hiding the shadow doesn't work
                    .build()
```

I would like to have an option to remove the shadow completely, which doesn't seem possible in 0.4.0, so for now I'm stuck with version 0.2.0. That's how it looks with my custom icon:

```
val locationLayerOptions = LocationLayerOptions.builder(this)
        .foregroundDrawable(R.drawable.my_location_icon)  // custom icon
        .backgroundTintColor(Color.TRANSPARENT)  // hide the default icon
        .elevation(0f)  // hiding the shadow doesn't work
        .build()
```

![device-2018-03-12-114122](https://user-images.githubusercontent.com/31691275/37273320-751ba9c6-25ea-11e8-8f72-da2b6a20a4b2.png)

**Comment by cammace** [comment]
I believe this is because you are setting the background tint color to null while also trying to hide the elevation. If the background tint was left to default the elevation would be hidden behind it. I should just look into changing the visibility of the shadow if elevations set to 0. Thanks for reporting this, looking into it now.

**Comment by fdermishin-radargeo** [comment]
Unfortunately setting `backgroundDrawable` doesn't help, because my icon is slightly smaller than the default one, so the shadow under it is still visible. This is the code I tried:

val locationLayerOptions = LocationLayerOptions.builder(this)
        .backgroundDrawable(R.drawable.my_location_icon)
        .foregroundTintColor(Color.TRANSPARENT)  // hide the default icon
        .elevation(0f)  // hide the shadow
        .build()

**Comment by cammace** [comment]
Good to know. At this point then, you'd need to wait for #356 to be merged and a bug release to go ahead and upgrade.
