### ISSUE TITLE
Localization plugin

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-plugins-android#36]
We should have a plugin that automatically localizes map labels into the user’s preferred language. There’s already a robust implementation of this feature in Objective-C targeting the macOS SDK that could be ported to the Android SDK:

https://github.com/mapbox/mapbox-gl-native/blob/cc1ea759a681cadcfd06fd7bdda79ca6deb38c62/platform/macos/app/MapDocument.m#L346-L393
https://github.com/mapbox/mapbox-gl-native/blob/cc1ea759a681cadcfd06fd7bdda79ca6deb38c62/platform/macos/app/MGLVectorSource+MBXAdditions.m

/ref mapbox/mapbox-gl-native#7031
/cc @tobrun @langsmith @ericrwolfe

**Comment by langsmith** [comment]
I'm interested in trying to tackle this as I wade into the plugin world

**Comment by langsmith** [comment]
For (self) reference:

- https://www.mapbox.com/help/change-language

- https://www.mapbox.com/help/change-language/#mapbox-android-sdk
