### ISSUE TITLE
Attempt to remove non-JNI local reference, dumping thread logs

### ISSUE THREAD

**Issue by LukasPaczos** [mapbox/mapbox-plugins-android#362]
We hear complaints from users about `Attempt to remove non-JNI local reference, dumping thread` logs littering the `logcat`. Referencing https://github.com/mapbox/mapbox-gl-native/issues/9688#issuecomment-373004990, we can work around those issues by using FeatureCollections and Functions/Expressions to update `LocationLayer` in various places like https://github.com/mapbox/mapbox-plugins-android/blob/1ccb76cc4b84d9e40ea1720eabf6c6a49e9e98a7/plugin-locationlayer/src/main/java/com/mapbox/mapboxsdk/plugins/locationlayer/LocationLayer.java#L195 and https://github.com/mapbox/mapbox-plugins-android/blob/1ccb76cc4b84d9e40ea1720eabf6c6a49e9e98a7/plugin-locationlayer/src/main/java/com/mapbox/mapboxsdk/plugins/locationlayer/LocationLayer.java#L201, instead of using layer properties setters.

**Comment by cammace** [comment]
This has been quite annoying for me also, will pick this one up :)

**Comment by aquabay** [comment]
I am getting this error whenever I add a ShapeSource to the map.
