### ISSUE TITLE
Failed to resolve: com.mapbox.mapboxsdk:mapbox-android-plugin-offline:0.1.0

### ISSUE THREAD

**Issue by VincenzoWiman** [mapbox/mapbox-plugins-android#364]
I have this error when try to import library

**Comment by cammace** [comment]
The offline plugin isn't released to maven yet ([see repo](https://repo1.maven.org/maven2/com/mapbox/mapboxsdk/)). We plan to release within the month. For now, you can use the SNAPSHOT version.
