### ISSUE TITLE
GeoJson Loader

### ISSUE THREAD

**Issue by bkhezry** [mapbox/mapbox-plugins-android#37]
I want to create plugin for loading `GeoJson` file from `assets`, `path` or `url`. Add `point`, `polyline` and `polygon` of GeoJson on the map with item click listener.
@tobrun @langsmith

**Comment by tobrun** [comment]
@bkhezry cool proposal! feel free to ping us if you need any guidance on this.

**Comment by langsmith** [comment]
Plugin has been made and released 🍾
