### ISSUE TITLE
What does color of location mark means?

### ISSUE THREAD

**Issue by dotPilot** [mapbox/mapbox-plugins-android#375]
I'm using locationLayerPlugin  '0.4.0'. After application start location mark is blue, but after 10 seconds it turns gray. Sometimes it can change color back and forward. Meanwhile GPS label in status bar is always solid(not blinking). What does it mean? Is it a bug?
![clipboard01](https://user-images.githubusercontent.com/12918725/37657435-d1fbbc2a-2c6c-11e8-9a53-43e2c68ca320.png)
![clipboard02](https://user-images.githubusercontent.com/12918725/37657439-d499d9d0-2c6c-11e8-8f0d-9f45b53c5507.png)

**Comment by cammace** [comment]
This is the new stale location state see https://github.com/mapbox/mapbox-plugins-android/issues/58, If you prefer to disable this behavior, you can either use the style attributes of LocationLayerOptions class to disable or extend/shorten the delay until the icon becomes stale.

**Comment by dotPilot** [comment]
But why user location hasn't been updated? According to system location indicator connection is established.
![clipboard01](https://user-images.githubusercontent.com/12918725/37756713-53bb425c-2dcc-11e8-8760-be83aecc5bce.png)
 I call:
```
private void enableLocationPlugin() {
// some code
     getLifecycle().addObserver(mLocationPlugin);
}

public void onConnected() {
        locationEngine.requestLocationUpdates();
}

@Override
public void onLocationChanged(Location location) {
    // some code
    locationEngine.removeLocationEngineListener(this);
}
```
but after reopen app from background location mark is always gray

**Comment by cammace** [comment]
A few things, in `onLocationChanged` you are removing the location engine listener, any reason for requesting 1 location update and then disabling the listener? The plugin should handle requests for you.

When you reopen the app from the background, can you see location updates in the log, does the location icon still remain gray?

**Comment by dotPilot** [comment]
reason: I need to move camera to current location on start
