### ISSUE TITLE
Question about the geojson plugin 

### ISSUE THREAD

**Issue by ChibaniImad** [mapbox/mapbox-plugins-android#387]
How can i change the default Marker with a custom Marker in the GeojsonPlugin ?

**Comment by cammace** [comment]
Looks like options for markers in the GeoJSON plugin aren't exposed. This will be resolved when we introduce the Annotation Plugin. I'd highly recommend loading your GeoJSON as a map style source (see [this example](https://github.com/mapbox/mapbox-android-demo/blob/master/MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/examples/styles/GeojsonLayerInStackActivity.java#L46-L48)) and using [a symbol layer](https://github.com/mapbox/mapbox-android-demo/blob/master/MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/examples/styles/BasicSymbolLayerActivity.java) to style the data on top of your map.
