### ISSUE TITLE
Light API on Building Plugin

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-plugins-android#39]
With https://github.com/mapbox/mapbox-gl-native/pull/9013, we added binding integration for the GL style specification concept of [Light](https://www.mapbox.com/mapbox-gl-js/style-spec/#light). This API allows to change the global light source used for fill extrusion layers.

Instead of exposing the API cfr to the style spec:
 - color
 - intensity
 - anchor
 - position (radian coordinate, azimuth angle & polar angle)

We can expose some facility API around the concept of the placement of the Sun during the day. 

> light conditions in the morning, midday and evening?

cc @mapbox/android

**Comment by zugaldia** [comment]
> We can expose some facility API around the concept of the placement of the Sun during the day.

Love this idea.

**Comment by tobrun** [comment]
The coolest thing we could do with this feature is creating an ObjectAnimator from `Light.java` and animate the light properties to try matching the :sun_with_face: the sun during a day.
