### ISSUE TITLE
Unify moveCamera invocations 

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-plugins-android#394]
Unify the moveCamera invocations instead of calling bearing and latlng seperatly. 

```
  private void setBearing(float bearing) {
    mapboxMap.moveCamera(CameraUpdateFactory.bearingTo(bearing));
  }

  private void setLatLng(LatLng latLng) {
    mapboxMap.moveCamera(CameraUpdateFactory.newLatLng(latLng));
  }
```

**Comment by zugaldia** [comment]
I'm gonna close this ticket as per https://github.com/mapbox/mapbox-plugins-android/issues/684#issuecomment-433947880 the functionality provided by the Location Layer Plugin is now part of the core Maps SDK (there's no need to add additional plugins) and the plugin is now deprecated. If this ticket is still relevant for the new `LocationComponent`, please cut a new ticket on https://github.com/mapbox/mapbox-gl-native/issues/new?template=android.md. Thanks!
