### ISSUE TITLE
LocationPicker plugin

### ISSUE THREAD

**Issue by bkhezry** [mapbox/mapbox-plugins-android#41]
a separate activity for picking the location from the Mapbox map & return a `latitude`, `longitude` and an `address`(if exist the reverse geocoding services ) based on the location picked.
with options for a center of the map, zoom and search view for searching location by text.

**Comment by zugaldia** [comment]
@bkhezry We've got an example of how to do this (one possible approach at least) on [`LocationPickerActivity`](https://github.com/mapbox/mapbox-android-demo/blob/master/MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/labs/LocationPickerActivity.java) and, agreed, it'd be great to extract it as a plugin 👍 .

**Comment by cammace** [comment]
We added a Places Picker UI Component to the Places Plugin which is now available in the latest version, see https://github.com/mapbox/mapbox-plugins-android/pull/262
