### ISSUE TITLE
TensorFlow plugin

### ISSUE THREAD

**Issue by zugaldia** [mapbox/mapbox-plugins-android#43]
There's a flavor of [TensorFlow for mobile](https://www.tensorflow.org/mobile/) ([example code here](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/examples/android/)). Additionally, it was announced during I/O a new effort, [TensorFlow Lite](https://techcrunch.com/2017/05/17/googles-tensorflow-lite-brings-machine-learning-to-android-devices/), that's gonna improve the mobile experience further. I'd love to see a plugin that uses a pre-trained TensorFlow model to provide some additional functionality on top of the map or our services.

@mapbox/android please keep an eye open for interesting models out there that we could apply here.

**Comment by tobrun** [comment]
One of the issues I recently ran into is getting a digital copy of a paper walking map. It would be cool if we could train image recognition to extract routes/lines from paper maps and determining where those match up on our maps. Not very useful, will keep looking for other ideas.

**Comment by zugaldia** [comment]
[Interesting](https://github.com/tensorflow/models/blob/master/slim/nets/mobilenet_v1.md):

> MobileNets are small, low-latency, low-power models parameterized to meet the resource constraints of a variety of use cases. They can be built upon for classification, detection, embeddings and segmentation similar to how other popular large scale models, such as Inception, are used. MobileNets can be run efficiently on mobile devices with TensorFlow Mobile.

**Comment by tobrun** [comment]
Capturing an idea of @ivovandongen: doing client side street sign detection.
