### ISSUE TITLE
"My location" not shown on map

### ISSUE THREAD

**Issue by sreekanth-krishnan** [mapbox/mapbox-plugins-android#451]
I'm trying to use location layer to show user location in the map because 'setMyLocationEnabled' is deprecated.

Below is my code

```

    @SuppressWarnings( {"MissingPermission"})
    private void enableLocationPlugin() {
        // Check if permissions are enabled and if not request
        if (PermissionsManager.areLocationPermissionsGranted(getContext())) {
            // Create a location engine instance
            initializeLocationEngine();

            locationPlugin = new LocationLayerPlugin(((MapView)mapFragment.getView()), mGoogleMap, locationEngine);
            locationPlugin.setLocationLayerEnabled(true);
        }/* else {
            permissionsManager = new PermissionsManager(this);
            permissionsManager.requestLocationPermissions(this);
        }*/
    }

    @SuppressWarnings( {"MissingPermission"})
    private void initializeLocationEngine() {
        locationEngine = new LocationEngineProvider(getContext()).obtainBestLocationEngineAvailable();
        locationEngine.setPriority(LocationEnginePriority.HIGH_ACCURACY);
        locationEngine.activate();
/*
        Location lastLocation = locationEngine.getLastLocation();
        if (lastLocation != null) {
            setCameraPosition(lastLocation);
        } else {
            locationEngine.addLocationEngineListener(this);
        }*/
    }

```

I call `enableLocationPlugin` from `onMapReady` after checking/requesting permissions.
I'm using SupportMapFragment.

I saw the demo app has some issues and shows the location only after navigating away from the app and returning back to it. But even that's not working in my implementation.

**Comment by psinetron** [comment]
I have this problem. I think until the exact location is fixed. 
Need show location at last known location.
Is it a bug?

**Comment by adrianbukros** [comment]
I have the same issue. Following the official sample code for showing the user location the marker shows up after navigating away from the app and returning back to it.

**Comment by cammace** [comment]
> I saw the demo app has some issues and shows the location only after navigating away from the app and returning back to it. But even that's not working in my implementation.

Which activity in particular? I haven't noticed this issue inside the Location Modes activity. 

```java
locationEngine = new LocationEngineProvider(getContext()).obtainBestLocationEngineAvailable();
```

Inside your dependencies, what location provider are you guys using? LOST, Android, or Google Play Services? Could you try forcing a location update using `LocationLayerPlugin.forceLocationUpdate()` and see if the layer shows up. Lastly, is there any logging that occurs during the initialization of the plugin which is related to location?

**Comment by psinetron** [comment]
I think I cracked my brain, but I tested two codes:
code1 :
```
this.map?.addOnMapClickListener { latLng -> 
            val testLocation = Location("fused")
            testLocation.latitude = latLng.latitude
            testLocation.longitude = latLng.longitude
            testLocation.accuracy = 100.0f
            locationLayerPlugin?.forceLocationUpdate(testLocation)
        }
locationLayerPlugin = LocationLayerPlugin(mapView, mapBox, null, R.style.customLocationLayer)
        locationLayerPlugin?.renderMode = RenderMode.NORMAL
        locationLayerPlugin?.cameraMode = CameraMode.TRACKING_GPS
```
This code working. When I click on map I see location marker and camera move to them
![ezgif com-video-to-gif 2](https://user-images.githubusercontent.com/3624600/39363347-a431878c-4a32-11e8-8305-55fc2bb4cdeb.gif)
We see like marker move to tap coordinates and  camera move to marker

Code 2 (copy of code 1 with forceLocation update after initialization):
```
this.map?.addOnMapClickListener { latLng -> 
            val testLocation = Location("fused")
            testLocation.latitude = latLng.latitude
            testLocation.longitude = latLng.longitude
            testLocation.accuracy = 100.0f
            locationLayerPlugin?.forceLocationUpdate(testLocation)
        }
locationLayerPlugin = LocationLayerPlugin(mapView, mapBox, null, R.style.customLocationLayer)
        locationLayerPlugin?.renderMode = RenderMode.NORMAL
        locationLayerPlugin?.cameraMode = CameraMode.TRACKING_GPS
//------Added forceLocationUpdate
val testLocation = Location("fused")
           testLocation.latitude = 59.9374612
            testLocation.longitude = 30.3225837
            testLocation.accuracy = 100.0f
            locationLayerPlugin?.forceLocationUpdate(testLocation)
```
And now code not working. We see taps but don't see location marker. But camera move to taps.
![ezgif com-video-to-gif 3](https://user-images.githubusercontent.com/3624600/39363790-2f2e549a-4a34-11e8-974a-80f5d8758f45.gif)

**Comment by cammace** [comment]
There's been several optimizations and bug fixes which have been made recently since the last 0.5.0 release. Can you try using the SNAPSHOT in your application and see if you are noticing the same behavior or if the issue is resolved?

**Comment by psinetron** [comment]
I can't implement SNAPSHOT version. I don't know why but I have errors on Firebase when add snapshots

**Comment by cammace** [comment]
Will work on doing a 0.5.1 release as soon as possible, stay tuned!

**Comment by psinetron** [comment]
@cammace It not worked on 0.5.3 again

**Comment by Andoresu250** [comment]
@cammace same here its not working properly.

i am using this dependecies:
`implementation ('com.mapbox.mapboxsdk:mapbox-android-sdk:6.1.3@aar') {
        transitive=true
    }
    implementation 'com.mapbox.mapboxsdk:mapbox-android-plugin-locationlayer:0.5.3'
    implementation 'com.mapbox.mapboxsdk:mapbox-android-plugin-offline:0.2.0'

    implementation 'com.mapbox.mapboxsdk:mapbox-android-navigation:0.14.0'
    implementation ('com.mapbox.mapboxsdk:mapbox-android-navigation-ui:0.14.0') {
        transitive = true
    }`
i think that for some reason the GPS is not turning on, the picture #1 its my map activity with the location plugin (followin this guide [https://www.mapbox.com/help/android-navigation-sdk/](url)), my current location is not showing.
The picture #2 is google maps app show the location and the GPS icon on toolbar.
The picture #3 is open again my map activity after open google maps app, now my location is showing properly.
![screenshot 2](https://user-images.githubusercontent.com/11479531/41611189-b789ddb0-73b4-11e8-91ad-d5c35a7b6151.jpg)
![screenshot 3](https://user-images.githubusercontent.com/11479531/41611194-bbfa59e2-73b4-11e8-9411-e99d92252844.jpg)
![screenshot 4](https://user-images.githubusercontent.com/11479531/41611196-bf291284-73b4-11e8-8935-f2bd5da08569.jpg)

**Comment by mhr9o2o** [comment]
I'm facing this issue after updating LocationLayer to 0.8.2

**Comment by johnbulalo** [comment]
The permission isn't showing and and the user location also on 7.0 update

**Comment by johnbulalo** [comment]
is your permission showing? how'd you do it? I'm using the updated android studio 3.5  and some codes are deprecated

**Comment by Andoresu250** [comment]
> is your permission showing? how'd you do it? I'm using the updated android studio 3.5 and some codes are deprecated
> @Andoresu250
i make this little example for you, i hope you find a solution
check in the manifest file the permissions, meta-data(keys), and the service is important that that service be declared on the manifest at the end, also check the HereMapFragment too
https://github.com/Andoresu250/heremap-test

**Comment by Andoresu250** [comment]
> @Andoresu250 still not showing either

i'm running on Android 6.0.1, i have tested on android 5 and 6 before and worked, what Android are you using?

**Comment by mhr9o2o** [comment]
@Andoresu250 Using mapbox sdk version 7.0.0 it's better to remove the location plugin and use the included location component, everything is working fine right now. On previous versions, we had to wait until our default style has been loaded and then enable location indicator otherwise, we couldn't see it. But upgrading to version 7 and using location component, now the style has a listener which indicates that the style has been loaded or not, and then enabling location indicator, it will appear with no problem.

**Comment by mhr9o2o** [comment]
@Andoresu250 please follow these steps:
https://docs.mapbox.com/android/maps/overview/location-component/
