### ISSUE TITLE
Make puck invisible until the first location fix

### ISSUE THREAD

**Issue by LukasPaczos** [mapbox/mapbox-plugins-android#460]
Refs. https://github.com/mapbox/mapbox-plugins-android/pull/458#pullrequestreview-114518101.
The location is displayed before we get the first location fix resulting in the puck being displayed at the null island.
![device-2018-04-23-211653](https://user-images.githubusercontent.com/16925074/39148164-e8247638-473b-11e8-8a70-1c0ebf393382.png)

**Comment by cammace** [comment]
I'm reopening this and reverting PR #476 since this causes the location layer source to not get re-added to the map when the map styles changed resulting in a bunch of `source not found` logging.

**Comment by cammace** [comment]
Plan moving forward on this will be to create an additional constructor which doesn't take in a LocationEngine. In this case, we would call obtainBestLocation and setup the engine ourselves.

**Comment by lilykaiser** [comment]
Do we need a UI prompt before location updates happen?
