### ISSUE TITLE
Bug. Location Layer 0.5.0 forceLocationUpdate not working

### ISSUE THREAD

**Issue by psinetron** [mapbox/mapbox-plugins-android#462]
In version 040 I was create LocationLayer without locationEngine because custom location engine works not good.
`LocationLayerPlugin(mapView, map, null, R.style.customLocationLayer)`
I was receive location from native code and it worked perfectly. After update force location update not worked.
`locationLayerPlugin?.forceLocationUpdate(location)`
 And not working Camera modes without locationEngine. Please do anything with module

**Comment by cammace** [comment]
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/5652865/39328598-d1b201ba-4969-11e8-8d3d-015f710fe0a1.gif)

Using the [ManualLocationUpdatesActivity](https://github.com/mapbox/mapbox-plugins-android/blob/master/app/src/main/java/com/mapbox/mapboxsdk/plugins/testapp/activity/location/ManualLocationUpdatesActivity.java) activity inside the testapp, I haven't been able to reproduce the issue with `forceLocationUpdate` not working. 

I'm not sure what camera issues you are seeing either but `forceLocationUpdate` calls the exact same method as if a location update occured inside the locationengine listener, therefore, nothing should be acting different.

Could you provide some code on how your initializing the locationlayer and using it so I can reproduce it?

**Comment by psinetron** [comment]
For example:
```
mapView.getMapAsync { mapboxMap ->
            presenter.setMapboxMap(mapboxMap, mapView)
        }
```
```
fun setMapboxMap(map: MapboxMap, mapView: MapView) {
        this.map = map
        setMapStyle(AppSettings.instance.getMapStyle())


        locationEngine = LocationEngineProvider(view.getContext()).obtainBestLocationEngineAvailable()
        locationLayerPlugin = LocationLayerPlugin(mapView, map, locationEngine, R.style.customLocationLayer)
        locationLayerPlugin?.renderMode = RenderMode.NORMAL
        locationLayerPlugin?.cameraMode = CameraMode.TRACKING
        buildingPlugin = BuildingPlugin(mapView, map)
        buildingPlugin?.setVisibility(true)


        val testLocation = Location("TEST LOCATION")
        testLocation.latitude = 59.9305886
        testLocation.longitude = 30.3331253
        locationLayerPlugin?.forceLocationUpdate(testLocation)
    }
```

And nothing :( I don't see marker of location.

**Comment by psinetron** [comment]
I found a problem. Marker not showed at first moving. And if first location and second location is equals then marker not showed too.

**Comment by cammace** [comment]
Could you try removing the set map style line `setMapStyle(AppSettings.instance.getMapStyle())` and see if that resolves the issue? This might be related to https://github.com/mapbox/mapbox-plugins-android/issues/470 but I wasn't able to reproduce the issue in https://github.com/mapbox/mapbox-plugins-android/pull/471.

**Comment by cammace** [comment]
Duplicate https://github.com/mapbox/mapbox-plugins-android/issues/451
