### ISSUE TITLE
Can't control layer position of LocationLayerPlugin

### ISSUE THREAD

**Issue by rm3dbeckers** [mapbox/mapbox-plugins-android#465]
Having a lot of Symbols and LineStrings on my map, I am not able to see my Location in crowded areas.

It should either be possible to control the layer above/below which the LocationLayerPlugin is being rendered or it should just always render on top of everything.

**Comment by cammace** [comment]
I like the idea of being able to control where exactly the location layer is within the map style layer stack. In other plugins such as traffic and buildings, we let you pass in a string representing the layer you would want the layer to be above in the stack, we could offer the same functionality or possibly even expose an API which can adjust where the locationLayer sits on the map like you mention.

Right now, a simple workaround would be to first add all your custom Symbol/line layers and lastly, add the location layer to the map. When the Location Layer Plugins initialized, the layers are placed at the top of the map style layer stack.

**Comment by Kravet** [comment]
> Right now, a simple workaround would be to first add all your custom Symbol/line layers and lastly, add the location layer to the map.

Hi, to make location layer be on top of my layers I try to reinit LocationEngine with LocationLayerPlugin from scratch on the same map. But in that case exception occurs: `CannotAddSourceException: Source mapbox-location-source already exists`

For that I manually remove "mapbox-location-source" and before all layers that use the source. Looks like an overhead.
```
map?.removeLayer("mapbox-location-shadow")
map?.removeLayer("mapbox-location-layer")
map?.removeLayer("mapbox-location-stroke-layer")
map?.removeLayer("mapbox-location-accuracy-layer")
map?.removeLayer("mapbox-location-bearing-layer")
map?.removeSource("mapbox-location-source")
//then reinit LocationEngine with LocationLayerPlugin 
```

Is there any better way to completely remove "mapbox-location-source" and add it anew.

**Comment by paakjis** [comment]
@Kravet 
I had an issue where I wanted the LocationLayerPlugin to be over all other layers.
I fixed it with Initializing LocationLayerPlugin before I started drawing other layers.
The other layers I added with mapboxMap.addLayerBelow(layer, "mapbox-location-shadow");

**Comment by langsmith** [comment]
The `LocationComponent` should be used instead of the Location Layer Plugin  https://www.mapbox.com/android-docs/maps/overview/location-component/

The `LocationComponent` should automatically place the device location puck (or whatever drawable(s) you're using) on top of all other layers. The `LocationComponentOptions` class has a `layerBelow()` method. [Here it is being used in the the GL-Native Android test app](https://github.com/mapbox/mapbox-gl-native/blob/master/platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/location/LocationModesActivity.java)

**Comment by Kravet** [comment]
I have recently migrated to Location Plugin and it's already deprecated.. But @langsmith thanks for advise.

**Comment by Yulin777** [comment]
`com.mapbox.mapboxsdk.style.sources.CannotAddSourceException: Source mapbox-android-symbol-source already exists`

having the same trouble with the annotation plugin .
what is the best way to set a new style and keep all the symbols?
the exception is thrown when i set new manager with new style
`mapboxMap.setStyle(Style.SATELLITE, style -> {`
`    this.symbolManager = new SymbolManager(this.mapView, this.mapboxMap, newMapStyle);`
 `});`

**Comment by sdtaheri** [comment]
I have this exact same issue. How can we switch the style of app while a SymbolManager is already available for that style? Whatever I do, it crashes.

**Comment by houdayec** [comment]
> `com.mapbox.mapboxsdk.style.sources.CannotAddSourceException: Source mapbox-android-symbol-source already exists`
> 
> having the same trouble with the annotation plugin .
> what is the best way to set a new style and keep all the symbols?
> the exception is thrown when i set new manager with new style
> `mapboxMap.setStyle(Style.SATELLITE, newMapStyle -> {`
> ` this.symbolManager = new SymbolManager(this.mapView, this.mapboxMap, newMapStyle);`
> `});`

Did you find a workaround for your issue? I get the same.

**Comment by LukasPaczos** [comment]
@Yulin777 @sdtaheri2 @houdayec all AnnotationManagers survive style changes on their own, they don't have to be re-instantiated. You should be able to change the style while keeping a reference to the previously created annotation manager and all added annotations should persist. Is that not the case?
