### ISSUE TITLE
LocationLayerPlugin 0.5 not having anymore accuracy animation

### ISSUE THREAD

**Issue by nole87** [mapbox/mapbox-plugins-android#469]
In new 0.5 location plugin there is accuracy circle but no animation it looks bad in my opinion. Can you add animation or add api to disable accuracy circle at all.  Also, how to change gps marker for location layer, with png no vector?

**Comment by cammace** [comment]
> there is accuracy circle but no animation it looks bad in my opinion.

Which animation are you talking about? When the accuracy value changes or when the user is moving from one location to the other? 

> disable accuracy circle at all

While there's no direct API to disable it, you can use the `LocationLayerOptions` class and set the accuracy alpha to 0 which will effectively make the circle invisible.

> how to change gps marker for location layer, with png no vector?

`LocationLayerOptions` also includes an API for changing the gps icon using `gpsDrawable()` which takes in any drawable resource vector or PNG. If you are having issues using a PNG, could you provide the image and the snippet of code you are using that initializes and applies your custom location layer style so I can reproduce?

**Comment by nole87** [comment]
Correct, I find LocationLayerOptions and resolve most of my issues. Animation for circle is missing when circle is small and than big without animation, only see jump from small to big circle. SDK is great btw!

**Comment by LukasPaczos** [comment]
On this note, the accuracy layer disappears when zooming the camera in/out and no `LocationEngine` is set up, meaning in the scenario when we are forcing all the location updates.
