### ISSUE TITLE
Marker Cluster Plugin

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-plugins-android#47]
We could make a reimplementation of  the clustering algorithm found in [Google maps utils library](https://github.com/googlemaps/android-maps-utils). The code for this is apache licensed. This plugin should automatically support clustering of Markers and MarkerViews.

**Comment by mdakram** [comment]
It seems its supporting Markers only not MarkerViews. Or i am missing something?

**Comment by cammace** [comment]
@mdakram markerviews have been deprecated. The clustering api from the google utils library has been ported over. Closing.
