### ISSUE TITLE
Image for navigation

### ISSUE THREAD

**Issue by nole87** [mapbox/mapbox-plugins-android#481]
Dear,

I try hard to set image for navigation mode, more precise GPS_TRACKING mode and GPS icon. I want to use compass image for navigation mode it's circle with bearing image but I don't know how to build that circle and bearing image on north and than set it as png. Is there some converter for vector android images.

**Comment by cammace** [comment]
Drawables include `png`, thus you should be able to pass in a png just like a vector image. For the look you desire, I'd recommend combining the bearing and user icon images [found in the SDK itself](https://github.com/mapbox/mapbox-plugins-android/tree/master/plugin-locationlayer/src/main/res/drawable).
