### ISSUE TITLE
Log warning: can't find source for layer 'mapbox-location-layer'

### ISSUE THREAD

**Issue by stoefln** [mapbox/mapbox-plugins-android#487]
I am getting this after upgrading to MapBox 6.01 and Location Layer Plugin 0.5.0:
```

W/mbgl: {GLThread 8559}[Render]: can't find source for layer 'mapbox-location-layer'
W/mbgl: {GLThread 8559}[Render]: can't find source for layer 'mapbox-location-shadow'
    {GLThread 8559}[Render]: can't find source for layer 'mapbox-location-stroke-layer'
    {GLThread 8559}[Render]: can't find source for layer 'mapbox-location-layer'

```
Also the location position marker is not displayed.

**Comment by khushalimehta** [comment]
@stoefln Try this https://www.youtube.com/watch?v=cIQdB7Lz6tY

**Comment by cammace** [comment]
This has since been fixed and will be in this weeks release 0.5.1. https://github.com/mapbox/mapbox-plugins-android/issues/470

**Comment by stoefln** [comment]
@khushalimehta I figured out that setting a LocationEngine solves my problem. I just wonder because I never needed to set a LocationEngine before. When did this requirement change?

**Comment by softe133** [comment]
I am a beginner, First time uses mapbox . First time, the application run fine but later I facing these types of errors while running the application.

W/ResourceType: Failure getting entry for 0x0108094c (t=7 e=2380) (error -75)
W/art: Before Android 4.1, method android.graphics.PorterDuffColorFilter android.support.graphics.drawable.VectorDrawableCompat.updateTintFilter(android.graphics.PorterDuffColorFilter, android.content.res.ColorStateList, android.graphics.PorterDuff$Mode) would have incorrectly overridden the package-private method in android.graphics.drawable.Drawable
W/linker: libmapbox-gl.so: unused DT entry: type 0x6ffffffe arg 0x3064
    libmapbox-gl.so: unused DT entry: type 0x6fffffff arg 0x4
I/art: Thread[1,tid=25279,WaitingForJniOnLoad,Thread*=0xb76c53c8,peer=0x780c3eb0,"main"] recursive attempt to load library "/data/app/com.example.mahnoor.mapbox-1/lib/arm/libmapbox-gl.so"
I/art: Thread[1,tid=25279,WaitingForJniOnLoad,Thread*=0xb76c53c8,peer=0x780c3eb0,"main"] recursive attempt to load library "/data/app/com.example.mahnoor.mapbox-1/lib/arm/libmapbox-gl.so"
    Thread[1,tid=25279,WaitingForJniOnLoad,Thread*=0xb76c53c8,peer=0x780c3eb0,"main"] recursive attempt to load library "/data/app/com.example.mahnoor.mapbox-1/lib/arm/libmapbox-gl.so"
D/PhoneWindow: *FMB* installDecor mIsFloating : false
    *FMB* installDecor flags : -2139029248
D/TextView: setTypeface with style : 0
    setTypeface with style : 0
D/TextView: setTypeface with style : 0
D/Activity: performCreate Call Injection manager
I/InjectionManager: dispatchOnViewCreated > Target : com.example.mahnoor.mapbox.MainActivity isFragment :false
D/OpenGLRenderer: Use EGL_SWAP_BEHAVIOR_PRESERVED: true
V/ActivityThread: updateVisibility : ActivityRecord{2020e682 token=android.os.BinderProxy@1618df70 {com.example.mahnoor.mapbox/com.example.mahnoor.mapbox.MainActivity}} show : true
D/PhoneWindow: *FMB* isFloatingMenuEnabled mFloatingMenuBtn : null
    *FMB* isFloatingMenuEnabled return false
I/Adreno-EGL: <qeglDrvAPI_eglInitialize:379>: EGL 1.4 QUALCOMM build:  (I856e09677e)
    OpenGL ES Shader Compiler Version: E031.25.03.04
    Build Date: 10/06/15 Tue
    Local Branch: LA.BR.1.1.3_RB1.05.01.01.032.053_ASTC
    Remote Branch: 
    Local Patches: 
    Reconstruct Branch: 
I/OpenGLRenderer: Initialized EGL, version 1.4
D/OpenGLRenderer: Get maximum texture size. GL_MAX_TEXTURE_SIZE is 4096
    Enabling debug mode 0
I/InjectionManager: dispatchCreateOptionsMenu :com.example.mahnoor.mapbox.MainActivity
    dispatchPrepareOptionsMenu :com.example.mahnoor.mapbox.MainActivity
I/Timeline: Timeline: Activity_idle id: android.os.BinderProxy@1618df70 time:11272258
I/Timeline: Timeline: Activity_idle id: android.os.BinderProxy@1618df70 time:11489697
I/mbgl: {GLThread 2580}[General]: GPU Identifier: Adreno (TM) 306
W/mbgl: {GLThread 2580}[OpenGL]: Not using Vertex Array Objects
W/art: Attempt to remove local handle scope entry from IRT, ignoring
    Attempt to remove local handle scope entry from IRT, ignoring
    Attempt to remove local handle scope entry from IRT, ignoring
    Attempt to remove local handle scope entry from IRT, ignoring
    Attempt to remove local handle scope entry from IRT, ignoring
W/art: Attempt to remove local handle scope entry from IRT, ignoring
    Attempt to remove local handle scope entry from IRT, ignoring
    Attempt to remove local handle scope entry from IRT, ignoring
    Attempt to remove local handle scope entry from IRT, ignoring
    Attempt to remove local handle scope entry from IRT, ignoring
    Attempt to remove local handle scope entry from IRT, ignoring
    Attempt to remove local handle scope entry from IRT, ignoring
    Attempt to remove local handle scope entry from IRT, ignoring
    Attempt to remove local handle scope entry from IRT, ignoring
W/mbgl: {GLThread 2580}[Render]: can't find source for layer 'mapbox-location-shadow'
W/art: Attempt to remove local handle scope entry from IRT, ignoring
    Attempt to remove local handle scope entry from IRT, ignoring
    Attempt to remove local handle scope entry from IRT, ignoring
    Attempt to remove local handle scope entry from IRT, ignoring
    Attempt to remove local handle scope entry from IRT, ignoring
    Attempt to remove local handle scope entry from IRT, ignoring
    Attempt to remove local handle scope entry from IRT, ignoring
    Attempt to remove local handle scope entry from IRT, ignoring
    Attempt to remove local handle scope entry from IRT, ignoring
    Attempt to remove local handle scope entry from IRT, ignoring
    Attempt to remove local handle scope entry from IRT, ignoring
    Attempt to remove local handle scope entry from IRT, ignoring
    Attempt to remove local handle scope entry from IRT, ignoring
W/art: Attempt to remove local handle scope entry from IRT, ignoring
    Attempt to remove local handle scope entry from IRT, ignoring
W/mbgl: {GLThread 2580}[Render]: can't find source for layer 'mapbox-location-shadow'
    {GLThread 2580}[Render]: can't find source for layer 'mapbox-location-stroke-layer'
    {GLThread 2580}[Render]: can't find source for layer 'mapbox-location-layer'
    {GLThread 2580}[Render]: can't find source for layer 'mapbox-location-bearing-layer'
W/art: Attempt to remove local handle scope entry from IRT, ignoring
    Attempt to remove local handle scope entry from IRT, ignoring
    Attempt to remove local handle scope entry from IRT, ignoring
    Attempt to remove local handle scope entry from IRT, ignoring
    Attempt to remove local handle scope entry from IRT, ignoring
W/mbgl: {GLThread 2580}[Render]: can't find source for layer 'mapbox-location-shadow'
    {GLThread 2580}[Render]: can't find source for layer 'mapbox-location-accuracy-layer'
    {GLThread 2580}[Render]: can't find source for layer 'mapbox-location-stroke-layer'

Plz guide me to solve these errors, I searched out alot but nothing sort out this problem.

**Comment by langsmith** [comment]
hey @stoefln , thanks for using Mapbox. 

Please reach out to the Mapbox Support team via https://support.mapbox.com/hc/en-us/requests/new?ticket_form_id=360000291231, so that you can be helped. Please provide Mapbox-related code so that the team can see how you're implementing Mapbox, the version of the Maps SDK that you're using, etc. This information will be helpful for troubleshooting your problems.

**Comment by Dorian1983** [comment]
Cute 👍

**Comment by hrezapour** [comment]
There seems to be a problem with the Google service and it still exists
