### ISSUE TITLE
OnClusterClickListener doesn't always work with satellite map

### ISSUE THREAD

**Issue by Li-Eric** [mapbox/mapbox-plugins-android#503]
Hello,

I created an OnClusterClickListener for a cluster of size 6. It works fine when the map is on "mapbox_style_satellite_streets" mode. However, when I change the map type to "mapbox_style_satellite", taps on the cluster don't work unless I'm at certain zoom levels (all the way out, and some random levels of zoom in).

**Comment by cammace** [comment]
Hey @Li-Eric, we are looking into actually deprecating and removing the cluster plugin. See https://github.com/mapbox/mapbox-plugins-android/issues/522 for further explanation. I'd recommend following the same method explained in #518 and for the "onClickListener", using querying map features (explain extensively in [this doc](https://www.mapbox.com/android-docs/map-sdk/overview/query/)). Please drop a comment on #522 if you find any reason for keeping the cluster plugin around. 

cc: @zugaldia
