### ISSUE TITLE
Use kotlin extension functions to expose APIs on mapboxMap

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-plugins-android#508]
[Kotlin extension functions](https://kotlinlang.org/docs/reference/extensions.html) allow to expose APIs on existing classes. The idea is to expose APIs of plugins directly on MapboxMap to create a real plugin system. This would allow for the following developer experience:

- add maps gradle dep
- add plugin 1 gradle dep
- add plugin 2 gradle dep
- integrate maps with all public api found on MapboxMap

cc @cammace @zugaldia

**Comment by cammace** [comment]
Watching the talk at Google IO about ktx, there might be another option which would remove the need to publish a second artifact for each plugin to support this functionality. See proposal [`KEEP-110`](https://github.com/kotlin/KEEP/issues/110) which adds annotations which you can easily slip into your existing library to make the APIs more friendly. Not sure if we want to hold out for this proposal to add ktx support but it is an option.

**Comment by tobrun** [comment]
Some movement on Maps KTX is moving in https://github.com/mapbox/mapbox-plugins-android/pull/712 and https://github.com/mapbox/mapbox-plugins-android/pull/715
