### ISSUE TITLE
Places AutoComplete Not Working

### ISSUE THREAD

**Issue by ManimuthuCR7** [mapbox/mapbox-plugins-android#513]
**I'm using following code to get places based on Country but always return no data. Kindly advice me.**          

_Intent intent = new PlaceAutocomplete.IntentBuilder()
                        .accessToken(Mapbox.getAccessToken())
                        .placeOptions(PlaceOptions.builder()
                               .country("IN")
                               .limit(10)
                                .build(PlaceOptions.MODE_CARDS))
                        .build(MapsActivity.this);
                startActivityForResult(intent, REQUEST_CODE_AUTOCOMPLETE);_

**Comment by cammace** [comment]
From the request, everything looks correct. Can you confirm that the `country` param is the issue? It might be that we only have `places` data for India and not addresses (see https://www.mapbox.com/geocoding/#coverage). Also try writing the country code in lower case. There's also the `geocodingType` which can be used to specify what kind of geocoding data is returned https://github.com/mapbox/mapbox-plugins-android/blob/master/plugin-places/src/main/java/com/mapbox/mapboxsdk/plugins/places/autocomplete/model/PlaceOptions.java#L108.

**Comment by cammace** [comment]
Going ahead and closing this ticket, if you are still having issues, feel free to comment back and I can look further into it.
