### ISSUE TITLE
Can't disable stale state

### ISSUE THREAD

**Issue by fdermishin-radargeo** [mapbox/mapbox-plugins-android#514]
I want to disable displaying of gray circle when location is not changing. As I understood it is called "stale state". I tried calling `enableStaleState(true)` and `enableStaleState(true)`, but the gray circle was appearing after some time in any case. I also tried to call `staleStateTimeout(Long.MAX_VALUE)`, but this didn't help either.

**Comment by fdermishin-radargeo** [comment]
By the way I was referring to Location Layer Plugin

**Comment by cammace** [comment]
I think you are looking to set `LocationLayerOptions.enableStaleState(false)` which should do the trick. It also sounds like once the options objects built you aren't passing it into the Location Layer Plugin through either its constructor or method `applyStyle`.

cc: @zugaldia

**Comment by fdermishin-radargeo** [comment]
Oh, sorry, I made a typo. I meant trying to call either `enableStaleState(true)` or `enableStaleState(false)`.

I'm passing options through constructor, and all options except `enableStaleState` are applied properly. The gray circle appears no matter what I trye.

            val locationLayerOptions = LocationLayerOptions.builder(this)
                    .foregroundDrawable(R.drawable.location)
                    .backgroundTintColor(Color.TRANSPARENT)  // hide the default icon
                    .elevation(0f)  // hide the shadow
                    .enableStaleState(false)  // do not show gray circle
                    .build()
            locationPlugin = LocationLayerPlugin(mapView, mapboxMap, locationEngine, locationLayerOptions).apply {
                setLocationLayerEnabled(true)
            }

**Comment by cammace** [comment]
Awesome find, thanks for the code snippet. I've fixed the issue in #525.
