### ISSUE TITLE
Change method and variable access modifiers to prevent synthetic accessors from being created.

### ISSUE THREAD

**Issue by cammace** [mapbox/mapbox-plugins-android#521]
This only adds to the method count and using the default accessor still prevents method access outside the SDK.

cc: @tobrun @zugaldia

**Comment by zugaldia** [comment]
I'm gonna close this ticket as per https://github.com/mapbox/mapbox-plugins-android/issues/684#issuecomment-433947880 the functionality provided by the Location Layer Plugin is now part of the core Maps SDK (there's no need to add additional plugins) and the plugin is now deprecated. If this ticket is still relevant for the new `LocationComponent`, please cut a new ticket on https://github.com/mapbox/mapbox-gl-native/issues/new?template=android.md. Thanks!
