### ISSUE TITLE
Deprecate and remove the Clustering Plugin

### ISSUE THREAD

**Issue by cammace** [mapbox/mapbox-plugins-android#522]
Spinning this ticket off of what I mentioned in https://github.com/mapbox/mapbox-plugins-android/issues/518. The Cluster Plugin offers no advantage of GeoJSON runtime clustering and IMO only promotes usage of GLMarkers which don't nearly have the same extensive API set as symbol layers (as we've discussed in great lengths in the past).

cc: @tobrun @zugaldia

**Comment by cammace** [comment]
After some discussion internally with @tobrun, we have decided the best path forward will be deprecating and removing this plugin. There are several different cases which you might be using clustering for but all the use cases for this plugin can be done using runtime styling as mentioned above. If you have any questions migrating over to runtime styling, please feel free to reach out on this ticket or through our support page.

**Comment by zugaldia** [comment]
The Demo app contains a few examples of how to implement clustering using runtime styling. Some good reference activities include:

- [`GeoJsonClusteringActivity`](https://github.com/mapbox/mapbox-android-demo/blob/master/MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/examples/styles/GeoJsonClusteringActivity.java)
- [`CreateHotspotsActivity`](https://github.com/mapbox/mapbox-android-demo/blob/master/MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/examples/dds/CreateHotspotsActivity.java)
- [`SymbolLayerMapillaryActivity`](https://github.com/mapbox/mapbox-android-demo/blob/master/MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/labs/SymbolLayerMapillaryActivity.java)

The whole is app open source and available for download [in the Play Store](https://play.google.com/store/apps/details?id=com.mapbox.mapboxandroiddemo).
