### ISSUE TITLE
Location Layer Default Icon very big size and not detecting current location

### ISSUE THREAD

**Issue by olsisaqe** [mapbox/mapbox-plugins-android#540]
Running the latest demo with this configuration: 

```
// Mapbox
            mapboxMapSdk             : '6.1.1',
            mapboxTurf               : '3.1.0',
            mapboxGeoJson            : '3.1.0',
            mapboxPluginBuilding     : '0.3.0',
            mapboxPluginLocationLayer: '0.5.2',
            mapboxPluginMarkerCluster: '0.3.0',
            mapboxPluginPlaces       : '0.4.0',
            mapboxPluginLocalization : '0.3.0',
            mapboxPluginTraffic      : '0.6.0',
```

**Steps to trigger behavior**
1. Open Demo App
2. Go to Show a user's location

**Expected behavior**
Zoom to current user location as it is stated in: LocationPluginActivity

```
  @Override
  public void onLocationChanged(Location location) {
    if (location != null) {
      setCameraPosition(location);
      locationEngine.removeLocationEngineListener(this);
    }
  }
```

**Actual behavior**
You will notice the location is not shown correctly since the icon is displayed at 0,0 and also you can notice that the my location icon is way to big (bigger than `14dp` specified [here](https://github.com/mapbox/mapbox-plugins-android/blob/752c368aec643d408a538283545bf539849fc04f/plugin-locationlayer/src/main/res/drawable/mapbox_user_icon.xml#L3) ) and pixelated even-though it is a vector.
![image](https://user-images.githubusercontent.com/5824180/40538182-4068baf0-6011-11e8-97eb-653c49f6378d.png)

**Comment by LukasPaczos** [comment]
Thanks for reaching out @olsisaqe.

The puck showing at null-island is fixed in `v0.5.3`.

We are aware of scaling issues of the puck, especially on lower resolution devices, and it's being try by https://github.com/mapbox/mapbox-plugins-android/issues/530. Just a side-note, that scaling is done on a bitmap, hence the distortion.

Closing as resolved/duplicate.
