### ISSUE TITLE
Proguard Parser Exception <mapbox-android-plugin-locationlayer>

### ISSUE THREAD

**Issue by Chrylo** [mapbox/mapbox-plugins-android#541]
When using the following setup and integrating the dependency **com.mapbox.mapboxsdk:mapbox-android-plugin-locationlayer:0.5.3**, I always get the following error:

`ProGuard configuration parser error: \.gradle\caches\transforms-1\files-1.1\mapbox-android-plugin-locationlayer-0.5.3.aar\bff82016c498500d5e92322d3f3579a3\proguard.txt line 11:21 no viable alternative at input ','`

When looking into the [proguard ](https://github.com/mapbox/mapbox-plugins-android/blob/master/plugin-locationlayer/proguard-consumer.pro)file, 11:21 stands out: 

`-keepclassmembernames,allowobfuscation interface * `

```
buildTypes {
        release {
            minifyEnabled true
            shrinkResources true
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
        debug {
            minifyEnabled true
            useProguard false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
            applicationIdSuffix '.debug'
        }
    }
```

**Comment by cammace** [comment]
Could you provide your projects ProGuard configuration, perhaps there's a merging conflict? The line it's referring to is an exact copy of the Retrofit team's [README file](https://github.com/square/retrofit) and our continuous integration runs a check to ensure no basic issues occur such as the one you describe above. 

https://github.com/mapbox/mapbox-plugins-android/blob/9c208bdbd6a7c0208119ee7fc73189dffb0cb705/circle.yml#L43-L45

**Comment by Chrylo** [comment]
Hey again, with proguard enabled (debug mode) I can succesfully build the app. It seems that `minifyEnabled = true ` without proguard being enabled does not support `allowobfuscation` or `includedescriptorclasses `.

See the following [realm issue](https://github.com/realm/realm-java/issues/3714). So the Realm team had the same issue. [Their solution](https://github.com/realm/realm-java/pull/3776/commits/964afd85d46658327f35c232b310c4d07683c94e) was to remove the not supported keywords for build in shrinking. Could you consider, doing the same? :)

To answer your question anyway. You can reproduce it with an empty (defualt) proguard file + my debug configuration. See [Google Documentation](https://developer.android.com/studio/build/shrink-code).

Thank you!

**Comment by cammace** [comment]
Awesome @Chrylo, thanks for looking into the issue and finding the same problem Realm was having. I opened #549 to remove the option.
