### ISSUE TITLE
Expose bearing accuracy

### ISSUE THREAD

**Issue by LukasPaczos** [mapbox/mapbox-plugins-android#553]
Following up on https://github.com/mapbox/mapbox-gl-native/issues/12137, we should expose bearing's accuracy data.

**Comment by danesfeder** [comment]
Does this refer to exposing the data from [Location#getBearingAccuracyDegrees()](https://developer.android.com/reference/android/location/Location.html#getBearingAccuracyDegrees())?  

Or does this refer to updating the render mode to include an option to show the bearing as depicted in the gmaps screenshot in mapbox/mapbox-gl-native#12137?

**Comment by NataliaSamoilovich** [comment]
It would be really cool if both options are included in the mapbox sdk :)

**Comment by LukasPaczos** [comment]
And what I understood from the initial issue is that you were looking for the compass-bearing accuracy, is that correct @NataliaSamoilovich?

**Comment by NataliaSamoilovich** [comment]
Yes. You are right. I was looking for compass bearing to implement behavior like in google maps.
