### ISSUE TITLE
Update ReadMe

### ISSUE THREAD

**Issue by cammace** [mapbox/mapbox-plugins-android#56]
With the merge of Location layer, we now offer an additional plugin. We also are close to merging to building plugin and the traffic plugin has been updated to 0.2.0. These changes need to be reflected in the readme file in this repo.

cc: @langsmith @zugaldia

**Comment by zugaldia** [comment]
I've created a new `v0.2` milestone to track the launch of these two new plugins: https://github.com/mapbox/mapbox-plugins-android/milestone/2. Please feel free to add any other relevant tickets to that milestone.

**Comment by tobrun** [comment]
If possible I would like to see a readme for each plugin in the folder of the plugin itself?
The main readme just lists these readme's + some general information.
