### ISSUE TITLE
Option to disable animation

### ISSUE THREAD

**Issue by LukasPaczos** [mapbox/mapbox-plugins-android#567]
We are hearing voices that smooth tracking animation puts a real stress on the battery consumption, CPU usage and introduces a delay. In order to improve the experience on lower-end devices, we could expose an option to disable the smooth animation.

/cc @danesfeder

**Comment by zugaldia** [comment]
Issue moved to [mapbox/mapbox-gl-native #13225](https://github.com/mapbox/mapbox-gl-native/issues/13225) via [**ZenHub**](https://www.zenhub.com/)
