### ISSUE TITLE
LocationLayerMode can't be imported

### ISSUE THREAD

**Issue by ferily7** [mapbox/mapbox-plugins-android#576]
I'm trying to implement the Location plugin to my application from an example that's in the [Mapbox  Android demo app](https://github.com/mapbox/mapbox-android-demo/blob/a411fa95cd71c1b90a30895060b319310444aebb/MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/examples/plugins/LocationPluginActivity.java). However, when I follow the code and try to do `LocationLayerMode.TRACKING` I am getting an error because of `LocationLayerMode` and when I try to import the library: `import com.mapbox.mapboxsdk.plugins.locationlayer.LocationLayerMode`, I still get an error saying that it "Cannot resolve symbol LocationLayerMode"

Did something change with LocationLayerMode because I cannot use this package at all in my application and it gives me an error.

**Comment by langsmith** [comment]
Hey @ferily7 , thanks for using Mapbox. You might be referencing an outdated version of that example. Your hyperlink above points to a branch that isn't `master`. Here's the `master` version: https://github.com/mapbox/mapbox-android-demo/blob/master/MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/examples/plugins/LocationPluginActivity.java

Trying having your project follow the `master` branch version and let us know if that solves things for you...

**Comment by LukasPaczos** [comment]
Here's the PR targeting the docs issue https://github.com/mapbox/mapbox-plugins-android/pull/571.

**Comment by ferily7** [comment]
It worked! Thank you for the help! I didn't realize that I was using an outdated version.
