### ISSUE TITLE
Expose API for adding text below location layer icon

### ISSUE THREAD

**Issue by cammace** [mapbox/mapbox-plugins-android#59]
Originally, the location layer supported adding text below the icon but while simplifying, I removed the code. We should add this back as an option.

**Comment by zugaldia** [comment]
I'm gonna close this ticket as per https://github.com/mapbox/mapbox-plugins-android/issues/684#issuecomment-433947880 the functionality provided by the Location Layer Plugin is now part of the core Maps SDK (there's no need to add additional plugins) and the plugin is now deprecated. If this ticket is still relevant for the new `LocationComponent`, please cut a new ticket on https://github.com/mapbox/mapbox-gl-native/issues/new?template=android.md. Thanks!
