### ISSUE TITLE
Release LocationLayerPlugin v0.7.0

### ISSUE THREAD

**Issue by LukasPaczos** [mapbox/mapbox-plugins-android#597]
### Features
Version `0.7.0` of the LocationLayerPlugin adds additional methods that allow manipulating the camera while any of the camera modes, besides `CameraMode#NONE`, is engaged.
- Use `LocationLayerPlugin#zoomWhileTracking` to zoom in/out the camera.
- Use `LocationLayerPlugin#tiltWhileTracking` to tilt the camera.

### Changelog
- Additional methods to tilt and zoom in/out the camera while camera tracking is engaged [#583](https://github.com/mapbox/mapbox-plugins-android/pull/583)
- Fixed wrong focal point persisting when camera modes are changed quickly [#583](https://github.com/mapbox/mapbox-plugins-android/pull/583)
- Update ProGuard to support built-in shrinker of Gradle Plugin [#582](https://github.com/mapbox/mapbox-plugins-android/pull/582)
- Break camera tracking on fling [#587](https://github.com/mapbox/mapbox-plugins-android/pull/587)
- Maps SDK bump to 6.3.0 [#585](https://github.com/mapbox/mapbox-plugins-android/pull/585)
- Fixed memory leak when using the mapbox-plugins [#570](https://github.com/mapbox/mapbox-plugins-android/issues/570)
- Always make plugin visible in location start when enabled [#592](https://github.com/mapbox/mapbox-plugins-android/pull/592)
- Check if the layer is hidden when setting render mode [#594](https://github.com/mapbox/mapbox-plugins-android/pull/594)
- Adjust camera based on the camera mode when plugin enabled [#596](https://github.com/mapbox/mapbox-plugins-android/pull/596)

### Release checklist

- [x] Cut the release branch
- [x] Run through testapp/demo app and test all activities
- [x] Update `README.md`
- [x] Update `CHANGELOG.md`
- [x] Change version name to `0.7.0` in `gradle.properties`
- [x] Publish `0.7.0` artifact to Maven Central
- [x] Change version name back to `0.8.0-SNAPSHOT`
- [x] Merge the release branch back to `master`
- [x] Tag `v0.7.0` in GitHub

### Post-release 
- [x] Update `constants.js` file in `android-docs` repo
- [x] Generate updated javadocs and add to `android-docs` repo
- [x] Update the version # in the Mapbox demo app @langsmith
- [x] Update the version # in the Studio Preview app @langsmith

/cc: @mapbox/android

**Comment by langsmith** [comment]
Done 🎊
