### ISSUE TITLE
Release LocationLayerPlugin v0.7.1

### ISSUE THREAD

**Issue by danesfeder** [mapbox/mapbox-plugins-android#606]
### Changelog
- Request location updates for AndroidLocationEngine [#602](https://github.com/mapbox/mapbox-plugins-android/pull/602)

### Release checklist

- [x] Cut the release branch
- [x] Run through testapp/demo app and test all activities
- [x] Update `README.md`
- [x] Update `CHANGELOG.md`
- [x] Change version name to `0.7.1` in `gradle.properties`
- [x] Publish `0.7.1` artifact to Maven Central
- [x] Change version name back to `0.8.0-SNAPSHOT`
- [x] Merge the release branch back to `master`
- [x] Tag `v0.7.1` in GitHub

### Post-release  @langsmith
- [x] Update plugin's version #s in https://github.com/mapbox/mapbox-plugins-android/tree/master/plugin-locationlayer 
- [x] Update `constants.js` file in `android-docs` repo 
- [x] Generate updated javadocs and add to `android-docs` repo 
- [x] Update the version # in the Mapbox demo app 
- [x] Update the version # in the Studio Preview app 

/cc: @mapbox/android

**Comment by langsmith** [comment]
Done on my end @danesfeder

**Comment by danesfeder** [comment]
Thanks @langsmith
