### ISSUE TITLE
Option to disable LatLng animation

### ISSUE THREAD

**Issue by mcfoi** [mapbox/mapbox-plugins-android#611]
By default, any new location triggers a LayerLatLngAnimator that moves the GPS marker towards the new known location.
This animation prevents the user to instantly perceive their exhact position in map. Ever.
This is most notable at higher speeds. In this scenario there is a constant artificial gap between the real user location and the marker position and while half is due to the 1000millisec frequency of (consumer) GPS antennas, the other half is due to animation.
It happens that 0.5sec after the last reading, the user is already away from the last known position while the animated GPS marker is still animating towards it. This can account to several tents of meters.
While animation is a very nice and desirable feature, fast paced surveying activities could prefer GPS marker to make discrete jumps instead of smootly animating between locations.

Belo you can see the GPS marker attempting to "catch"the most recent known location.. ..bull falling behind.
![latlng_animator_gap](https://user-images.githubusercontent.com/1722186/43577668-c40ed8fa-964c-11e8-9f1c-61a0671f43f0.gif)

**Comment by LukasPaczos** [comment]
Hey @mcfoi, thanks for reaching out! This a totally reasonable use case and we are tracking this request in https://github.com/mapbox/mapbox-plugins-android/issues/567.

**Comment by mcfoi** [comment]
Dear Łukasz,
I am happy to hear such news from you.
Just please confirm #567
<https://github.com/mapbox/mapbox-plugins-android/issues/567> will handle
also disabling of GPS icon animation. As for what I can read in #567, you
are targeting Camera animation but I am not even using it. My use case is
just using plain GPS updates and what I would change is simply the icon
animation.
No Camera involved at all!

Thanks.
Marco

Il lun 6 ago 2018, 12:44 Łukasz Paczos <notifications@github.com> ha
scritto:

**Comment by LukasPaczos** [comment]
Yes, we'd like to target both camera and layer animation with that ticket @mcfoi!
