### ISSUE TITLE
Compass not working on devices without gyroscope

### ISSUE THREAD

**Issue by niihelium** [mapbox/mapbox-plugins-android#613]
I've been testing my app on my Moto 3G (2015) API 25 and noticed, that compass tracking wasn't working, it just stands still. Similar problem I've encountered with Sky Map application, I should go to the settings of the app and disable gyroscope. 

Then I've tested plugin-locationlayer on 2 different emulators Nexus 5X API 27 and on Nexus S API 22. It works on Nexus 5X, but not working on Nexus S. After listing all available sensors on all of this three devices appears that on all devices CompassManager falls back to Sensor.TYPE_ORIENTATION, but it works only on device with gyroscope. 

So I propose in case of fallback add check does device have gyroscope, and if it has use Sensor.TYPE_ORIENTATION, otherwise fallback further to combination of accelerometer and magnetic field sensor. 

I've already tested this and can make pull request if it's appropriate solution to futher investiagation.

**Comment by niihelium** [comment]
@LukasPaczos @langsmith it was written that I may feel free ping someone from dev team, can you comment on this, please.

**Comment by danesfeder** [comment]
Hey @niihelium 👋thanks a lot for debugging this and digging into a solution.  Please feel free to open pull request and the team would love to have a look.  Your solution sounds great as described.  Cheers!
