### ISSUE TITLE
Optimize for OfflineGeometryRegionDefinition

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-plugins-android#621]
The upstream Mapbox Maps for Android SDK will introduce OfflineGeometryRegionDefinition from https://github.com/mapbox/mapbox-gl-native/pull/11447 in v6.5.0. The codebase for the offline plugin needs to be hardened for occurences of that instance + provide integration for it as well. 

Note that in 7.0.0 the interface for OfflineRegionDefinition will change, see https://github.com/mapbox/mapbox-gl-native/issues/12685.

**Comment by LukasPaczos** [comment]
Blocked by https://github.com/mapbox/mapbox-gl-native/issues/13687.
