### ISSUE TITLE
Expose clustering configuration

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-plugins-android#648]
Due to the SymbolManager being backed by a SymbolLayer with GeoJson source we should be able to provide a clustering configuration on top of it.

**Comment by tobrun** [comment]
Been thinking more about this and instead of a configuration we need to support a new concept that is build on top of the annotation plugin concept. A cluster contains multiple layers and we you create an easy to use wrapper for it.

**Comment by SalimHFX** [comment]
Any updates on this ??

**Comment by tobrun** [comment]
@SalimHFX no concrete eta on creating this facility API, you can however use code from https://github.com/mapbox/mapbox-gl-native/blob/master/platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/style/GeoJsonClusteringActivity.java in combination with the API found in the annotation plugin. (the symbolLayer = symbolManager/symbols).

**Comment by kleeb** [comment]
any chance of merging ? 
This request is depending on it https://github.com/tobrun/flutter-mapbox-gl/issues/169

**Comment by AAverin** [comment]
@tobrun Any chance to push this forward? It would be lovely to finally get points clustering in Flutter implementation

**Comment by Martibis** [comment]
Would love to see this too
