### ISSUE TITLE
Location Layer's render mode "COMPASS" malfuncionating

### ISSUE THREAD

**Issue by chirmac** [mapbox/mapbox-plugins-android#659]
I have a LocationLayer function like this:
```kotlin
private fun initLocationLayer() {
        locationLayerPlugin = LocationLayerPlugin(falconMap, mapBoxMap)
        locationLayerPlugin.isLocationLayerEnabled = true
        locationLayerPlugin.cameraMode = CameraMode.TRACKING_GPS
        locationLayerPlugin.renderMode = RenderMode.COMPASS
        lifecycle.addObserver(locationLayerPlugin)
    }
```
I currently use Google Play services location API instead of location engine, as it is the recommended from Google, faster and more reliable:
```kotlin
        fusedLocationClient = LocationServices.getFusedLocationProviderClient(this)
        val builder = LocationSettingsRequest.Builder()
                .addLocationRequest(locationRequest)

        val client: SettingsClient = LocationServices.getSettingsClient(this)
        val task: Task<LocationSettingsResponse> = client.checkLocationSettings(builder.build())
```

And I use this function to update the camera:
```kotlin
fun setCameraPosition(cameraPosition: Location) {
        mapBoxMap.animateCamera(CameraUpdateFactory.bearingTo(cameraPosition.bearing.toDouble()))
        mapBoxMap.animateCamera(CameraUpdateFactory.newLatLngZoom(LatLng(cameraPosition.latitude, cameraPosition.longitude), 16.0))
    }
```
The camera positions always updated correctly, there's no problem with coordinates updating. But if I use the compass render mode, the arrow icon on the layer doesn't move at all. While in GPS or Normal render mode, the GPS mode updates it's arrow accordingly and Normal mode changes the map's orientation well too, just the Compass render mode is miss behaving.

![image](https://user-images.githubusercontent.com/19695011/45391191-f70c0d80-b619-11e8-828c-1258c3587c45.png)

As you can see in the picture, it doesn't update the arrow, tho the bearing is 81 degrees. Is this intended behavior with the Google location API? Please help me.

**Comment by LukasPaczos** [comment]
Hey @chirmac, thanks for using our products!

From what I can see, the `RenderMode.COMPASS` works as designed here - the arrow displayed in this mode faces the bearing provided by the `CompassManager`, not the location. Only the `RenderMode.GPS` takes location's bearing into consideration.

Let us know if you have any other questions. Closing as answered.

**Comment by chirmac** [comment]
Oh, that explains a lot! Since my emulator doesn't have a compass, it doesn't work. Thanks!
