### ISSUE TITLE
Release LocationLayerPlugin 0.8.2

### ISSUE THREAD

**Issue by LukasPaczos** [mapbox/mapbox-plugins-android#662]
### Changelog
 - Maps SDK bump to 6.5.0 [#634](https://github.com/mapbox/mapbox-plugins-android/pull/634)

### Release checklist
- [x] Cut the release branch
- [x] Run through testapp/demo app and test all activities
- [x] Update `README.md`
- [x] Update `CHANGELOG.md`
- [x] Change version name to `0.8.2` in `gradle.properties`
- [x] Publish `0.8.2` artifact to Maven Central
- [x] Change version name back to `0.9.0-SNAPSHOT`
- [x] Merge the release branch back to `master`
- [x] Tag `v0.8.2-location-layer` in GitHub

### Post-release  @langsmith
- [x] Update `constants.js` file in `android-docs` repo 
- [x] Generate updated javadocs and add to `android-docs` repo 
- [x] Update the version # in the Mapbox demo app 
- [x] Update the version # in the Studio Preview app 
- [x] Update the version # in voyage
- [x] Update the version # in china plugin demo

/cc: @mapbox/android

**Comment by langsmith** [comment]
🏁🍾
