### ISSUE TITLE
Release PlacesPlugin 0.6.0

### ISSUE THREAD

**Issue by LukasPaczos** [mapbox/mapbox-plugins-android#663]
### Changelog
 - Problem with option 'country' [#554](https://github.com/mapbox/mapbox-plugins-android/pull/554)
 - Update ProGuard to support built-in shrinker of Gradle Plugin [#582](https://github.com/mapbox/mapbox-plugins-android/pull/582)
 - Fix for disappearing places picker marker [#584](https://github.com/mapbox/mapbox-plugins-android/pull/584)
 - Maps SDK bump to 6.5.0 [#634](https://github.com/mapbox/mapbox-plugins-android/pull/634)

### Release checklist
- [x] Cut the release branch
- [x] Run through testapp/demo app and test all activities
- [x] Update `README.md`
- [x] Update `CHANGELOG.md`
- [x] Change version name to `0.6.0` in `gradle.properties`
- [x] Publish artifact to Maven Central
- [x] Change version name back to `0.7.0-SNAPSHOT`
- [x] Merge the release branch back to `master`
- [x] Tag `v0.6.0-places` in GitHub

### Post-release  @langsmith
- [x] Update `constants.js` file in `android-docs` repo 
- [x] Generate updated javadocs and add to `android-docs` repo 
- [x] Update the version # in the Mapbox demo app 
- [x] Update the version # in the Studio Preview app 
- [x] Update the version # in voyage

/cc: @mapbox/android

**Comment by langsmith** [comment]
🏁🍾
