### ISSUE TITLE
Release LocalizationPlugin 0.5.0

### ISSUE THREAD

**Issue by LukasPaczos** [mapbox/mapbox-plugins-android#664]
### Changelog
 - Update ProGuard to support built-in shrinker of Gradle Plugin [#582](https://github.com/mapbox/mapbox-plugins-android/pull/582)
 - Update localization plugin to support expressions [#654](https://github.com/mapbox/mapbox-plugins-android/pull/654)
 - Fix Localization set camera to locale country Javadoc broken link [#640](https://github.com/mapbox/mapbox-plugins-android/pull/640)
 - Adding japanese and korean support to localization plugin [#575](https://github.com/mapbox/mapbox-plugins-android/pull/575)
 - Maps SDK bump to 6.5.0 [#634](https://github.com/mapbox/mapbox-plugins-android/pull/634)

### Release checklist
- [x] Cut the release branch
- [x] Run through testapp/demo app and test all activities
- [x] Update `README.md`
- [x] Update `CHANGELOG.md`
- [x] Change version name to `0.5.0` in `gradle.properties`
- [x] Publish artifact to Maven Central
- [x] Change version name back to `0.6.0-SNAPSHOT`
- [x] Merge the release branch back to `master`
- [x] Tag `v0.5.0-localization` in GitHub

### Post-release  @langsmith
- [x] Update `constants.js` file in `android-docs` repo 
- [x] Generate updated javadocs and add to `android-docs` repo 
- [x] Update the version # in the Mapbox demo app 

/cc: @mapbox/android

**Comment by langsmith** [comment]
🏁🍾
