### ISSUE TITLE
Release MarkerViewPlugin 0.1.0

### ISSUE THREAD

**Issue by LukasPaczos** [mapbox/mapbox-plugins-android#665]
### Changelog
Initial release! 🎉 

### Release checklist
- [x] Cut the release branch
- [x] Run through testapp/demo app and test all activities
- [x] Update `README.md`
- [x] Update `CHANGELOG.md`
- [x] Change version name to `0.1.0` in `gradle.properties`
- [x] Publish artifact to Maven Central
- [x] Change version name back to `0.2.0-SNAPSHOT`
- [x] Merge the release branch back to `master`
- [x] Tag `v0.1.0-markerview` in GitHub

### Post-release  @langsmith
- [x] Update `constants.js` file in `android-docs` repo 
- [x] Generate updated javadocs and add to `android-docs` repo 

/cc: @mapbox/android

**Comment by langsmith** [comment]
🏁 🎉
