### ISSUE TITLE
Another locationlayer mode - "static" navigation icon

### ISSUE THREAD

**Issue by davols** [mapbox/mapbox-plugins-android#67]
Ticket as per the contribution guidelines. I'm not fully sure if the word static is the best word to use for this ticket.

The idea is either a setting on top of current `NAVIGATION` mode or another mode. Where the navigation icon would not move or rotate as it does today. Instead it would be centered and the map/camera would rotate and follow the user. 

Iirc the `TRACKING_FOLLOW` at `MyLocationView` in Mapbox SDK did the following part but not always pointing upwards on the screen. 

Similar to other navigation apps, as it's probably a simpler UI experience for navigation. 

Feel free to close this issue. Looking forward for any input from @mapbox/android 

I'm pretty sure we are interested in this mode, we currently have a small testing branch with a modified version of this master.

**Comment by davols** [comment]
We have a rather crude version over at https://github.com/Hitta/mapbox-plugins-android/tree/feature/navigation_locked  

![gif](https://media.giphy.com/media/EDd7Lb6ejCQow/giphy.gif)

Works pretty well, however when a navigation session (using mapbox navigation for android) it is not the smooth transitions anymore instead it's jumping/hacking it's way though the map.

**Comment by cammace** [comment]
Going off your GIF, it would be more appropriate to make use of the CompassListener which will be available in 0.2.0 (see [implementation here](https://github.com/mapbox/mapbox-plugins-android/pull/84)). I put together an example which shows a similar behavior. For location icon padding (placing the icon in a none center position in the viewport) will require adjustment to the camera which isn't something we want to handle in this SDK. Instead, we plan to offer a `navigationCamera` implementation inside the navigation SDK which will handle this feature.

With the compass listener, you pass in an implementation to the locationLayerPlugin and you should immediately start receiving heading values once every second. 

![ezgif com-video-to-gif 3](https://user-images.githubusercontent.com/5652865/29471599-949249e0-841e-11e7-8b3d-36e8636ccd7c.gif)

**Comment by davols** [comment]
Wasn't able to find a better example, but in the turn I guess what we want is visible, a smooth and quick turn (except, gif makes it hacky). But compass listener might be the easiest way to get the same feature.
Another tl;dr of our idea would be to always animate and rotate the map, instead of rotating the icon (so the icon looks like it's static and always in the middle and pointing upwards/the direction of travel). 

A padding could be done in attrs styles I guess? But feel free to close this issue if it's nothing you're looking for in the plugin.

**Comment by davols** [comment]
I'm not sure we're having a communication issue. But the locationlayerplugin in iOS is following like our branch and has feature we want. Adding another gif. 

For a user the plugin should always point upwards and the map should rotate instead. (Added padding to this gif) 
![giphy 1](https://user-images.githubusercontent.com/1420172/29608488-8effe224-87f4-11e7-9172-509052790a95.gif)

(Replaying a route I took on a bus, disregard toasts and other markers since they are for testing purposes).

**Comment by cammace** [comment]
Thanks for the GIF, because the effect you are trying to accomplish can be done with a combination of the compass listener added in https://github.com/mapbox/mapbox-plugins-android/pull/84 and a regular image view on top of the map showing the user location puck, I don't see the need/benefit of adding an additional state that's implementation would veer so far away from the other 3 modes.

**Comment by marconealberto** [comment]
@davols where can I find a working example of the GIF above? thank you!

**Comment by davols** [comment]
@marconealberto with the rotations? The crude version used for that was https://github.com/Hitta/mapbox-plugins-android/tree/feature/navigation_locked 

However, I'm no longer apart of the organiation and no longer working on using mapbox-plugins-android so I couldn't help you more. Before I stopped working the latest version of that plugin (together with mapbox-navigation-android) had a similar setup as the last gif.

**Comment by marconealberto** [comment]
great stuff, thank you!
