### ISSUE TITLE
MapLocale RUSSIA is missing from MapLocale 

### ISSUE THREAD

**Issue by rusvel** [mapbox/mapbox-plugins-android#675]
If the device language is Russian, LocalizationPlugin.checkMapLocalNonNull() returns NullPointerException 

Locale ru_RU has no matching MapLocale object. You need to create an instance of MapLocale and add it to the MapLocale Cache using the addMapLocale method.

**Comment by tobrun** [comment]
Thanks for the report @rusvel, fixing this in #678
