### ISSUE TITLE
Use data driven styling for building height

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-plugins-android#68]
Been seeing some [examples](https://twitter.com/igor_au/status/891526823099547652) of data driven coloring of the `height` property

<img width="340" alt="screen shot 2017-07-31 at 17 57 41" src="https://user-images.githubusercontent.com/2151639/28786586-ecfb392e-7619-11e7-9bb7-d00fce7d91ce.png">

We could look into adding this as an option on the plugin.

**Comment by cammace** [comment]
I'm not entirely sure how we want to proceed with this idea. In my opinion, the APIs in this plugin should remain simple and this would add a bunch of options which could confuse users. I propose we drop this feature request and guide users to create their own extrusion layer if they want this type of functionality.
