### ISSUE TITLE
Deprecate LocationLayerPlugin

### ISSUE THREAD

**Issue by LukasPaczos** [mapbox/mapbox-plugins-android#684]
Refs https://github.com/mapbox/mapbox-gl-native/pull/12786.

This ticket tracks deprecation of the `LocationLayerPlugin` that will happen when the `LocationComponent` is released in the Maps SDK `v6.6.0`.

**Comment by zugaldia** [comment]
> will happen when the LocationComponent is released in the Maps SDK

May I suggest we call it `LocationManager` to match the naming we use on iOS?

**Comment by zugaldia** [comment]
By looking at [the iOS docs](https://www.mapbox.com/ios-sdk/maps/examples/user-location-annotation/), it seems the actual name for this type of functionality is `MGLUserLocationAnnotationView`. If so, `UserLocationAnnotation` (or simply `LocationAnnotation`) probably is a better name which improves consistency across platforms but I'm open to other options.

**Comment by LukasPaczos** [comment]
Browsing through that doc it looks like in the iOS world the `MGLUserLocationAnnotationView` is just a view. The camera tracking and location management functionality seem to be embedded into the map. What we are proposing is something that exposes all of those things separately from the map, but since there already is a concept of `LocationManager` on iOS which has an equivalent in `LocationEngine` on Android I opted for `LocationComponent` to indicate that all methods used to display and manipulate the location are enclosed in the component.

At this point, I'd propose sticking with the name, but that's still up for debate.

**Comment by zugaldia** [comment]
For future reference and for folks looking for functionality similar to the one provided by the Location Layer Plugin: we've integrated this API into our core Maps SDK and this is now available without requiring any additional plugins. Up to date documentation is available here: https://www.mapbox.com/android-docs/maps/overview/location-component/
