### ISSUE TITLE
GeoJSON/FeatureCollection parsing

### ISSUE THREAD

**Issue by LukasPaczos** [mapbox/mapbox-plugins-android#705]
Refs https://github.com/mapbox/mapbox-plugins-android/issues/683. It'd be great to have an API able to parse raw `GeoJSON` string or `FeatureCollection` to annotations.

**Comment by tobrun** [comment]
Thinking about ways to expose this, probably something as:

```java
AnnotationManager#create(string geoJson);
AnnotationManager#create(FeatureCollection featureCollection);
```

**Comment by LukasPaczos** [comment]
Yes, that'd be exactly how I see it as well. We can iterate through the collection and generate annotations from features that are matching the manager's type.

**Comment by tobrun** [comment]
![tenor](https://user-images.githubusercontent.com/2151639/46140542-b0d9bf80-c251-11e8-83b7-1258770cb030.gif)

Looking forward adding a bunch of geojson on top of a map using geojson.io and using the resulting resource in conjunction with this api for benchmarking purposes!
