### ISSUE TITLE
LocationLayerPlugin Release v0.9.0

### ISSUE THREAD

**Issue by danesfeder** [mapbox/mapbox-plugins-android#707]
### Changelog
 - Add animation duration multiplier configuration [#706](https://github.com/mapbox/mapbox-plugins-android/pull/706)
 - Don't invalidate camera mode if unnecessary for gestures initiated changes [#694](https://github.com/mapbox/mapbox-plugins-android/pull/694)

### Release checklist @danesfeder 
- [x] Cut the release branch
- [x] Run through testapp/demo app and test all activities
- [x] Update `CHANGELOG.md`
- [x] Change version name to `0.9.0` in `gradle.properties`
- [ ] Publish `0.9.0` artifact to Maven Central
- [ ] Change version name back to `0.10.0-SNAPSHOT`
- [ ] Merge the release branch back to `master`
- [ ] Tag `v0.9.0-location-layer` in GitHub

### Post-release  @langsmith
- [ ] Update `README.md`
- [ ] Update `constants.js` file in `android-docs` repo 
- [ ] Generate updated javadocs and add to `android-docs` repo 
- [ ] Update the version # in the Mapbox demo app 
- [ ] Update the version # in the Studio Preview app 
- [ ] Update the version # in china plugin demo

/cc: @mapbox/android

**Comment by LukasPaczos** [comment]
Closing because of the `0.10.0` that has already been released.
