### ISSUE TITLE
TelemetryService can't use AndroidLocationEngineFactory

### ISSUE THREAD

**Issue by letuananh035** [mapbox/mapbox-plugins-android#723]
```
boolean hasDependencyOnClasspath(String className) {
    try {
      Class.forName(className);
      return true;
    } catch (ClassNotFoundException ignored) {
      // Empty
    }
    return false;
  }
```
Always running GoogleLocationEngineFactory with com.google.android.gms.location.LocationServices is import though google play service is not found
#location-layer-plugin

**Comment by LukasPaczos** [comment]
This issue has already been fixed upstream. Please try out the [`LocationComponent`](https://www.mapbox.com/android-docs/maps/overview/location-component/), that is a direct replacement of the already deprecated `LocationLayerPlugin`, and let us know whether you still run into this issue.
