### ISSUE TITLE
OfflineDownloadChangeListener not working

### ISSUE THREAD

**Issue by arnekaiser** [mapbox/mapbox-plugins-android#724]
None of the callback methods are called anymore. The problem appears also in the test app of this repo (see OfflineRegionDetailActivity).

Tested on OnePlus 5 (Android 8.1) and emulator (Android 9).

**Comment by tobrun** [comment]
Fixed with https://github.com/mapbox/mapbox-plugins-android/commit/452f25e830fc904aa7fd8508d3d4daacc1750d5c
