### ISSUE TITLE
Disable bitrise email notifications

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-plugins-android#73]
Every time CI has build successfully, the team is getting an email. 
For other projects we have disabled this integration. 

<img width="1236" alt="screen shot 2017-08-05 at 12 39 20" src="https://user-images.githubusercontent.com/2151639/28994930-3b152ace-79db-11e7-9ec4-b221d44c91ec.png">

**Comment by langsmith** [comment]
[Bitrise settings page for Plugins project](https://www.bitrise.io/app/a3a5f64a6d4a78c3#/settings)

![screen shot 2017-08-18 at 11 21 03 am](https://user-images.githubusercontent.com/4394910/29472092-67224288-8407-11e7-97da-35518a526f60.png)


re-open if plugin emails are still arriving
