### ISSUE TITLE
LocationLayerPlugin Release v0.11.0

### ISSUE THREAD

**Issue by LukasPaczos** [mapbox/mapbox-plugins-android#739]
### Changelog
- Deprecating LocationLayerPlugin [#729](https://github.com/mapbox/mapbox-plugins-android/pull/729)

### Release checklist
- [x] Cut the release branch
- [ ] Run through testapp/demo app and test all activities
- [x] Update `CHANGELOG.md`
- [x] Change version name to `0.11.0` in `gradle.properties`
- [x] Publish `0.11.0` artifact to Maven Central
- [x] Change version name back to `0.12.0-SNAPSHOT`
- [x] Merge the release branch back to `master`
- [x] Tag `v0.11.0-location-layer` in GitHub

### Post-release @langsmith 
- [x] Update `README.md`
- [x] Update `constants.js` file in `android-docs` repo 
- [x] Generate updated javadocs and add to `android-docs` repo 

/cc: @mapbox/android

**Comment by zugaldia** [comment]
For future reference and for folks looking for functionality similar to the one provided by the Location Layer Plugin: we've integrated this API into our core Maps SDK and this is now available without requiring any additional plugins. Up to date documentation is available here: https://www.mapbox.com/android-docs/maps/overview/location-component/

**Comment by langsmith** [comment]
All done on my end @LukasPaczos

**Comment by LukasPaczos** [comment]
:rocket:
