### ISSUE TITLE
icon-image loader

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-plugins-android#742]
The style-spec icon-image is currently exposed as 

```java
  public void setIconImage(String value) {
    jsonObject.addProperty("icon-image", value);
  }
```

We need an easier way to support Android resources, for example by allow setting a drawable, bitmap or resource id. This setup should also take in account to support re-adding the images if a style changes occurs #737.

**Comment by jchekanoff** [comment]
What would you suggest in the interim? Since `IconFactory` is deprecated, we haven't been successful in finding another way to set custom icon images.

**Comment by tobrun** [comment]
You add images to your style and create an id for them with:

 > Style.Builder#withImage or Style#addImage 

You can use that id with:

> Symbol#setIconImage

**Comment by jchekanoff** [comment]
@tobrun thanks for the quick reply!!!

**Comment by tobrun** [comment]
Updating here that it might make more sense for people reading this issue to start using the new image missing api from https://github.com/mapbox/mapbox-gl-native/pull/14320. This will land as part of the upcoming v7.4.0 release.

**Comment by chloekraw** [comment]
> The style-spec icon-image is currently exposed as
```
  public void setIconImage(String value) {
    jsonObject.addProperty("icon-image", value);
  }
```
> We need an easier way to support Android resources, for example by allow setting a drawable, bitmap or resource id. This setup should also take in account to support re-adding the images if a style changes occurs #737.

@tobrun is there a better way that we could have exposed the `icon-image` property on Android?

> Updating here that it might make more sense for people reading this issue to start using the new image missing api from mapbox/mapbox-gl-native#14320. This will land as part of the upcoming v7.4.0 release.

Interesting, so this means on Android with https://github.com/mapbox/mapbox-plugins-android/pull/1000, it will be easier to add an arbitrary image at runtime than to add a custom sprite uploaded to Studio at runtime?

**Comment by tobrun** [comment]
@chloekraw in https://github.com/mapbox/mapbox-plugins-android/pull/1000 I'm proposing an alternative way of loading the icons. Just call `setIconImage(String value)` with the name of the resource and it will be automatically loaded for you (this includes reloading it during style changes).

**Comment by chloekraw** [comment]
@tobrun ahh, I see! the proposed `setIconImage(String value)`, where "String value" is the name or ID of the `icon-image`, works for both adding custom sprites to the map and arbitrary images, right?

**Comment by tobrun** [comment]
> @tobrun ahh, I see! the proposed setIconImage(String value), where "String value" is the name or ID of the icon-image, works for both adding custom sprites to the map and arbitrary images, right?

correct, first core tries to match this `value` to an image in the spritesheet. If not found, the plugin will try loading a app resource with the name (fwiw, if no resource is found with that name, we log out message and do not crash the app).

**Comment by chloekraw** [comment]
Awesome, thanks @tobrun. That sounds like the ideal developer workflow for using images as icons.
