### ISSUE TITLE
Support any sources that follow streets specification

### ISSUE THREAD

**Issue by diegolaballos** [mapbox/mapbox-plugins-android#761]
I've tested with the Mapbox plugins app, the one that shows how to use all the plugins. The localization works fine until I set a custom style : mapView.setStyleUrl("http://mystyle")

### Steps to reproduce

 1. Clone Mapbox plugins app
 2. Add a custom style to the LocalizationActivity
 3. Try to change the language

### Expected behavior
It should change the language and it works before adding a custom style

### Actual behavior
It ignores the new language

### Configuration

**Mapbox Localization plugin: 0.5.0 **

**Comment by tobrun** [comment]
@diegolaballos the localisation plugin uses the name prefix to localise the content as defined in the [Mapbox Streets Definition](https://www.mapbox.com/vector-tiles/mapbox-streets-v7/). Does your custom style symbol layers use these?

**Comment by diegolaballos** [comment]
@tobrun Thanks for the info. 

Well I see that my style is using different labels. Instad of `name_ln` I have `name:ln` Is there a way to use different name fields or does my style need to match the same structure?

**Comment by tobrun** [comment]
Changed title to reflect the feature request

**Comment by diegolaballos** [comment]
@tobrun I know you changed the title of the issue and now my question might not make sense but it's about the same problem I had when I opened this. 

We've changed our style to match with the mapbox localization labels but it doesn't work. Everything is fine with the implementation because it works fine when no custom style is set.

The thing is that we don't know where and what to look at. 

![unnamed](https://user-images.githubusercontent.com/17909959/50280925-25398e80-044e-11e9-9745-6ecd08b39478.png)

Thanks!

**Comment by LukasPaczos** [comment]
Hey @diegolaballos, are your sources based on the Mapbox sources? [Here's the list of compatible ones.](https://github.com/mapbox/mapbox-plugins-android/blob/master/plugin-localization/src/main/java/com/mapbox/mapboxsdk/plugins/localization/LocalizationPlugin.java#L48-L50)

If yes, could you jump into the code and debug `LocalizationPlugin#setMapLanguage` method? Especially check if the conversion is happening and not falling out on any `if` checks.

**Comment by diegolaballos** [comment]
I've just debugged the code and it returns false for `sourceIsFromMapbox(source)` We've been using Mapbox for a long time and everything works fine. We've also tweaked the name labels in order to make it compatible with Mapbox, so I'm wondering what would happen if we remove this if clause.

**Comment by LukasPaczos** [comment]
If the source is properly adapted to the `streets` sources spec, there should be no issues.

I believe this is still a valid request, let us revisit ways of providing translatable names, or alternatively failing silently if the spec is not met instead of force-checking for Mapbox sources.

**Comment by diegolaballos** [comment]
ok thanks! we'll try.

Should we rename the title for this issue because it's not only about supporting a different naming for the labels?

**Comment by diegolaballos** [comment]
Hi @LukasPaczos ,

I tried to remove the if condition `sourceIsFromMapbox(source)` but it didn't work.
Since we're not using the Mapbox sources I've asked our source provider about this and that's what they told us:

> The "streets sources spec" is for the Mapbox Streets source. It's proprietary, we wouldn't even be allowed to use that.
> You are using the Maptoolkit source, which correctly follows the Mapbox vector tile spec. Which should be the only thing that matters.
> 

We don't know what to do at this moment. How are we supposed to make these custom sources compatible with the streets sources spec?
Thanks in advance!

**Comment by LukasPaczos** [comment]
> I tried to remove the if condition sourceIsFromMapbox(source) but it didn't work.

Could you point exactly to what did not work? Removing this check will make the code fall into [`streets-v7` conversion scheme](https://github.com/mapbox/mapbox-plugins-android/blob/master/plugin-localization/src/main/java/com/mapbox/mapboxsdk/plugins/localization/LocalizationPlugin.java#L223-L242) so as long as your source is mirroring the field names of [the `streets-v7` source](https://docs.mapbox.com/vector-tiles/mapbox-streets-v7/) and your style has entries that will match [the expression regex](https://github.com/mapbox/mapbox-plugins-android/blob/master/plugin-localization/src/main/java/com/mapbox/mapboxsdk/plugins/localization/LocalizationPlugin.java#L57) and [the token regex](https://github.com/mapbox/mapbox-plugins-android/blob/master/plugin-localization/src/main/java/com/mapbox/mapboxsdk/plugins/localization/LocalizationPlugin.java#L93), there should no issues.

**Comment by diegolaballos** [comment]
Hi @LukasPaczos this is what our provider is telling us:

1. Our source is not mirroring the streets-v7 schema because this would constitute a copyright infringement - see this [message](https://github.com/osm2vectortiles/osm2vectortiles/issues/387#issue-167962180) .
> We're so flattered by Mapbox Streets vector tiles. However, we do not need to ask you to change that aspect of this project, and it does so by building your own tile schema and cartography. The Mapbox Streets tiles that have been shipped to us, and they are all in one piece, and they are one of the few pieces of our work that we do not openly license. Mapbox Streets vector tiles are copyright Mapbox and only licensed for use with our APIs.

2. It should be sufficient to follow the open Mapbox Vector Tile specification , which we do. The streets-v7 schema is proprietary, and just one of many.

Could you confirm us this and how are we supposed to do it?

Thanks!

**Comment by zugaldia** [comment]
Hey @diegolaballos - thank you for the continued feedback. If I understand the issue so far correctly, the plugin is failing to work with your style because your custom source is not mirroring the streets-v7 schema. If so, this is ultimately a feature request to add new APIs to this plugin that'd let you customize the localization schema.

At this point such a feature isn't in our immediate roadmap so we don't expect to support this use case short term. Having said, this plugin is open source and we welcome contributions :)
