### ISSUE TITLE
Problem rendering a polygon when I modify its vertices

### ISSUE THREAD

**Issue by henriquesobral** [mapbox/mapbox-plugins-android#771]
I've built a simple editable polygon which works fine, but when I move one of it vertices, part of polygon disappears. I've made a video of the issue. https://imgur.com/wk2KJcK

What I did was create a Fill with 4 vertices and 4 draggable Circles on each vertice of Fill, then I start to listen drag events of those Circles using CircleManager and update the corresponding vertice of Fill with the new coordinate.

```java
        @Override
        public void onAnnotationDrag(Circle annotation) {
          ArrayList<LatLng> temp = new ArrayList<>();

          for (int i = 0; i < poligonVertices.size(); i++) {
            if (i == currentIndex) {
              temp.add(annotation.getLatLng());
            } else {
              temp.add(poligonVertices.get(i));
            }
          }
          List<List<LatLng>> latLngs = new ArrayList<>();
          latLngs.add(temp);
          polygon.setLatLngs(latLngs);
          fillManager.update(polygon);
        }
``` 

Thanks

**Comment by LukasPaczos** [comment]
Hey, thanks for testing out the plugin!

Could you verify, that first and last `Point` in your fill's coordinate list are the same? Per GeoJSON spec, the coordinates for any polygon need to be enclosed, see https://github.com/mapbox/mapbox-gl-native/issues/11469#issuecomment-374652946 and [an example](https://github.com/mapbox/mapbox-plugins-android/blob/master/app/src/main/java/com/mapbox/mapboxsdk/plugins/testapp/activity/annotation/FillActivity.java#L54-L58) in our test app.

**Comment by LukasPaczos** [comment]
Closing, please let us know if the provided solution didn't work for you.
