### ISSUE TITLE
Issues applying mapbox local map download to custom tileset

### ISSUE THREAD

**Issue by roderich74** [mapbox/mapbox-plugins-android#787]
We can not find any documentation in the ANDROID PLUGIN FOR LOCAL MAP DOWNLOADS & SYNCING how it can be applied to custom tilesets. 

Is this possible? And if yes how?

**Comment by tobrun** [comment]
@roderich74 documentation for it can be found https://github.com/mapbox/mapbox-plugins-android/tree/master/plugin-localization and https://www.mapbox.com/android-docs/plugins/overview/localization/.

The localization plugin from this repository only support mapbox hosted tilesets for now. See more information and discussion in https://github.com/mapbox/mapbox-plugins-android/issues/761.

Closing this answered.
