### ISSUE TITLE
Accuracy circle layer

### ISSUE THREAD

**Issue by cammace** [mapbox/mapbox-plugins-android#79]
https://github.com/mapbox/mapbox-gl-native/pull/9426 looks to add support for circle pitch alignment in runtime styling thus unlocking the ability to simplify the logic for the accuracy ring and animate it. 

We are currently using a fill layer since it lays flat even when the maps tilted but with this property unlocked it should become a circle layer. Technically all the layer really could become a circle layer but for the customizability available as far as using drawable for the location icon, I'm thinking they should remain symbol layers.

cc: @tobrun @zugaldia

**Comment by cammace** [comment]
On second look, this doesn't seem to be in 5.1.2. Any chance we could pull in that PR into the 5.1 release branch so that we can use it here @tobrun?

**Comment by tobrun** [comment]
`circle pitch alignment` should be available in a 5.2.0-SNAPSHOT, no plans of adding new features to patch releases.

**Comment by tobrun** [comment]
User report on this in https://github.com/mapbox/mapbox-plugins-android/issues/85
