### ISSUE TITLE
Runtime Style MyLocationView Plugin

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-plugins-android#8]
The idea for this plugin is using Runtime Styling to replace current MyLocationView implementation. @cammace started of this work in https://github.com/mapbox/mapbox-gl-native/pull/7516. Instead of merging it to the main SDK, wee could also expose this as a plugin and let the SDK rely on it instead. With a SemVer release we could extract the implementation completely in a separate plugin.

**Comment by cammace** [comment]
#22 has been merged into master!
