### ISSUE TITLE
Allow Places Picker to Work Without ActionBar

### ISSUE THREAD

**Issue by riastrad** [mapbox/mapbox-plugins-android#801]
Currently if you try to initialize place picker in an app that doesn't have an ActionBar, it will cause a crash when you initialize the plugin.

This is because there should be a null check before making this call:
https://github.com/mapbox/mapbox-plugins-android/blob/83c82acb8cd93f689d7a611afeb4febc6b17a093/plugin-places/src/main/java/com/mapbox/mapboxsdk/plugins/places/picker/ui/PlacePickerActivity.java#L65

Fixing this would make the plugin in a little bit more flexible, and potentially ease a lot of pain.

cc: @mapbox/maps-android

**Comment by gauravk95** [comment]
Temporary might be adding this to the main **AndroidManifest.xml**, where AppThemeActionBar is any Custom Theme with Action Bar in it.
  ```
<activity
            android:name="com.mapbox.mapboxsdk.plugins.places.picker.ui.PlacePickerActivity"
            android:configChanges="keyboard|keyboardHidden|orientation|screenLayout|uiMode|screenSize|smallestScreenSize"
            android:theme="@style/AppThemeActionBar"/>
```
