### ISSUE TITLE
Release plugins with the Maps SDK v7.0.0

### ISSUE THREAD

**Issue by LukasPaczos** [mapbox/mapbox-plugins-android#809]
This release brings a change in artifact names of the plugins - from now on, each plugin's artifact name will include a suffix that declares which major version of the Maps SDK this plugin's version is compatible with.

### mapbox-android-plugin-annotation-v7:0.4.0
- Mapbox maps SDK for Android v7.0.0 [#800](https://github.com/mapbox/mapbox-plugins-android/pull/800)
- Save plugin's state across style changes [#800](https://github.com/mapbox/mapbox-plugins-android/pull/800/commits/cba17474e6087faf94375570700d4edfc52b6dd6)
- Exposed filter API [#775](https://github.com/mapbox/mapbox-plugins-android/pull/775)
- Create annotations from FeatureCollection/GeoJSON [#772](https://github.com/mapbox/mapbox-plugins-android/pull/772)
- Invalid symbol ID during animation fix [#776](https://github.com/mapbox/mapbox-plugins-android/pull/776/commits/c2488010f27107693fd529a01afc2f51ecde03cf)
- Make package private abstract classes public [#769](https://github.com/mapbox/mapbox-plugins-android/pull/769)
- Draggable builder option [#768](https://github.com/mapbox/mapbox-plugins-android/pull/768)
- Generic geometry [#777](https://github.com/mapbox/mapbox-plugins-android/pull/777)

### mapbox-android-plugin-building-v7:0.5.0
- Update building plugin with Maps SDK 7.0.0 [#795](https://github.com/mapbox/mapbox-plugins-android/pull/795)

### mapbox-android-plugin-localization-v7:0.7.0
 - Update localization plugin with the Maps SDK v7.0.0 [#791](https://github.com/mapbox/mapbox-plugins-android/pull/791)

### mapbox-android-plugin-markerview-v7:0.2.0
- Update MarkerView plugin with the Maps SDK v7.0.0 [#789](https://github.com/mapbox/mapbox-plugins-android/pull/789)

### mapbox-android-plugin-offline-v7:0.4.0
- Update Offline plugin with the Maps SDK v7.0.0 [#789](https://github.com/mapbox/mapbox-plugins-android/pull/789)
- Cancelling download reworked [#779](https://github.com/mapbox/mapbox-plugins-android/pull/779)
- Add cancel text and enable/disable map snapshots notification options [#805](https://github.com/mapbox/mapbox-plugins-android/pull/805)

### mapbox-android-plugin-places-v7:0.7.0
 - Update Offline plugin with the Maps SDK v7.0.0 [#789](https://github.com/mapbox/mapbox-plugins-android/pull/789)
 - Places plugin NPEs fixes [#806](https://github.com/mapbox/mapbox-plugins-android/pull/806)

### mapbox-android-plugin-traffic-v7:0.8.0
 - Update Traffic plugin with the Maps SDK v7.0.0 [#793](https://github.com/mapbox/mapbox-plugins-android/pull/793)
 - Traffic plugin update [#785](https://github.com/mapbox/mapbox-plugins-android/pull/785)

### Release checklist
- [x] Cut the release branch
- [x] Run through testapp/demo app and test all activities
- [x] Update `CHANGELOG.md`
- [x] Change version names in `gradle.properties`
- [x] Publish artifacts to Maven Central
- [x] Change version name back to `SNAPSHOT`
- [x] Merge the release branch back to `master`
- [x] Tag releases in GitHub

### Post-release @langsmith 
- [x] Update `README.md`
- [x] Update `constants.js` file in `android-docs` repo 
- [x] Generate updated javadocs and add to `android-docs` repo 

/cc: @mapbox/android

**Comment by langsmith** [comment]
All done on my end! Congrats on a huge release, @LukasPaczos 👏 🍾

**Comment by LukasPaczos** [comment]
:tada:
