### ISSUE TITLE
LocationLayerPlugin accurary

### ISSUE THREAD

**Issue by sun2008mt** [mapbox/mapbox-plugins-android#81]
**Platform:Android 6.0
**Mapbox SDK version:5.1.2

1.The accuracy part of LocationLayerPlugin doesn't shown, event changing to customized style;
2.If the accuracy part can be seen, will it change its shape along with the tilt?

**Comment by sun2008mt** [comment]
I've just found the key. I should set the accuracy range of the location myself using the setAccuracy() method of class Location. I doubt if there should be a default accuracy of LocationLayerPlugin.

**Comment by cammace** [comment]
Sounds like you worked this issue out and it is safe to close?
