### ISSUE TITLE
Widget combining the place picker and the address autocompleter

### ISSUE THREAD

**Issue by abustany** [mapbox/mapbox-plugins-android#818]
The place picker from Google shows a search field on top of the map (see https://developers.google.com/places/android-sdk/placepicker ), which allows to search for a place by its name first, and potentially refine the position afterwards by panning and zooming. In Mapbox, those are two separate widgets (or two activities you can start and wait for). I'm sure combining the two widgets from the Mapbox SDK together in a new activity is no rocket science, but it'd be convenient to have it as a built-in so I could just invoke the activity and retrieve the CarmenFeature as a result... Maybe having a search field could just be an option enabled via a field in `PlacePickerOptions` ?

**Comment by percula** [comment]
I am also in need of such a feature. Google is deprecating the Place Picker and this would be a perfect replacement.

**Comment by czorek** [comment]
Bumping this, it would be a nice thing to have indeed.
