### ISSUE TITLE
Provide fallback to rotation vector sensor missing 

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-plugins-android#82]
Copied from https://github.com/mapbox/mapbox-gl-native/issues/9149

**Platform:** Android
**Mapbox SDK version:** 5cf0fc0f8bb3f66fd7844cae73efca1a4c2d94f5

### Steps to trigger behavior

 1. Open user tracking mode example in SDK test app
 2. Set bearing mode to either GPS bearing or compass bearing

### Expected behavior

View tracks bearing, and arrow appears above user location marker as in the screenshots in https://github.com/mapbox/mapbox-gl-native/issues/8238#issuecomment-283681408.

### Actual behavior

The bearing mode settings doesn't appear to do anything.

![device-2017-05-30-190421](https://cloud.githubusercontent.com/assets/1450212/26608955/5a18421a-456c-11e7-8d7d-79857ab6e80b.png)

I've tested it in an Android 7.1 emulator and on a Moto G running Android 5.1. I know it worked in version 4.0 of the SDK.

**Comment by cammace** [comment]
This issue should be resolved in the location layer plugin and will fall back to the deprecated `TYPE_ORIENTATION` [if the rotation vector is null](https://github.com/mapbox/mapbox-plugins-android/blob/master/plugins/locationlayer/src/main/java/com/mapbox/mapboxsdk/plugins/locationlayer/CompassManager.java#L49-L52). I haven't found a device to reliably test this though.

**Comment by tobrun** [comment]
I have such a device, let me try testing this.
