### ISSUE TITLE
Why Hiding SymbolOptions when then intersect?  zoomIn/zoomOut

### ISSUE THREAD

**Issue by serzh-f** [mapbox/mapbox-plugins-android#829]
How can i show all markers on map? If I trying use SymbolOptions in one place - they hiding and when I zoomIn it show again

**Comment by tobrun** [comment]
This is because of the underlying default configuration of the SymbolLayer. 
You can alter this behavouir using the SymbolManager, by calling:

```java
symbolManager#setIconAllowOverlap(true);
symbolManager#setIconIgnorePlacement(true);
```

@mapbox/maps-android should we make this configuration the default?

**Comment by LukasPaczos** [comment]
I'd personally rather follow what's default in the Maps SDK. How about we expose an overrode constructor with `setIconAllowOverlap` flag to increase discoverability of this option?

**Comment by tobrun** [comment]
`How about we expose an overrode constructor with `setIconAllowOverlap` flag to increase discoverability of this option?` adding such construction might lead to a bunch of overloaded constructors, similar to LocationComponent. To fix that, I would suggest using a Builder or Options class  but this again removes that discoverability that you are wanting to add.

**Comment by LukasPaczos** [comment]
In this case, I'd lean towards leaving this as is, following what's default in the Maps SDK. We can improve our docs and examples to make this option easier to discover.
