### ISSUE TITLE
Custom autocomplete place search

### ISSUE THREAD

**Issue by shinejosephDev** [mapbox/mapbox-plugins-android#846]
Hi,  I would like to implement location search with `AutoComplete` in my app with custom `RecycleView` and `Adapter`. Is there any documentation available to do that, all I could find is with the  `Intent` which directs to another Activity.

Thanks

**Comment by tobrun** [comment]
These Activities use the custom views as shown in this package.
Feel free to open a PR if additional features should be exposed.
