### ISSUE TITLE
Add Annotation Plugin custom image example

### ISSUE THREAD

**Issue by lomza** [mapbox/mapbox-plugins-android#848]
Hi,

I've been following example of SymbolActivity.java - https://github.com/mapbox/mapbox-plugins-android/blob/master/app/src/main/java/com/mapbox/mapboxsdk/plugins/testapp/activity/annotation/SymbolActivity.java and found out that Maki images as used as symbol image. I have an svg image, imported as vector image into Android Studio. How can I use it for my symbol icon image?

Thanks!

**Comment by LukasPaczos** [comment]
Hey @lomza, thanks for reaching out!

You will need to convert your SVG to a bitmap (you can easily find how to do that on the web) and add it to the map with
```
mapboxMap.getStyle(new Style.OnStyleLoaded() {
  @Override
  public void onStyleLoaded(@NonNull Style style) {
    style.addImage("my_image", bitmap);
  }
});
```
then you can reference that image's ID in the `SymbolOptions`
```
SymbolOptions symbolOptions = new SymbolOptions()
        .withLatLng(new LatLng(6.687337, 0.381457))
        .withIconImage("my_image")
        ...
```

**Comment by lomza** [comment]
@LukasPaczos , thank you so much! It worked perfectly ;)

**Comment by gracedotdotdot** [comment]
Hi i want to add multiple markers on it, and I add

>  // create symbol manager
>                 GeoJsonOptions geoJsonOptions = new GeoJsonOptions().withTolerance(0.4f);
>                 symbolManager = new SymbolManager(mapView, mapboxMap, style, null, geoJsonOptions);
>                 // create a symbol
>                 SymbolOptions symbolOptions = new SymbolOptions()
>                         .withLatLng(new LatLng(31.995560, 34.767070))
>                         .withIconImage("Charge")
>                         .withIconSize(1.3f)
>                         .withDraggable(true);
>                 symbol = symbolManager.create(symbolOptions);

But it isn't showing any markers, may I ask what may be the problems?

**Comment by LukasPaczos** [comment]
Sure @gracedotdotdot, check out [`PressForSymbolActivity`](https://github.com/mapbox/mapbox-plugins-android/blob/c492ee8f5a40b33b274229dc6a574a1a800862c0/app/src/main/java/com/mapbox/mapboxsdk/plugins/testapp/activity/annotation/PressForSymbolActivity.java) example.

**Comment by gracedotdotdot** [comment]
when I try to use the addSymbol function in your reference. I add the

> implementation 'com.mapbox.mapboxsdk:mapbox-android-plugin-annotation-v8:0.7.0'

line in my build.gradle, but it comes error

> Duplicate class com.mapbox.mapboxsdk.plugins.annotation.Annotation found in modules classes.jar (com.mapbox.mapboxsdk:mapbox-android-plugin-annotation-v7:0.6.0) and classes.jar (com.mapbox.mapboxsdk:mapbox-android-plugin-annotation-v8:0.7.0)

**Comment by LukasPaczos** [comment]
You can inspect your dependencies and verify where the duplicate is coming from:
https://stackoverflow.com/a/39020703/9126211.

**Comment by gracedotdotdot** [comment]
Hi I've already deleted the duplicate libraries but it's still popping duplicate class error.
may I ask why can't I use the code in #1017 to add multiple markers dynamically?
Thank you

**Comment by HridaySarma** [comment]
Thanks @LukasPaczos  for helping out. I was finding difficulty to implement custom icons to the map that goes with our algorithm. It worked like a charm.
