### ISSUE TITLE
LocationLayer accuracy radius moves asynchron

### ISSUE THREAD

**Issue by P-Zenker** [mapbox/mapbox-plugins-android#85]
**Platform: Android**
**Mapbox SDK version: 5.1.2**
'mapbox-android-plugin-locationlayer', version: '**0.1.0**'
or 'mapbox-android-plugin-locationlayer', version: '0.2.0-SNAPSHOT'

### Steps to trigger behavior

 1. I've downloaded your [plugin repo](https://github.com/mapbox/mapbox-plugins-android) and copied most of the stuff to my own project.
 2. Use a mock location app
 3. Switch to tracking / compass mode

### Expected behavior
If the location layer receive a update, move location and accuracy radius simultaneously

### Actual behavior
First the accuracy radius moves instantly and the location dot animates afterwards

![2017-08-21 17 21 09](https://user-images.githubusercontent.com/23097192/29526765-fd3e4744-8696-11e7-96db-70b1ae353ba0.gif)

Maybe this issue belongs to [#79?](https://github.com/mapbox/mapbox-plugins-android/issues/79)

**Comment by cammace** [comment]
#79 will be the fix for this. The current implementation requires drawing a fill-layer on the map using several Points which would cause a performance hit if we chose to animate them. Thus, until circle-pitch alignment gets unblocked in 5.2, the update for the accuracy will need to be instant.

**Comment by tobrun** [comment]
Going to be resolved with https://github.com/mapbox/mapbox-plugins-android/issues/79
