### ISSUE TITLE
LineOptions.java is missing dash-array getter/setter

### ISSUE THREAD

**Issue by PawelZarzycki** [mapbox/mapbox-plugins-android#850]
Hey,
I'm trying to draw a simple dashed-line with annotation plugin.  I can see that you have line-dasharray option in your style guide:
https://docs.mapbox.com/mapbox-gl-js/style-spec/ but I can't see it exposed in LineOptions.java.
Is there something missing here? If not can you point to some example ? 
Regards,
Paweł

**Comment by LukasPaczos** [comment]
Unfortunately, as you can see in the documentation, [`line-dasharray` is not data-driven](https://docs.mapbox.com/mapbox-gl-js/style-spec/#paint-line-line-dasharray). This means, that you won't be able to style each line separately, however, you can use [`LineManager#setLineDasharray`](https://docs.mapbox.com/android/api/plugins/annotation/0.5.0/com/mapbox/mapboxsdk/plugins/annotation/LineManager.html#setLineDasharray-java.lang.Float:A-) to change the pattern for all of the lines created by one manager. To have different patterns at once, you will have to create multiple `LineManager`s.

I hope this helps!
