### ISSUE TITLE
Places plugin missing timber dependency

### ISSUE THREAD

**Issue by androideveloper** [mapbox/mapbox-plugins-android#856]
I have added it on my side and it works, please release a new version with the dependency

**Comment by tobrun** [comment]
This was fixed with https://github.com/mapbox/mapbox-plugins-android/commit/2edb52ae0d735a52516699a97bd5cef745e523d0 but we haven't made a release to include this fix yet.

**Comment by tobrun** [comment]
This was fixed with https://github.com/mapbox/mapbox-plugins-android/commit/2edb52ae0d735a52516699a97bd5cef745e523d0 but we haven't made a release to include this fix yet.

**Comment by androideveloper** [comment]
Ok, I see. When do you plan to release?

**Comment by LukasPaczos** [comment]
Most likely sometime next week to bundle the Maps SDK `v7.3.0`. I'm going to close as this is fixed on `master` already.
