### ISSUE TITLE
Place picker without geocoding option

### ISSUE THREAD

**Issue by androideveloper** [mapbox/mapbox-plugins-android#857]
We want a simple location picker, just to return back lat/lng, without Geocoding option. Is it possible with current API-s?

**Comment by tobrun** [comment]
@androideveloper this is currently not a feature but we happily accept a PR for it. You can convert any screen coordinate (x,y) to a LatLn using `MapboxMap#getProjection#fromScreenLocation(PointF)`

**Comment by androideveloper** [comment]
Thanks!

**Comment by langsmith** [comment]
Adding this functionality is happening in #965
