### ISSUE TITLE
LocationLayer W/art errors

### ISSUE THREAD

**Issue by P-Zenker** [mapbox/mapbox-plugins-android#86]
**Platform: Android**
**Mapbox SDK version: 5.1.2**
'mapbox-android-plugin-locationlayer', version: '**0.1.0**'

### Steps to trigger behavior

I've downloaded your [plugin repo](https://github.com/mapbox/mapbox-plugins-android) and copied most of the stuff to my own project to test your plugin. 

### Expected behavior
No W/art errors

### Actual behavior
I receive a lot of "W/art: Attempt to remove non-JNI local reference, dumping thread" errors on my Google Nexus 6 with Android 7.1.1. 
On my Samsung Galaxy S3 (GT-I9300) with Android 4.3 and on my MOBISTEL Cynus E4 (very cheap smartphone with Android 5.1) there are no "non-JNI" erros, but I see "W/art: Attempt to remove local handle scope entry from IRT, ignoring" errors.

The error message don't have negative effects on your LocationLayer (as far as I can see).

**Comment by tobrun** [comment]
Thank you for the report, this is an issue upstream in https://github.com/mapbox/mapbox-gl-native/issues/9688. Closing as it needs to be resolved in that repo.
