### ISSUE TITLE
Mapbox managers require mapview for initialization, but SupportMapFragment mapview is private

### ISSUE THREAD

**Issue by androideveloper** [mapbox/mapbox-plugins-android#861]
When I use SupportMapFragment with plugins, all annotaion managers require mapview, which is private in SupportMapFragment. I know this issue was once opened https://github.com/mapbox/mapbox-plugins-android/issues/333, but solution seems to be a hack way. Why not provide a simple reference to underlying mapview in SupportMapFragment?

**Comment by tobrun** [comment]
SupportMapFragment does expose getting notified about MapView creation through `MapFragment.OnMapViewReadyCallback`. Let your Activity implement this interface and you will receive a callback when the fragment has created the MapVIew.

**Comment by androideveloper** [comment]
Actually I'm inheriting from SupportMapFragment. I found a way to refer mapview: 
` mapView = super.onCreateView(layoutInflater, viewGroup, savedInstance) as MapView`
Thanks anyway!
