### ISSUE TITLE
How to use Icon Halo ?

### ISSUE THREAD

**Issue by ben-j69** [mapbox/mapbox-plugins-android#868]
I checked in the demo project and in the documentation and I can not find the good way to use Icon Halo on a Symbol.

I also have tried many different value and nothing happen. The code documentation is not clear enough on what value are expected.

`.withIconHaloBlur(1f / 100f / 1000f)
                        .withIconHaloWidth(1f / 100f / 1000F)
                        .withIconHaloColor("black" / "000000" / "#000000")`

**Comment by tobrun** [comment]
More information in the style specification [here](https://docs.mapbox.com/mapbox-gl-js/style-spec/#paint-symbol-icon-halo-color). Key thing to take away that his is only supported for sdf images (you can pass an android vector drawable as a bitmap). You can indicate to the map if an bitmap can be handled as sdf by passing in true to the sdf flag in Style#addImage.

**Comment by tobrun** [comment]
Leaving this issue open so we can add an example for it.

**Comment by ben-j69** [comment]
@tobrun so using these values I should be able to see a dark shadow arround my marker ?

` options.withIconAnchor("left")
                        .withIconImage(step.publisherId)
                        .withLatLng(LatLng(step.location.latitude(), step.location.longitude()))
                        .withIconOffset(arrayOf(-15f, 0f))
                        .withIconHaloBlur(30f)
                        .withIconHaloWidth(30f)
                        .withIconHaloColor("rgba(0, 0, 0, 1)")`

Because nothing is displayed around my marker.

**Comment by tobrun** [comment]
yes but only if you image icon is an SDF image, to close this issue we need to add an example on this
