### ISSUE TITLE
Quick navigation controls on Symbol click

### ISSUE THREAD

**Issue by androideveloper** [mapbox/mapbox-plugins-android#873]
Is there a way to show quick navigation controls like in Google Maps, when user clicks on symbol? Another question is how to show user current location button? Is there a standard way?

![Screenshot_20190312-102435](https://user-images.githubusercontent.com/1249919/54179597-aaaf6680-44b2-11e9-9a31-b61bef6134bd.png)

**Comment by LukasPaczos** [comment]
Hey @androideveloper, those features would have to be manually implemented, we don't have any predetermined ways of showing these types of controls. Feel free to [contact support](https://docs.mapbox.com/help/) if you need any further help!

Closing as answered, thanks for reaching out.
