### ISSUE TITLE
MarkerView projection update lags

### ISSUE THREAD

**Issue by kathyma** [mapbox/mapbox-plugins-android#880]
When using the `MarkerView` plugin, there is a noticeable lag in its position updates when you pan / zoom the map. I screen recorded [a video](https://drive.google.com/file/d/1pNDp9TD_5W2JaMXUap8TL26lswMmMYjV/view?usp=sharing) from the Android Mapbox demo app.

Just from logging the callback rate with `MarkerView#setOnPositionUpdateListener`, it doesn't seem like frame rate is the issue (seeing 60fps on a Pixel 3), so I suspect the projection update is out of sync with the map movements causing `Projection.toScreenLocation` to return an inaccurate position [here](https://github.com/mapbox/mapbox-plugins-android/blob/master/plugin-markerview/src/main/java/com/mapbox/mapboxsdk/plugins/markerview/MarkerView.java#L75).

Any ideas on how this can be fixed?

**Comment by tobrun** [comment]
@kathyma this is known downside of synchronizing an Android SDK view on top of Surface. The underlying projection is not in sync with the applied projection to the View. This was the reason why we stripped out MarkerView from the main sdk and provided it as a plugin instead. You should be able to get better results using a TextureView as rendering surface (vs GLSurfaceView by default). This can be enabled through mapboxMapOptions#textureMode(true) or with xml attributes. 

If you don't need an interactive view but just a visual representation (bitmap) of it, you can migrate to either a SymbolLayer or AnnotationPlugin by using the following [sample code](https://github.com/mapbox/mapbox-gl-native/blob/master/platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/style/SymbolGeneratorActivity.java). Hope this clear things, sadly I don't have an immidate fix for the issue at hand.

**Comment by vahidlazio** [comment]
I created my own marker view couple of months ago, maybe it's useful for mapbox team as well. i wrapped the mapview in another touch aware view in SupportMapFragment.
Whenever i receive a new touch callback, I calculate the new projection again.
