### ISSUE TITLE
String color API

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-plugins-android#881]
While implementing annotation support in flutter plugin. I noticed that having only Android color int support is a bit too limiting. We should allow setting string colors conform to style spec:

```
{
    "line-color": "#ff0",
    "line-color": "#ffff00",
    "line-color": "rgb(255, 255, 0)",
    "line-color": "rgba(255, 255, 0, 1)",
    "line-color": "hsl(100, 50%, 50%)",
    "line-color": "hsla(100, 50%, 50%, 1)",
    "line-color": "yellow"
}
```

**Comment by LukasPaczos** [comment]
Closed by https://github.com/mapbox/mapbox-plugins-android/pull/897.
