### ISSUE TITLE
Dragged annotation triggers Map Clicked

### ISSUE THREAD

**Issue by sebastienrouif** [mapbox/mapbox-plugins-android#883]
Scenario :
 - on master "1e032afb0652582e19166ef41ab8db03ca064f33"
 - open the app in the CircleActivity, Drag a circle for a short amount of time and distance
 - observe a toast for CircleClicked

Expected behaviour :
 - as the circle has been dragged I was not expecting the click listener to be triggered

A similar problem happens with the long click

I'll try to investigate how the DraggableAnnotationController could be changed to include that behavior.

**Comment by androideveloper** [comment]
The same here

**Comment by JonasVautherin** [comment]
Is there a workaround to that? Like a way to detect in the long click callback that a drag is active?

**Comment by ajaykotianneebal** [comment]
Any workaround found for this issue?

**Comment by kikothemaster** [comment]
Any workaround found for this issue?
