### ISSUE TITLE
SymbolOptions / Symbol info window

### ISSUE THREAD

**Issue by william-reed** [mapbox/mapbox-plugins-android#887]
Is it possible to show an info window (as you would with a Marker / Marker options) on symbol click?

If not is this functionality I must add myself listening to symbol clicks?

With #649 it looks like its not implemented yet. Is it possible to draw my own view while this probably won't be implemented for a bit?

The reason I switched to the annotation plugin is to easily support settings icons, rotating, etc compared to the standard SDK. Should I switch to something in the standard SDK?

**Comment by LukasPaczos** [comment]
Hey @william-reed, thanks for using Mapbox! Unfortunately, there is no option to display info windows without https://github.com/mapbox/mapbox-plugins-android/issues/649. You can try and create your own `GeoJsonSource` + `SymbolLayer` combo and display that at the same position as your selected annotation. For more info see [this example](https://github.com/mapbox/mapbox-android-demo/blob/master/MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/examples/labs/SymbolLayerMapillaryActivity.java) which besides implementing custom `SymbolLayer` based info windows also handles clicks inside of them.

**Comment by HridaySarma** [comment]
You can use MarkerView to get a similar view. It contains less functions but it gets me what i want. Check this for example : https://docs.mapbox.com/android/plugins/examples/marker-view-plugin
