### ISSUE TITLE
Keep receiving location updates

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-plugins-android#89]
- Actively change location
- Open `Toggle Manual Location Updates` Activity
- Press back button

Logcat is still reporting location updates

```
D/ManualLocationUpdatesAc: Location change occurred: Location[gps 41.262107,-4.676861 acc=8 et=+13m34s198ms alt=118.38145002 vel=22.222221 bear=351.00644 mock]
```

cc @cammace

**Comment by cammace** [comment]
Simply stopping updates, removing listener, and deactivating, should fix the issue inside `onDestroy()`. https://github.com/mapbox/mapbox-plugins-android/blob/master/plugins/app/src/main/java/com/mapbox/mapboxsdk/plugins/testapp/activity/location/ManualLocationUpdatesActivity.java#L138
