### ISSUE TITLE
SymbolManager not supported in offline mode.

### ISSUE THREAD

**Issue by SillyV** [mapbox/mapbox-plugins-android#892]
When using SymbolManager to add Symbols after calling  

`Mapbox.setConnected(false)`

`symbolManager.create(symbolOptions)`

symbols are not displayed.

**Comment by LukasPaczos** [comment]
Hey @SillyV, I'm not able to reproduce the issue. Would you be able to provide a minimal example?

**Comment by SillyV** [comment]
I am trying to reproduce it on a blank project and can't for now. I will close the issue until I will either find the edge case bug or find my own bug.

**Comment by Sanunez** [comment]
I'm having the same issue
It seems that the SymbolManager is null when being created offline.
when attempting to create a symbole I get a null pointer error
