### ISSUE TITLE
Location Layer requires google maven

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-plugins-android#90]
The setup instructions in the readme file don't include:

```
        maven { url 'https://maven.google.com' }
```

This is required for the architecture components used by the plugin

**Comment by langsmith** [comment]
@tobrun , [I've updated the location layer plugin readme](https://github.com/mapbox/mapbox-plugins-android/blob/master/plugins/locationlayer/README.md). If I've done something wrong, please re-open this ticket and let me know 🙇
