### ISSUE TITLE
Error: Invoke-customs are only supported starting with Android O (--min-api 26)

### ISSUE THREAD

**Issue by ANGerz** [mapbox/mapbox-plugins-android#900]
Hello,
I have a problem with the Mapbox's Annotation plugin since I am removing all deprecated classes from Mapbox (Marker, MarkersOptions..) to be up to date.

Android Studio version : 3.3.1
Kotlin : 1.3.21
Mapbox-android-sdk : 7.2.0
Mapbox-android-plugin-offline-v7: 0.4.0
Mapbox-android-plugin-annotation-v7: 0.5.0

I added the annotation plugin and now the project won't correctly compile. I have this error : 
```Error: Invoke-customs are only supported starting with Android O (--min-api 26)```

I guess this is happening because Mapbox Annontation use Java 8. Some researches bring me a solution by adding 

```
compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
```

But I think I should not add this in my gradle file. I am using Kotlin so I do not need to enable Java 8. Maybe I am doing something wrong here. Is this a _normal_ error ? Should I enable Java 8 even if I use Kotlin ?

Thanks you for your support

**Comment by LukasPaczos** [comment]
Hey @ANGerz, yes, your project has to have Java 8 features enabled in order to use the plugin because the plugin has been compiled using Java.

**Comment by ANGerz** [comment]
Thanks you for your answer. I think the documentation should specify this behavior for more clarity.
