### ISSUE TITLE
How to Add   custom marker  ?

### ISSUE THREAD

**Issue by CMingTseng** [mapbox/mapbox-plugins-android#901]
If i want  custom marker ( All  different !!!)

Before  i Ref : https://stackoverflow.com/questions/34586876/how-can-i-create-a-speech-bubble-border-for-a-google-marker-custom-icon-using-pi

i use   Picasso & Glide do it 

Outer frame  Ref : https://pse.is/GMUCR

now ?

THX

**Comment by ben-j69** [comment]
You can generate views, then translate it in Bitmap and add it as Symbol.

**Comment by LukasPaczos** [comment]
What @ben-j69 mentioned should be the correct solution for runtime-generated images.

You can add the image to the map with `MapboxMap#addImage` and reference that image ID when building `SymbolOptions`.

**Comment by mortezahosseinee** [comment]
I use Bubble layout and show custom info window. my info window has edittext, image view and ... . and i need handle click of views on info window that has custom xml layout. bubble layout was depricated. help me what can i do to do get my goal!!?


i asked same question in another word and i did not get right answer, refer: 
https://github.com/mapbox/mapbox-plugins-android/issues/649#issuecomment-489989961

**Comment by frankgogoland** [comment]
I came across same question,Could you give me some samples?

**Comment by mortezahosseinee** [comment]
Do you need custom icon in marker place or custom view in info window?

**Comment by frankgogoland** [comment]
list.add(new SymbolOptions()
         .withLatLng(new LatLng(60.169432, 24.939876))
         .withIconImage(MAKI_ICON_CAFE)
         .withIconSize(2.0f)
         .withDraggable(true))       ;
list.add(new SymbolOptions()
        .withLatLng(new LatLng(60.169530, 24.939876))
        .withIconImage(MAKI_ICON_AIRPORT)
        .withIconSize(2.0f)
        .withDraggable(true));
// Add symbol at specified lat/lon
 symbolManager.create(list);
in fact I want to real time to create bitmap that can be input into the list. I really don't understandt how to replace icon Image, thanks






------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Morteza Hosseini"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月17日(星期二) 晚上8:15
收件人:&nbsp;"mapbox/mapbox-plugins-android"<mapbox-plugins-android@noreply.github.com&gt;;
抄送:&nbsp;"冰冻三尺"<1223774014@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [mapbox/mapbox-plugins-android] How to Add   custom marker  ? (#901)




Do you need custom icon in marker place or custom view in info window?
