### ISSUE TITLE
OfflinePlugin getActiveDownloads() returns inactive downloads

### ISSUE THREAD

**Issue by xit0c** [mapbox/mapbox-plugins-android#907]
### Steps to reproduce

 1. Create a new Android Studio project with Kotlin
 2. Add these module dependencies
`implementation 'com.mapbox.mapboxsdk:mapbox-android-sdk:7.3.0'`
`implementation 'com.mapbox.mapboxsdk:mapbox-android-plugin-offline-v7:0.4.0'`
`implementation 'com.jakewharton.timber:timber:4.7.1'`
and this permission to the manifest
`<uses-permission android:name="android.permission.FOREGROUND_SERVICE" />`
 3. Copy/Paste the `MainActivity` class and `activity_main` layout code from the attached files
 4. Run the app and use the buttons 'Active Downloads' to show/log the active downloads and 'Download' to start a new download

### Expected behavior
`getActiveDownloads()` should return only downloads in `STARTED` or `PROGRESS` state.

### Actual behavior
`getActiveDownloads()` returns all the started downloads, even if they are finished, canceled or terminated by an error.

### Configuration

Android versions: [9, 6.0.1]
Device models: [Xiaomi Mi A1, OnePlus One]
Mapbox SDK version: 'mapbox-android-sdk:7.3.0'
Mapbox Offline Plugin version: 'mapbox-android-plugin-offline-v7:0.4.0'

### Attachments

[activity_main.txt](https://github.com/mapbox/mapbox-plugins-android/files/3044331/activity_main.txt)
[MainActivity.txt](https://github.com/mapbox/mapbox-plugins-android/files/3044332/MainActivity.txt)

**Comment by mik1407** [comment]
Same here!

**Comment by Alton09** [comment]
I'm seeing the same error. This makes it difficult to prevent users from continuously downloading the same offline region.

**Comment by xit0c** [comment]
If someone is still facing this issue, I've written a library inspired to Mapbox's offline plugin that better handles downloads related events.

https://github.com/xit0c/mapbox-plugin-offline
