### ISSUE TITLE
Release plugins with the Maps SDK v7.3.0

### ISSUE THREAD

**Issue by LukasPaczos** [mapbox/mapbox-plugins-android#914]
#### Features
- Maps SDK bump to 7.3.0 [#895](https://github.com/mapbox/mapbox-plugins-android/pull/895)
- Add toString, hashcode and equals [#858](https://github.com/mapbox/mapbox-plugins-android/pull/858)
- Delete all annotations method [#859](https://github.com/mapbox/mapbox-plugins-android/pull/859)
- Add style spec documentation generation [#879](https://github.com/mapbox/mapbox-plugins-android/pull/879)
- Move supported json properties docs to the public methods [#889](https://github.com/mapbox/mapbox-plugins-android/pull/889)
- Support string color for layout properties [#897](https://github.com/mapbox/mapbox-plugins-android/pull/897)
- Expose GeoJsonOptions [#909](https://github.com/mapbox/mapbox-plugins-android/pull/909)
#### Bugs
- Check if annotation is an active annotation when updating [#891](https://github.com/mapbox/mapbox-plugins-android/pull/891)
- Use with prefix for options [#898](https://github.com/mapbox/mapbox-plugins-android/pull/898)
- Notify gesture manager when drag is handled [#906](https://github.com/mapbox/mapbox-plugins-android/pull/906)
- Register only one style loaded listener [#905](https://github.com/mapbox/mapbox-plugins-android/pull/905)
- Use constants wherever property name strings are needed [#910](https://github.com/mapbox/mapbox-plugins-android/pull/910)

#### Features
- Maps SDK bump to 7.3.0 [#895](https://github.com/mapbox/mapbox-plugins-android/pull/895)
- Add better support for Chinese languages [#878](https://github.com/mapbox/mapbox-plugins-android/pull/878)
#### Bugs
- Correct javadoc syntax [#871](https://github.com/mapbox/mapbox-plugins-android/commit/0761054e0be8b55e5c41415bf196ab8c42a4decc)
- Remove textField constant value check [#875](https://github.com/mapbox/mapbox-plugins-android/pull/875)
- Register only one style loaded listener [#905](https://github.com/mapbox/mapbox-plugins-android/pull/905)

#### Features
- Maps SDK bump to 7.3.0 [#895](https://github.com/mapbox/mapbox-plugins-android/pull/895)
- Use a generic OfflineRegionDefinition [#913](https://github.com/mapbox/mapbox-plugins-android/pull/913)
#### Bugs
- Include missing Timber dependency [#820](https://github.com/mapbox/mapbox-plugins-android/pull/820/commits/12083e8964fd81b4cd0818bfcc2d433ba361b6fa)
- Disable vector drawable in download notification on pre lollipop devices [#866](https://github.com/mapbox/mapbox-plugins-android/pull/866)
- Check for null intent in case of a service restart [#912](https://github.com/mapbox/mapbox-plugins-android/pull/912)

#### Features
- Maps SDK bump to 7.3.0 [#895](https://github.com/mapbox/mapbox-plugins-android/pull/895)
#### Bugs
- Include missing Timber dependency [#820](https://github.com/mapbox/mapbox-plugins-android/pull/820/commits/12083e8964fd81b4cd0818bfcc2d433ba361b6fa)

## Release checklist
- [x] Cut the release branch
- [x] Run through testapp/demo app and test all activities
- [x] Update `CHANGELOG.md`
- [x] Change version names in `gradle.properties`
- [x] Publish artifacts to Maven Central
- [x] Change version name back to `SNAPSHOT`
- [x] Merge the release branch back to `master`
- [x] Tag releases in GitHub

## Post-release @langsmith 
- [x] Update `README.md`
- [x] Update `constants.js` file in `android-docs` repo 
- [x] Generate updated javadocs and add to `android-docs` repo 
- [x] If needed, bump dependencies in https://github.com/mapbox/mapbox-android-demo

/cc: @mapbox/android @mapbox/enterprise-support

**Comment by langsmith** [comment]
All done here 🕺 ☑️
