### ISSUE TITLE
Multiple manager support

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-plugins-android#921]
Due to the plugin setup and how gl-native works under the hood, we are unable to show lines with and without a line pattern configuration. Once you set a pattern, the non line pattern lines disappear (more context on this in https://github.com/mapbox/mapbox-gl-native/issues/14331).

One solution to this would be to allow to have multiple line manangers. One for the line pattern one, the other for normal lines. To achieve this we need to generate the IDs of the used source and layers dynamically. 

cc @mapbox/maps-android

**Comment by ben-j69** [comment]
We also need to instantiate multiple manager to draw normal polyline and dashed polylines.
