### ISSUE TITLE
Add separate make targets

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-plugins-android#93]
We currently expose targets as `make publish` or `make release`. These targets now include all the different plugins, we should introduce separate targets in a similar way as we expose [abi's on gl-native](https://github.com/mapbox/mapbox-gl-native/blob/master/Makefile). 

eg.

>make release-cluster
make publish-location-layer

cc @cammace

**Comment by cammace** [comment]
The Makefile supports this now https://github.com/mapbox/mapbox-plugins-android/blob/master/Makefile
