### ISSUE TITLE
SymbolManager.setIconIgnorePlacement(true) seems to have no effect

### ISSUE THREAD

**Issue by zestyping** [mapbox/mapbox-plugins-android#935]
I'm adding a symbol to the map using `SymbolManager.create(...)`.

I have called
```
symbolManager.setIconAllowOverlap(true);
symbolManager.setIconIgnorePlacement(true);
```

But when my symbol appears, other symbols on the base map that collide with it still disappear.  This seems to be contrary to what `setIconIgnorePlacement(true)` is supposed to do.  Do I have that right or have I misunderstood the purpose of `setIconIgnorePlacement`?  What's the correct way to prevent my symbols from making base map symbols disappear?

The symbols also aren't drawn when they're too near each other.  I'd like the symbols to always be drawn.  I thought `setIconAllowOverlap(true)` would do that, but it doesn't seem to work.  Is there a way to ensure that every symbol is always drawn?

Is there a way to turn off collision detection entirely?

**Comment by zestyping** [comment]
Here's a video capture that shows the problem.  The symbols in question are the small red circles.

[createSymbol-latency.mp4.zip](https://github.com/mapbox/mapbox-plugins-android/files/3102076/createSymbol-latency.mp4.zip)

The symbols and labels on the base map are disappearing as the symbols are added.  Also, the symbols being added don't always appear—you can see that for the last few taps, the symbol isn't drawn at all because it's close to another symbol.

**Comment by tobrun** [comment]
@zestyping there are equivalent text equivalent methods availlable as well:

```
symbolManager.setTextIgnorePlacement(true);
symbolManager.setTextIgnorePlacement(true);
```

You should be able to get the requested UX with above in place.

**Comment by zestyping** [comment]
Thank you very much @tobrun!  This solved the issue!
