### ISSUE TITLE
Adding symbols is slow

### ISSUE THREAD

**Issue by zestyping** [mapbox/mapbox-plugins-android#936]
When I add a symbol to the map with `SymbolManager.create(...)`, the symbol fades in slowly (it takes at least 500 ms), which makes UI interactions feel sluggish.  `map.getStyle().setTransition(new TransitionOptions(0, 0, false))` makes the symbol appear all at once instead of fading in, but it still appears after a long delay.

I'd like to make symbols appear instantly.  Is there a way to do this?

I wonder if the long delay is due to collision testing.  Possibly related to #935—I can't seem to turn off collision testing.  Should one expect `setIconIgnorePlacement(true)` to make this faster?

**Comment by zestyping** [comment]
Here's a video capture illustrating the issue.  Taps are shown as white circles.  You can see that the symbols only appear a very long time after each tap.

[createSymbol-latency.mp4.zip](https://github.com/mapbox/mapbox-plugins-android/files/3102034/createSymbol-latency.mp4.zip)

**Comment by zestyping** [comment]
Here's a video capture of the same thing after `setTransition(new TransitionOptions(0, 0, false))`.  The symbols no longer fade in, but they still appear a very long time after each tap.

[createSymbol-transition0-latency.mp4.zip](https://github.com/mapbox/mapbox-plugins-android/files/3102044/createSymbol-transition0-latency.mp4.zip)

**Comment by tobrun** [comment]
@zestyping the annotation plugin is hacky way of having an OO way of handling markers build on top of a GeoJsonSource and layers. This way requires us to do not optimal updates before we can render. If you need more performance, I would advice you to take a use the lower level APIs of GeoJsonSource with a SymbolLayer and FillLayer instead. That said, I would love to track down which part of the code takes up most time and see if there are some optimizations possible.
