### ISSUE TITLE
Query map when clicked on POI name

### ISSUE THREAD

**Issue by cammace** [mapbox/mapbox-plugins-android#94]
With Query layers, we can now support clicking on POI names/labels on the map and highlighting the name on the map and increase the text size along with perform geocoding at that location to get more information.

**Comment by tobrun** [comment]
nice idea, would be great if we can provide a callback for the resulting action so the user can customize it to his own use-case. Related to performing geocoding, I feel this should either be made part of our current geocoding library? or having a separate plugin build on top of this one?
