### ISSUE TITLE
How can SymbolManager instantiated when used with SupportMapFragment

### ISSUE THREAD

**Issue by TankJK** [mapbox/mapbox-plugins-android#951]
Hi there,

Application wants to use SymbolManager but it cannot instantiate as it does not have reference to Mapview due to use of SupportMapFragment. SupportMapFragment does not have access to Mapview. Can you please guide how to instantiate SymbolManager when used with SupportMapFragment.

Thanking you in advance,
TankJK

**Comment by tobrun** [comment]
Two options:
You can get a reference, if you let your Activity implement `OnMapReadyCallback` or you can call `supportMapFragment#getView()` and cast it to `MapView`. The benefit of the former suggestion is that you don't need to worry about state management of the fragment lifecycle (and thus avoiding the management around getView potentially returning null).

**Comment by TankJK** [comment]
Thank you for your answer. It works
