### ISSUE TITLE
Create Info Window above annotations

### ISSUE THREAD

**Issue by philoez98** [mapbox/mapbox-plugins-android#953]
Hello,
I'm using the annotation plugin and I need to show for every marker (hundreds) on the map its own info window. I tried the solution proposed in the examples, but couldn't make it work. Is there a nicer (or easier) way of doing so? Maybe like with the older marker API.

Thanks

**Comment by LukasPaczos** [comment]
Thanks for using Mapbox @philoez98! Unfortunately, there are no alternatives right now besides examples linked in https://github.com/mapbox/mapbox-plugins-android/issues/649.

Feel free to reach out to our [support team](https://www.mapbox.com/contact/) or stackoverflow if you need more assistance.
