### ISSUE TITLE
PlaceAutocomplete does not set toolbarColor

### ISSUE THREAD

**Issue by Firzen7** [mapbox/mapbox-plugins-android#954]
Hi, I am using your PlaceAutocomplete activity, but when I set toolbarColor using PlaceOptions.builder(), it doesn't do anything, and toolbar remains black.

It doesn't work in emulator either, no matter the Android version apparently. It doesn't even work in MapBox Demo appliaction on GooglePlay (https://play.google.com/store/apps/details?id=com.mapbox.mapboxandroiddemo&hl=en) - once I open the places autocomplete activity, toolbar turns black.

I have looked at the source of MapBox Demo app, and I am using very similar code:

> Intent intent = new PlaceAutocomplete.IntentBuilder()
		.accessToken(FrontendConstants.MAPBOX_API_TOKEN)
		.placeOptions(PlaceOptions.builder()
				.backgroundColor(Color.parseColor("#144259"))
				.toolbarColor(getResources().getColor(R.color.colorStatusBar))
				.limit(10)
				.proximity(Point.fromLngLat(loc.getLongitude(), loc.getLatitude()))
				.build(PlaceOptions.MODE_CARDS))
		.build(this);
startActivityForResult(intent, FrontendConstants.PLACES_REQUEST_CODE);

I am sure it will be easy to fix for you. It sadly seems impossible to override this behaviour for me. Thank you!

**Comment by Firzen7** [comment]
I have uploaded video where you can see the problem demonstrated in MapBox Demo application downloaded from Google Play: https://youtu.be/05zcXKZ2rrI

**Comment by langsmith** [comment]
Hey @Firzen7 , thanks for using Mapbox. Can confirm that [the _status bar_](https://material.io/design/platform-guidance/android-bars.html#status-bar) remains black. Logic for setting the toolbar color is working just fine.

From the plugin test app:
![ezgif com-resize](https://user-images.githubusercontent.com/4394910/58146762-60fa9f00-7c0c-11e9-9a85-1b39377deca2.gif)

**Comment by Firzen7** [comment]
@langsmith Thank you for sorting this out! And yes, you are right, it is a statusBar, not toolBar, sorry. :-)

**Comment by langsmith** [comment]
You're welcome @Firzen7 . #962 just landed, so until we release a new version of the plugin, you could use the plugin's SNAPSHOT to get access to #962   https://github.com/mapbox/mapbox-plugins-android/tree/master/plugin-places#getting-started .

cc @LukasPaczos
