### ISSUE TITLE
SymbolManager not adding Symbols to Offline Map

### ISSUE THREAD

**Issue by Sanunez** [mapbox/mapbox-plugins-android#970]
I'm attempting to add symbols onto an offline map, but markers do not show up on the offline map. As soon as I turn wifi or data back on the markers show up.

I need for symbols to be able to be placed without Internet connection. Is this normal behaviour?

**Comment by tobrun** [comment]
@Sanunez are these symbols using any text? If yes, this could be explained by missing font resources that need to be fetched from the internet.

**Comment by Sanunez** [comment]
Yes, Each symbol has a requirement to show a label with its title. I will try removing the text and reporting back the behaviour.

**Comment by Sanunez** [comment]
It seems that removing the text did fix the rendering issue, however the text are part of the use case requirements. Is it possible to download a style and fonts along side the offline map tiles for offline use?

**Comment by tobrun** [comment]
the fonts are automatically downloaded as part of the offline download. I'm guessing that the provided textFont doesn't match the one from the download (I had some issues myself with getting the correct value while looking into this issue).

For me the following configuration worked when using `Style.MAPBOX_STREETS`:

```java 
    mapView.getMapAsync(mapboxMap -> mapboxMap.setStyle(Style.MAPBOX_STREETS, style -> {
      findViewById(R.id.fabStyles).setOnClickListener(v -> mapboxMap.setStyle(Style.DARK));

      mapboxMap.moveCamera(CameraUpdateFactory.newLatLngZoom(new LatLng(50.846317, 5.698414), 17));

      style.addImage(ID_ICON, BitmapUtils.getBitmapFromDrawable(getResources().getDrawable(R.drawable.mapbox_marker_icon_default)));

      // create symbol manager
      symbolManager = new SymbolManager(mapView, mapboxMap, style);
      symbolManager.setIconAllowOverlap(true);
      symbolManager.setTextAllowOverlap(true);

      // create a symbol
      SymbolOptions symbolOptions = new SymbolOptions()
        .withLatLng(new LatLng(50.846202, 5.69738))
        .withIconImage(ID_ICON)
        .withTextFont(new String[]{"DIN Offc Pro Regular", "Arial Unicode MS Regular"})
        .withTextField("Hello World");
      symbol = symbolManager.create(symbolOptions);
    }));
```

![ezgif com-video-to-gif (73)](https://user-images.githubusercontent.com/2151639/58948063-96b19300-8789-11e9-8788-936cb6345122.gif)

I looked up the font in the SQL database which is located at: 
 - /data/data/your/package/files/mbgl-offline.db

and you can open this with a SQLite browser and check the data in `resources` table.

**Comment by kiskunk** [comment]
Could this be reopened to note that this only works if you can get away with using those 2 fonts, since for example no Roboto fonts being downloaded, and there should be a way to define that instead of these 2 fonts.

**Comment by tylerbGCI** [comment]
> For me the following configuration worked when using `Style.MAPBOX_STREETS`:

This worked when i switched from my custom style to STREETS, but were you able to accomplish this when using a custom style? I have the mbgl-offline.db on my device. I was trying to find the line where STREETS references the db and copy it into my custom style
