### ISSUE TITLE
ScaleBar incorrect values

### ISSUE THREAD

**Issue by paulsUsername** [mapbox/mapbox-plugins-android#972]
Scale bar is out of sync with the map. 

Adding scalebar like so:

```
val scaleBar = ScaleBarPlugin(mapView, mapboxMap)
scaleBar.create(ScaleBarOptions(safeContext))
scaleBar.isEnabled = true
```

Result:

![WhatsApp Image 2019-06-02 at 16 40 11](https://user-images.githubusercontent.com/32492218/58763001-2a028280-8556-11e9-805f-6e8bf43417bf.jpeg)

For reference see iOS version:
![WhatsApp Image 2019-06-02 at 16 43 47](https://user-images.githubusercontent.com/32492218/58763008-35ee4480-8556-11e9-8c14-f5dc6be53d21.jpeg)

**Comment by paulsUsername** [comment]
I've tested the map, it is definitely showing at the correct scale.

**Comment by tobrun** [comment]
cc @Chaoba

**Comment by Chaoba** [comment]
@paulsUsername Thanks for reporting. Could you please add the zoom level and `LatLng` of the above picture?

**Comment by paulsUsername** [comment]
LatLng [latitude=52.47182821970851, longitude=-6.73574977924693, altitude=0.0], Zoom:12.067948539510445, Bearing:-0.0, Tilt:0.0

That is the location for the below screenshot:

![WhatsApp Image 2019-06-04 at 09 41 48](https://user-images.githubusercontent.com/32492218/58864664-0e5dc000-86ad-11e9-8484-1a0788a25d09.jpeg)

**Comment by paulsUsername** [comment]
It looks to me like its showing 1-mile distances as 1 km.
