### ISSUE TITLE
Add device location button in Place Picker activity 

### ISSUE THREAD

**Issue by langsmith** [mapbox/mapbox-plugins-android#973]
Creating this ticket to track @androideveloper 's request for [a way to enable "My location" button in Place Picker page that zooms to user current location](https://github.com/mapbox/mapbox-plugins-android/pull/965#issuecomment-498043305)

Floating action button would be added to the [PlacePickerActivity](https://github.com/mapbox/mapbox-plugins-android/blob/master/plugin-places/src/main/java/com/mapbox/mapboxsdk/plugins/places/picker/ui/PlacePickerActivity.java) XML layout and we'd use the Maps SDK's `LocationComponent` in the activity.

<img width="636" alt="Screen Shot 2019-06-03 at 10 37 46 AM" src="https://user-images.githubusercontent.com/4394910/58822143-a4311680-85eb-11e9-8ec7-9f5ed2d312eb.png">

**Comment by androideveloper** [comment]
Great! In that case Place Picker can replace our custom solution.
