### ISSUE TITLE
androidX :ERROR: Failed to resolve: legacy-support-core-utils 

### ISSUE THREAD

**Issue by MohammadSommakia** [mapbox/mapbox-plugins-android#974]
i got this error when trying to migrate my android app to androidX 
with this     implementation 'com.mapbox.mapboxsdk:mapbox-android-sdk:7.3.0'
but it's ok with : 
    implementation 'com.mapbox.mapboxsdk:mapbox-android-plugin-localization-v7:0.8.0'
    implementation 'com.mapbox.mapboxsdk:mapbox-sdk-services:4.6.0'

**Comment by abdulmalekDery** [comment]
خلص يا أخي خليك على الإصدار القديم أمرك لله

**Comment by kamlyMopu** [comment]
Is the problem resolved?

**Comment by kamlyMopu** [comment]
I am also involved with this problem

**Comment by MohammadSommakia** [comment]
Unfortunately, the problem has not been solved. It is clear that mapbox did not support Androidx until now
