### ISSUE TITLE
Not supporting all possible languages

### ISSUE THREAD

**Issue by leocarona** [mapbox/mapbox-plugins-android#978]
I'm using [plugin-localization](https://github.com/mapbox/mapbox-plugins-android/tree/master/plugin-localization) expecting mapbox to get translated into Portuguese, but it doesn't.
I set up my phone in Brazilian Portuguese, restarted the phone, but labels on the map are displayed in English. 
According to [this article](https://docs.mapbox.com/help/troubleshooting/change-language/) it's possible to translate mapbox labels into Portuguese.

**Comment by langsmith** [comment]
#979 resolved this and #979 was included in a new version of the Localization Plugin, [which was released a couple of days ago](https://github.com/mapbox/mapbox-plugins-android/issues/987).
