### ISSUE TITLE
MakerView update delay

### ISSUE THREAD

**Issue by Chaoba** [mapbox/mapbox-plugins-android#981]
There are two phenomenons related to markerview update delay and could be reproduced by test app in this repo.
1. When open a new activity all markers will be firstly shown on the left top corner and then updated to their correct location.
2. When zooming out/in or sliding mapview, markers will be updated with a obvious delay.

Possible solution:
1. Call `markerView.update();` when add a new maker.
2. Instead of `OnDidFinishRenderingFrameListener`, use `OnCameraDidChangeListener` to update maker's position.

@tobrun What do you think?

**Comment by tobrun** [comment]
Sounds good! 

> Instead of OnDidFinishRenderingFrameListener, use OnCameraDidChangeListener to update maker's position.

Can we [profile](https://developer.android.com/studio/profile/inspect-gpu-rendering) the differences?
