### ISSUE TITLE
Allowing multiple SymbolManagers

### ISSUE THREAD

**Issue by NitroG42** [mapbox/mapbox-plugins-android#986]
Right now, if I'm not mistaken, we can only add one SymbolManager (and others) to a map.
The issue for our case is that we have a big numbers of annotations (> 1000) that have different type and different ways to be added/removed to the map.
Example of performance issues (I think at least) we have is we have 8000 symbols, we need to remove 1000 from this, which are removed from the main thread and is costly. 
Example of issue can also appears in click because there is no way to add a tag to a symbol, so if two type of symbol have different click listeners, we need to use "hacks" to handle them.

My suggestion here is to allow multiple managers to be added (as different layers I suppose) to the map, so we can easily have one manager for a type, which greatly reduce the hassle (we can remove all symbols in one manager but not the others, handle click only etc...)
Right now (I think) it's not possible because a SymbolManager is created with a fixed layer id : 
```public static final String ID_GEOJSON_LAYER = "mapbox-android-symbol-layer";```
and we can't change it because the constructor is package protected.

**Comment by langsmith** [comment]
Hey @NitroG42 , thanks for using 

Have you seen https://github.com/mapbox/mapbox-plugins-android/pull/941? Seems that it'd solve what you're trying to do.

[I'm about to release a new version of the Annotation Plugin](https://github.com/mapbox/mapbox-plugins-android/issues/987), which will include #941 or you can try out [the current SNAPSHOT of the plugin](https://github.com/mapbox/mapbox-plugins-android/tree/master/plugin-annotation#getting-started) if you'd rather not wait the 1-3 hours that it takes for a release to roll out. 

Going to close. If neither the new release or SNAPSHOT solve your issue, feel free to ping us again.

**Comment by NitroG42** [comment]
My bad, I search only in issues, not in pull request.
Very happy that it will come so quickly, thanks for your work !
