### ISSUE TITLE
When adding symbol with 'withIconRotate', symbols are not rotating when map rotates

### ISSUE THREAD

**Issue by nijs9** [mapbox/mapbox-plugins-android#991]
### Steps to reproduce

 1. Add a symbol on a map with the withIconRotate property set to a value higher then 0
 2. Rotate map.
 3. Map is rotating, but symbols are not rotating with the map.

### Expected behavior

Symbols rotating in the same direction as map rotation

### Actual behavior

Symbols are not rotating with map. My symbols have an arrow image to give a direction suggestion, so they have to rotate with map otherwise directions are not correct anymore.

### Configuration

**Android versions:*7 and 9* 
**Device models:*Moto G5S* 
**Mapbox SDK versions:*7.1.1*

**Comment by LukasPaczos** [comment]
I've transferred this issue to the plugins repo.

In order to make all your symbols within one manager to be tied to a map rotation-wise, you need to call `symbolManager.setIconRotationAlignment(Property.ICON_ROTATION_ALIGNMENT_MAP)`.

**Comment by nijs9** [comment]
Thanks a lot!
