### ISSUE TITLE
GroundOverlay with mapbox SDK

### ISSUE THREAD

**Issue by khanyasirforu** [mapbox/mapbox-plugins-android#998]
I was trying to migrate my project from google maps to Mapbox Maps for Android and iOS.

Android one i am able to migrate as its APIs are quite similar to what google offers, Its not case in iOS.

On Android there is one thing is missing which i am using extensively i.e. GroundOverlay. I saw there is a provision to add one using ImageSource, now question is do Mapbox support all properties of GroundOverlay?

**Comment by LukasPaczos** [comment]
Hey @khanyasirforu thanks for using Mapbox! It looks to me like you can achieve `GroundOverlay` functionality with either `RasterLayer` + `ImageSource` or a `SymbolLayer` (using [`PropertyFactory#iconImage`](https://docs.mapbox.com/android/api/map-sdk/8.1.0/com/mapbox/mapboxsdk/style/layers/PropertyFactory.html#iconImage-java.lang.String-) and [`Style#addImage`](https://docs.mapbox.com/android/api/map-sdk/8.1.0/com/mapbox/mapboxsdk/maps/Style.html#addImage-java.lang.String-android.graphics.Bitmap-) to provide the bitmap) + `GeoJsonSource`. If you'd like to use the [`AnnotationPlugin`](https://github.com/mapbox/mapbox-plugins-android/tree/master/plugin-annotation), check out [`SymbolOptions#withIconImage`](https://github.com/mapbox/mapbox-plugins-android/blob/5a787b06660ce2d8332cb2451b1a3da64e6fb090/plugin-annotation/src/main/java/com/mapbox/mapboxsdk/plugins/annotation/SymbolOptions.java#L144) and again [`Style#addImage`](https://docs.mapbox.com/android/api/map-sdk/8.1.0/com/mapbox/mapboxsdk/maps/Style.html#addImage-java.lang.String-android.graphics.Bitmap-).Please reach out to [our support](https://docs.mapbox.com/help/) if you have any further questions as this repo is used for bug reports and feature requests only.

**Comment by khanyasirforu** [comment]
Hi @LukasPaczos Thanks for update, i tried using AnnotationPlugin, but marker size is not changing when zoom level changes. Sure i will contact support team for further questions

**Comment by LukasPaczos** [comment]
@khanyasirforu unfortunately, the AnnotationPlugin doesn't support [expressions](https://docs.mapbox.com/mapbox-gl-js/style-spec/#expressions) yet, this is tracked in https://github.com/mapbox/mapbox-plugins-android/issues/736. For scaling to work, you'll need to use `Layer` API itself with [`zoom`](https://docs.mapbox.com/android/api/map-sdk/8.1.0/com/mapbox/mapboxsdk/style/expressions/Expression.html#zoom--) expression as the [`icon-size`](https://docs.mapbox.com/android/api/map-sdk/8.1.0/com/mapbox/mapboxsdk/style/layers/PropertyFactory.html#iconSize-com.mapbox.mapboxsdk.style.expressions.Expression-) property.
